#include "pch.h"
#include "Core.h"
#include <shlwapi.h>
#include <cmath>
using namespace winrt;
using namespace Windows::Data::Json;
namespace guodesk {
std::wstring NewId(){ GUID id{}; check_hresult(CoCreateGuid(&id)); wchar_t text[40]{}; StringFromGUID2(id,text,40); return text; }
std::wstring PathKey(std::wstring const& value){ auto p=std::filesystem::absolute(value).lexically_normal().wstring(); std::replace(p.begin(),p.end(),L'/',L'\\'); CharLowerBuffW(p.data(),static_cast<DWORD>(p.size())); while(p.size()>3 && p.back()==L'\\')p.pop_back(); return p; }
bool AddEntry(Zone& z,std::wstring const& path){if(path.empty())return false; auto key=PathKey(path); for(auto const& e:z.entries)if(PathKey(e.path)==key)return false; z.entries.push_back({NewId(),std::filesystem::absolute(path).lexically_normal().wstring()}); return true;}
void SyncMapped(Zone& z){if(z.mappedFolder.empty())return; std::error_code ec;std::filesystem::directory_iterator it(std::filesystem::path(z.mappedFolder),ec);if(ec)return;struct Item{std::wstring name,path;bool dir;};std::vector<Item> items;for(auto const& e:it){std::error_code de;bool dir=e.is_directory(de);items.push_back({e.path().filename().wstring(),e.path().wstring(),dir});}std::sort(items.begin(),items.end(),[](Item const& a,Item const& b){if(a.dir!=b.dir)return a.dir>b.dir;return StrCmpLogicalW(a.name.c_str(),b.name.c_str())<0;});z.entries.clear();for(auto const& i:items)z.entries.push_back({NewId(),i.path});}
void Clamp(Zone& z,RECT const& a){int w=std::max(1L,a.right-a.left),h=std::max(1L,a.bottom-a.top); z.width=std::clamp(z.width,std::min(280,w),w); z.height=std::clamp(z.height,std::min(160,h),h); z.x=std::clamp(z.x,static_cast<int>(a.left),static_cast<int>(a.right)-z.width); z.y=std::clamp(z.y,static_cast<int>(a.top),static_cast<int>(a.bottom)-(z.collapsed?std::min(64,h):z.height));}
std::string Serialize(Layout const& l){JsonObject root; root.SetNamedValue(L"version",JsonValue::CreateNumberValue(1)); JsonArray zones; for(auto const& z:l.zones){JsonObject j; j.SetNamedValue(L"id",JsonValue::CreateStringValue(z.id)); j.SetNamedValue(L"name",JsonValue::CreateStringValue(z.name)); j.SetNamedValue(L"x",JsonValue::CreateNumberValue(z.x));j.SetNamedValue(L"y",JsonValue::CreateNumberValue(z.y));j.SetNamedValue(L"width",JsonValue::CreateNumberValue(z.width));j.SetNamedValue(L"height",JsonValue::CreateNumberValue(z.height));j.SetNamedValue(L"collapsed",JsonValue::CreateBooleanValue(z.collapsed)); j.SetNamedValue(L"mappedFolder",JsonValue::CreateStringValue(z.mappedFolder)); j.SetNamedValue(L"viewMode",JsonValue::CreateStringValue(z.viewMode)); j.SetNamedValue(L"nameLines",JsonValue::CreateNumberValue(z.nameLines)); JsonArray entries;for(auto const& e:z.entries){JsonObject item;item.SetNamedValue(L"id",JsonValue::CreateStringValue(e.id));item.SetNamedValue(L"path",JsonValue::CreateStringValue(e.path));entries.Append(item);}j.SetNamedValue(L"entries",entries);zones.Append(j);}root.SetNamedValue(L"zones",zones);JsonObject s;s.SetNamedValue(L"theme",JsonValue::CreateStringValue(l.settings.theme));s.SetNamedValue(L"compact",JsonValue::CreateBooleanValue(l.settings.compact));root.SetNamedValue(L"settings",s);return to_string(root.Stringify());}
Layout Deserialize(std::string const& text){auto root=JsonObject::Parse(to_hstring(text)); if(root.GetNamedNumber(L"version")!=1)throw std::runtime_error("Unsupported layout version"); Layout l;std::vector<std::wstring> ids;auto number=[](JsonObject const& j,wchar_t const* key){double n=j.GetNamedNumber(key);if(!std::isfinite(n)||n < -100000 || n > 100000)throw std::runtime_error("Invalid geometry");return static_cast<int>(n);};for(auto const& value:root.GetNamedArray(L"zones")){auto j=value.GetObject();Zone z;z.id=j.GetNamedString(L"id");z.name=j.GetNamedString(L"name");if(z.id.empty()||std::find(ids.begin(),ids.end(),z.id)!=ids.end())throw std::runtime_error("Invalid zone identity");ids.push_back(z.id);z.x=number(j,L"x");z.y=number(j,L"y");z.width=number(j,L"width");z.height=number(j,L"height");if(z.width<=0||z.height<=0)throw std::runtime_error("Invalid size");z.collapsed=j.GetNamedBoolean(L"collapsed");if(j.HasKey(L"mappedFolder"))z.mappedFolder=std::wstring(j.GetNamedString(L"mappedFolder"));if(j.HasKey(L"viewMode")){z.viewMode=std::wstring(j.GetNamedString(L"viewMode"));if(z.viewMode!=L"grid"&&z.viewMode!=L"list")z.viewMode=L"grid";}if(j.HasKey(L"nameLines")){double n=j.GetNamedNumber(L"nameLines");z.nameLines=(n>=0&&n<=2&&n==static_cast<int>(n))?static_cast<int>(n):2;}for(auto const& ev:j.GetNamedArray(L"entries")){auto ej=ev.GetObject();std::wstring p(ej.GetNamedString(L"path")),id(ej.GetNamedString(L"id"));if(p.empty()||!std::filesystem::path(p).is_absolute()||id.empty()||std::find(ids.begin(),ids.end(),id)!=ids.end())throw std::runtime_error("Invalid entry");ids.push_back(id);if(AddEntry(z,p))z.entries.back().id=id;}l.zones.push_back(std::move(z));}if(root.HasKey(L"settings")){auto s=root.GetNamedObject(L"settings");if(s.HasKey(L"theme"))l.settings.theme=std::wstring(s.GetNamedString(L"theme"));if(s.HasKey(L"compact"))l.settings.compact=s.GetNamedBoolean(L"compact");}return l;}
Store::Store(std::filesystem::path root):directory(std::move(root)){if(directory.empty()){PWSTR path{};check_hresult(SHGetKnownFolderPath(FOLDERID_LocalAppData,0,nullptr,&path));directory=std::filesystem::path(path)/L"GuoDesk";CoTaskMemFree(path);}std::filesystem::create_directories(directory);}
static std::string Read(std::filesystem::path const& p){std::ifstream f(p,std::ios::binary);if(!f)throw std::runtime_error("Cannot read layout");return {std::istreambuf_iterator<char>(f),{}};}
Layout Store::Load(std::wstring& warning){auto main=directory/L"layout.json",backup=directory/L"layout.backup.json";if(!std::filesystem::exists(main)){if(std::filesystem::exists(backup)){warning=L"主配置缺失，已从备份恢复。";return Deserialize(Read(backup));}Zone z;z.id=NewId();return {{z}};}try{return Deserialize(Read(main));}catch(...){auto preserved=directory/(L"layout.corrupt."+std::to_wstring(GetTickCount64())+L".json");std::filesystem::copy_file(main,preserved);warning=L"配置损坏，已保留原文件。";try{auto result=Deserialize(Read(backup));std::filesystem::remove(main);warning+=L"已从备份恢复。";return result;}catch(...){std::filesystem::remove(main);warning+=L"使用新的默认分区。";Zone z;z.id=NewId();return {{z}};}}}
void Store::Save(Layout const& l){auto main=directory/L"layout.json",temp=directory/L"layout.tmp",backup=directory/L"layout.backup.json";auto data=Serialize(l);HANDLE file=CreateFileW(temp.c_str(),GENERIC_WRITE,0,nullptr,CREATE_ALWAYS,FILE_ATTRIBUTE_NORMAL,nullptr);if(file==INVALID_HANDLE_VALUE)throw std::runtime_error("Cannot create layout temporary file");DWORD written{};bool ok=WriteFile(file,data.data(),static_cast<DWORD>(data.size()),&written,nullptr)&&written==data.size()&&FlushFileBuffers(file);CloseHandle(file);if(!ok)throw std::runtime_error("Cannot write layout");if(std::filesystem::exists(main)){if(!ReplaceFileW(main.c_str(),temp.c_str(),backup.c_str(),REPLACEFILE_IGNORE_MERGE_ERRORS,nullptr,nullptr))throw std::runtime_error("Cannot replace layout");}else if(!MoveFileExW(temp.c_str(),main.c_str(),MOVEFILE_WRITE_THROUGH|MOVEFILE_REPLACE_EXISTING))throw std::runtime_error("Cannot save layout");}
}

