#include "pch.h"
#include "DeskWindow.h"
#include "TidyWindow.h"
#include "NoteWindow.h"
#include "TodoWindow.h"
#include "ClockWindow.h"
#include "GuideWindow.h"
#include "MusicWindow.h"
#include "SearchWindow.h"
#include "WeatherWindow.h"
#include "Shell.h"
#include "I18n.h"
using namespace winrt;
using namespace Microsoft::UI::Xaml;
using namespace Microsoft::UI::Xaml::Controls;
using namespace Microsoft::UI::Xaml::Media;
using namespace Microsoft::UI::Xaml::Media::Animation;
using namespace Windows::ApplicationModel::DataTransfer;
namespace guodesk {
static Brush ResolveBrush(wchar_t const* key,Windows::UI::Color fallback,bool dark){
 try{
  auto res=Application::Current().Resources();
  return res.Lookup(box_value(key)).as<Brush>();
 }catch(...){}
 struct Entry{wchar_t const* key;Windows::UI::Color light;Windows::UI::Color dark;};
 static const Entry palette[]{
  {L"CardBackgroundFillColorDefault",{255,248,248,248},{255,43,43,43}},
  {L"CardBackgroundFillColorSecondary",{255,244,244,244},{255,54,54,54}},
  {L"SubtleFillColorSecondaryBrush",{255,236,236,236},{255,56,56,56}},
  {L"TextFillColorSecondary",{255,97,97,97},{255,199,199,199}},
  {L"ApplicationPageBackgroundThemeBrush",{255,243,243,243},{255,32,32,32}},
 };
 for(auto const& e:palette)if(!wcscmp(e.key,key))return SolidColorBrush(dark?e.dark:e.light);
 return SolidColorBrush(fallback);
}
Brush DeskWindow::ThemeBrush(wchar_t const* key,Windows::UI::Color fallback){return ResolveBrush(key,fallback,root.ActualTheme()==ElementTheme::Dark);}
static Button Action(wchar_t const* glyph,std::function<void()> run){FontIcon f;f.FontFamily(FontFamily(L"Segoe Fluent Icons"));f.Glyph(glyph);f.FontSize(16);Button b;b.Content(f);b.Background(nullptr);b.BorderThickness(Thickness{0});b.Click([run](auto&&,auto&&){try{run();}catch(hresult_error const& e){MessageBoxW(nullptr,e.message().c_str(),L"GuoDesk",MB_OK|MB_ICONERROR);}catch(std::exception const&){MessageBoxW(nullptr,i18n::Tr(L"操作未完成，请检查路径或访问权限。").c_str(),L"GuoDesk",MB_OK|MB_ICONERROR);}});return b;}
static MenuFlyoutItem MenuItem(std::wstring const& text,std::function<void()> run){MenuFlyoutItem b;b.Text(text);b.Click([run](auto&&,auto&&){try{run();}catch(...){MessageBoxW(nullptr,i18n::Tr(L"操作未完成，请检查文件是否存在及访问权限。").c_str(),L"GuoDesk",MB_OK|MB_ICONERROR);}});return b;}
static int Snap(int value,std::vector<int> const& targets,int threshold){int delta=0,best=threshold+1;for(int t:targets){int d=t-value,ad=d<0?-d:d;if(ad<best){best=ad;delta=d;}}return best<=threshold?delta:0;}
Zone& DeskWindow::Model(){return *std::find_if(owner.layout.zones.begin(),owner.layout.zones.end(),[this](auto const& z){return z.id==id;});}
Zone& DeskWindow::View(){auto& m=Model();auto members=GroupMemberIds(owner.layout,m.group);if(members.empty()||m.group.empty())return m;for(auto& z:owner.layout.zones)if(z.id==viewId)return z;viewId=m.id;return m;}
DeskWindow::DeskWindow(Controller& c,std::wstring key):owner(c),id(std::move(key)){
 window=Window();window.Title(L"GuoDesk");hwnd=shell::Handle(window);
 root=Grid();window.SystemBackdrop(MicaBackdrop());root.Padding(Thickness{12,12,12,12});root.RowSpacing(8);
 RowDefinition tabsRow;tabsRow.Height(GridLength{0,GridUnitType::Auto});root.RowDefinitions().Append(tabsRow);RowDefinition header;header.Height(GridLength{44,GridUnitType::Pixel});root.RowDefinitions().Append(header);RowDefinition body;body.Height(GridLength{1,GridUnitType::Star});root.RowDefinitions().Append(body);RowDefinition footer;footer.Height(GridLength{0,GridUnitType::Auto});root.RowDefinitions().Append(footer);
 tabsPanel=StackPanel();tabsPanel.Orientation(Orientation::Horizontal);tabsPanel.Spacing(4);tabsPanel.VerticalAlignment(VerticalAlignment::Center);Grid::SetRow(tabsPanel,0);tabsPanel.Visibility(Visibility::Collapsed);root.Children().Append(tabsPanel);
 Grid bar;ColumnDefinition col;col.Width(GridLength{1,GridUnitType::Star});bar.ColumnDefinitions().Append(col);ColumnDefinition buttons;buttons.Width(GridLength{0,GridUnitType::Auto});bar.ColumnDefinitions().Append(buttons);Grid::SetRow(bar,1);barGrid=bar;
 title=TextBox();title.Text(Model().name);title.PlaceholderText(i18n::Tr(L"分区名称"));title.Background(SolidColorBrush(Windows::UI::Colors::Transparent()));title.BorderThickness(Thickness{0});title.FontSize(16);title.FontWeight(Windows::UI::Text::FontWeights::SemiBold());title.VerticalContentAlignment(VerticalAlignment::Center);title.Padding(Thickness{4,11,4,11});ToolTipService::SetToolTip(title,box_value(i18n::Tr(L"点击重命名分区")));auto TitleFill=[this](bool hover){Brush fill=SolidColorBrush(Windows::UI::Colors::Transparent());if(hover)fill=ThemeBrush(L"SubtleFillColorSecondaryBrush",Windows::UI::Color{13,0,0,0});title.Background(fill);};title.PointerEntered([TitleFill](auto&&,auto&&){TitleFill(true);});title.PointerExited([TitleFill](auto&&,auto&&){TitleFill(false);});title.LostFocus([this](auto&&,auto&&){auto name=std::wstring(title.Text());if(name.empty())name=i18n::Tr(L"未命名分区");View().name=name;title.Text(name);window.Title(L"GuoDesk · "+name);owner.Save();});bar.Children().Append(title);
 StackPanel actions;actions.Orientation(Orientation::Horizontal);actions.Spacing(4);actions.VerticalAlignment(VerticalAlignment::Center);Grid::SetColumn(actions,1);
 Border dragHandle;FontIcon dragIcon;dragIcon.FontFamily(FontFamily(L"Segoe Fluent Icons"));dragIcon.Glyph(L"\uE7C2");dragIcon.FontSize(16);dragHandle.Child(dragIcon);dragHandle.Padding(Thickness{6,4,6,4});dragHandle.CornerRadius(CornerRadius{4,4,4,4});dragHandle.Background(SolidColorBrush(Windows::UI::Colors::Transparent()));ToolTipService::SetToolTip(dragHandle,box_value(i18n::Tr(L"按住移动分区")));auto HandleHover=[dragHandle,this](bool hover){Brush fill=SolidColorBrush(Windows::UI::Colors::Transparent());if(hover)fill=ThemeBrush(L"SubtleFillColorSecondaryBrush",Windows::UI::Color{13,0,0,0});dragHandle.Background(fill);};dragHandle.PointerEntered([dragHandle,HandleHover](auto&&,auto&&){HandleHover(true);});dragHandle.PointerExited([dragHandle,HandleHover](auto&&,auto&&){HandleHover(false);});embedTimer=root.DispatcherQueue().CreateTimer();embedTimer.Interval(std::chrono::milliseconds(16));embedTimer.Tick([this](auto&&,auto&&){if(!dragging){embedTimer.Stop();return;}if(!(GetAsyncKeyState(VK_LBUTTON)&0x8000)){embedTimer.Stop();dragging=false;Capture();owner.Save();return;}DragUpdate();});dragHandle.PointerPressed([this,dragHandle](auto&&,Input::PointerRoutedEventArgs const& a)mutable{dragging=true;GetCursorPos(&dragStart);GetWindowRect(hwnd,&dragOrigin);if(!desktop)dragHandle.CapturePointer(a.Pointer());else embedTimer.Start();a.Handled(true);});auto DragMove=[this](auto&&,auto&&){DragUpdate();};dragHandle.PointerMoved(DragMove);root.PointerMoved(DragMove);title.PointerMoved(DragMove);auto EndDrag=[this](auto&&,auto&&){if(!dragging)return;dragging=false;Capture();owner.Save();};dragHandle.PointerReleased(EndDrag);dragHandle.PointerCaptureLost(EndDrag);root.PointerReleased(EndDrag);actions.Children().Append(dragHandle);
auto add=Action(L"\uE710",[this]{Pick();});ToolTipService::SetToolTip(add,box_value(i18n::Tr(L"添加入口")));add.PointerMoved(DragMove);actions.Children().Append(add);
 chevron=Action(L"\uE70E",[this]{Capture();Model().collapsed=!Model().collapsed;Refresh();Place();owner.Save();});ToolTipService::SetToolTip(chevron,box_value(i18n::Tr(L"折叠 / 展开")));chevron.PointerMoved(DragMove);actions.Children().Append(chevron);
 auto more=Action(L"\uE712",[]{});ToolTipService::SetToolTip(more,box_value(i18n::Tr(L"更多操作")));more.Click([this,more](auto&&,auto&&){Menu(more);});more.PointerMoved(DragMove);actions.Children().Append(more);bar.Children().Append(actions);root.Children().Append(bar);
 grid=GridView();grid.SelectionMode(ListViewSelectionMode::None);grid.IsItemClickEnabled(false);grid.AllowDrop(true);grid.HorizontalAlignment(HorizontalAlignment::Stretch);Grid::SetRow(grid,2);root.Children().Append(grid);
 grid.DragOver([this](auto&&,DragEventArgs const& a){a.AcceptedOperation(!View().mappedFolder.empty()?DataPackageOperation::None:(a.DataView().Contains(StandardDataFormats::StorageItems())?DataPackageOperation::Link:DataPackageOperation::Move));a.Handled(true);});grid.Drop([this](auto&&,DragEventArgs const& a){if(!View().mappedFolder.empty()){Notify(i18n::Tr(L"映射分区为只读视图，无法拖入。"));return;}Drop(a,View().entries.size());});
 listHost=ScrollViewer();listPanel=StackPanel();listPanel.Orientation(Orientation::Vertical);listPanel.Spacing(2);listPanel.Padding(Thickness{2,2,2,2});listHost.Content(listPanel);listHost.AllowDrop(true);listHost.Visibility(Visibility::Collapsed);Grid::SetRow(listHost,2);root.Children().Append(listHost);
 listHost.DragOver([this](auto&&,DragEventArgs const& a){a.AcceptedOperation(View().mappedFolder.empty()?(a.DataView().Contains(StandardDataFormats::StorageItems())?DataPackageOperation::Link:DataPackageOperation::Move):DataPackageOperation::None);a.Handled(true);});listHost.Drop([this](auto&&,DragEventArgs const& a){a.Handled(true);if(!View().mappedFolder.empty()){Notify(i18n::Tr(L"映射分区为只读视图，无法拖入。"));return;}Drop(a,View().entries.size());});
 status=TextBlock();status.FontSize(11);status.TextWrapping(TextWrapping::Wrap);status.Foreground(ThemeBrush(L"TextFillColorSecondary",Windows::UI::Color{255,160,160,160}));Grid::SetRow(status,3);root.Children().Append(status);
 auto members=GroupMemberIds(owner.layout,Model().group);viewId=members.empty()?id:(Model().groupTab<static_cast<int>(members.size())?members[static_cast<size_t>(Model().groupTab)]:members.front());
 pill=Border();pill.CornerRadius(CornerRadius{20,20,20,20});pill.Height(36);pill.Padding(Thickness{10,0,10,0});pill.VerticalAlignment(VerticalAlignment::Center);pill.HorizontalAlignment(HorizontalAlignment::Stretch);Grid::SetRow(pill,1);StackPanel pillBox;pillBox.Orientation(Orientation::Horizontal);pillBox.Spacing(8);pillIcon=Image();pillIcon.Width(20);pillIcon.Height(20);pillGlyph=FontIcon();pillGlyph.FontFamily(FontFamily(L"Segoe Fluent Icons"));pillGlyph.Glyph(L"\uE8B7");pillGlyph.FontSize(16);pillName=TextBlock();pillName.FontSize(13);pillName.FontWeight(Windows::UI::Text::FontWeights::SemiBold());pillName.VerticalAlignment(VerticalAlignment::Center);pillName.TextTrimming(TextTrimming::CharacterEllipsis);pillBox.Children().Append(pillGlyph);pillBox.Children().Append(pillIcon);pillBox.Children().Append(pillName);pill.Child(pillBox);FontIcon grip;grip.FontFamily(FontFamily(L"Segoe Fluent Icons"));grip.Glyph(L"\uE7C2");grip.FontSize(14);grip.VerticalAlignment(VerticalAlignment::Center);pillBox.Children().InsertAt(0,grip);pill.Visibility(Visibility::Collapsed);pill.PointerPressed([this](auto&&,Input::PointerRoutedEventArgs const& a)mutable{dragging=true;GetCursorPos(&dragStart);GetWindowRect(hwnd,&dragOrigin);if(!desktop)pill.CapturePointer(a.Pointer());else embedTimer.Start();a.Handled(true);});pill.PointerMoved(DragMove);pill.PointerReleased(EndDrag);pill.PointerCaptureLost(EndDrag);pill.DoubleTapped([this](auto&&,auto&&){SetCapsule(false);Refresh();Place();owner.Save();});pill.ContextFlyout(nullptr);pill.RightTapped([this](auto&&,auto&&){Menu(pill);});root.Children().Append(pill);
 hoverTimer=root.DispatcherQueue().CreateTimer();hoverTimer.Interval(std::chrono::milliseconds(80));hoverTimer.Tick([this](auto&&,auto&&){if(dragging||closing)return;POINT p{};GetCursorPos(&p);RECT r{};GetWindowRect(hwnd,&r);if(PtInRect(&r,p))ExpandCapsule();else ShrinkCapsule();});
 if(Model().capsule)SetCapsule(true);
 window.Content(root);window.Closed([this](auto&&,WindowEventArgs const& args){if(!closing){args.Handled(true);ShowWindow(hwnd,SW_HIDE);}});
 SetWindowSubclass(hwnd,Subclass,1,reinterpret_cast<DWORD_PTR>(this));window.Activate();auto presenter=window.AppWindow().Presenter().as<Microsoft::UI::Windowing::OverlappedPresenter>();presenter.SetBorderAndTitleBar(true,false);window.AppWindow().IsShownInSwitchers(false);ApplySettings();Place();
 Storyboard fade;DoubleAnimation alpha;alpha.From(0.0);alpha.To(1.0);alpha.Duration(Duration{std::chrono::milliseconds(220),DurationType::TimeSpan});Storyboard::SetTarget(alpha,root);Storyboard::SetTargetProperty(alpha,L"Opacity");fade.Children().Append(alpha);fade.Begin();
}
DeskWindow::~DeskWindow(){closing=true;if(IsWindow(hwnd)){RemoveWindowSubclass(hwnd,Subclass,1);window.Close();}}
void DeskWindow::ApplySettings(){auto const& theme=owner.layout.settings.theme;root.RequestedTheme(theme==L"Dark"?ElementTheme::Dark:theme==L"Light"?ElementTheme::Light:ElementTheme::Default);status.Foreground(ThemeBrush(L"TextFillColorSecondary",Windows::UI::Color{255,160,160,160}));Refresh();}
void DeskWindow::Notify(std::wstring const& text){status.Text(text);}
void DeskWindow::Capture(){if(!IsWindow(hwnd))return;RECT r{};GetWindowRect(hwnd,&r);auto& z=Model();z.x=r.left;z.y=r.top;if(!capsuleNow)z.width=r.right-r.left;if(!z.collapsed&&!capsuleNow)z.height=r.bottom-r.top;MONITORINFOEXW mi{sizeof(mi)};GetMonitorInfoW(MonitorFromWindow(hwnd,MONITOR_DEFAULTTONEAREST),&mi);z.mon=mi.szDevice;z.mx=z.x-mi.rcWork.left;z.my=z.y-mi.rcWork.top;}
void DeskWindow::Place(){auto& z=Model();shell::Fit(z);POINT p{z.x,z.y};if(desktop)ScreenToClient(GetParent(hwnd),&p);int w=z.width,h=z.collapsed?88:z.height;if(capsuleNow){w=MulDiv(160,GetDpiForWindow(hwnd),96);h=MulDiv(68,GetDpiForWindow(hwnd),96);}SetWindowPos(hwnd,nullptr,p.x,p.y,w,h,SWP_NOZORDER|SWP_NOACTIVATE);}
void DeskWindow::RebuildTabs(){auto& z=Model();auto members=GroupMemberIds(owner.layout,z.group);bool show=!z.group.empty()&&members.size()>1&&!capsuleNow&&!z.collapsed;tabsPanel.Visibility(show?Visibility::Visible:Visibility::Collapsed);if(!show)return;tabsPanel.Children().Clear();
 for(size_t idx=0;idx<members.size();++idx){
  auto zit=std::find_if(owner.layout.zones.begin(),owner.layout.zones.end(),[&](auto const& o){return o.id==members[idx];});
  if(zit==owner.layout.zones.end())continue;
  bool active=zit->id==viewId;
  auto tab=Button();tab.Background(nullptr);tab.BorderThickness(Thickness{0});tab.Padding(Thickness{10,4,10,4});tab.CornerRadius(CornerRadius{6,6,6,6});
  TextBlock t;t.Text(zit->name);t.FontSize(12);t.TextTrimming(TextTrimming::CharacterEllipsis);t.MaxWidth(96);
  if(active){t.FontWeight(Windows::UI::Text::FontWeights::SemiBold());tab.Background(ThemeBrush(L"CardBackgroundFillColorDefault",Windows::UI::Color{255,60,60,60}));}
  tab.Content(t);
  auto captured=static_cast<int>(idx);
  tab.Click([this,captured](auto&&,auto&&){SwitchTab(captured);});
  tabsPanel.Children().Append(tab);
 }
 auto plus=Button();plus.Background(nullptr);plus.BorderThickness(Thickness{0});plus.Padding(Thickness{6,4,6,4});FontIcon pg;pg.FontFamily(FontFamily(L"Segoe Fluent Icons"));pg.Glyph(L"\uE710");pg.FontSize(12);plus.Content(pg);ToolTipService::SetToolTip(plus,box_value(i18n::Tr(L"在标签组中新增分区")));plus.Click([this](auto&&,auto&&){owner.AddToGroup(id);});tabsPanel.Children().Append(plus);}
void DeskWindow::SwitchTab(int index){auto& z=Model();auto members=GroupMemberIds(owner.layout,z.group);if(members.empty())return;index=std::clamp(index,0,static_cast<int>(members.size())-1);viewId=members[static_cast<size_t>(index)];z.groupTab=index;expandedStack.clear();Refresh();owner.Save();}
void DeskWindow::SetCapsule(bool on){auto& z=Model();z.capsule=on;capsuleNow=on;if(on){z.collapsed=false;if(hoverTimer)hoverTimer.Start();}else{if(hoverTimer)hoverTimer.Stop();pill.Visibility(Visibility::Collapsed);}Refresh();Place();}
void DeskWindow::ExpandCapsule(){if(!capsuleNow||dragging)return;capsuleNow=false;Refresh();Place();}
void DeskWindow::ShrinkCapsule(){if(capsuleNow||dragging)return;Capture();capsuleNow=true;Refresh();Place();}
std::vector<RECT> DeskWindow::Peers(){std::vector<RECT> list;for(auto& w:owner.windows)if(w.get()!=this&&IsWindow(w->hwnd)&&IsWindowVisible(w->hwnd)){RECT r{};GetWindowRect(w->hwnd,&r);list.push_back(r);}return list;}
void DeskWindow::DragUpdate(){if(!dragging)return;POINT p{};GetCursorPos(&p);int x=dragOrigin.left+p.x-dragStart.x,y=dragOrigin.top+p.y-dragStart.y,w=dragOrigin.right-dragOrigin.left,h=dragOrigin.bottom-dragOrigin.top;int threshold=MulDiv(8,GetDpiForWindow(hwnd),96);std::vector<int> xs,ys;auto peers=Peers();for(auto const& r:peers){int cx=r.left+(r.right-r.left)/2,cy=r.top+(r.bottom-r.top)/2;xs.push_back(r.left);xs.push_back(r.right-w);xs.push_back(r.left-w);xs.push_back(r.right);xs.push_back(cx-w/2);ys.push_back(r.top);ys.push_back(r.bottom-h);ys.push_back(r.top-h);ys.push_back(r.bottom);ys.push_back(cy-h/2);}MONITORINFO mi{sizeof(mi)};GetMonitorInfoW(MonitorFromWindow(hwnd,MONITOR_DEFAULTTONEAREST),&mi);xs.push_back(mi.rcWork.left);xs.push_back(mi.rcWork.right-w);ys.push_back(mi.rcWork.top);ys.push_back(mi.rcWork.bottom-h);x+=Snap(x,xs,threshold);y+=Snap(y,ys,threshold);SetWindowPos(hwnd,nullptr,x,y,0,0,SWP_NOSIZE|SWP_NOZORDER|SWP_NOACTIVATE);}
void DeskWindow::SnapResize(RECT& r,int edge){auto peers=Peers();if(peers.empty())return;int threshold=MulDiv(10,GetDpiForWindow(hwnd),96);bool left=edge==WMSZ_LEFT||edge==WMSZ_TOPLEFT||edge==WMSZ_BOTTOMLEFT,top=edge==WMSZ_TOP||edge==WMSZ_TOPLEFT||edge==WMSZ_TOPRIGHT;int w=r.right-r.left,best=threshold+1,target=w;for(auto const& p:peers){int pw=p.right-p.left,d=pw-w,ad=d<0?-d:d;if(ad<best){best=ad;target=pw;}}if(best<=threshold){if(left)r.left=r.right-target;else r.right=r.left+target;}int h=r.bottom-r.top;best=threshold+1;target=h;for(auto const& p:peers){int ph=p.bottom-p.top,d=ph-h,ad=d<0?-d:d;if(ad<best){best=ad;target=ph;}}if(best<=threshold){if(top)r.top=r.bottom-target;else r.bottom=r.top+target;}}
void DeskWindow::Show(){ShowWindow(hwnd,SW_SHOWNOACTIVATE);}
void DeskWindow::SetDesktop(bool enabled){Capture();bool was=desktop;if(enabled){desktop=shell::Attach(hwnd,owner.host);root.Background(ThemeBrush(L"ApplicationPageBackgroundThemeBrush",Windows::UI::Color{255,32,32,32}));Notify(desktop?i18n::Tr(L"实验性桌面宿主 · 添加入口不会移动原文件"):i18n::Tr(L"嵌入失败，已保留普通窗口模式"));}else{if(desktop)shell::Detach(hwnd);desktop=false;root.Background(nullptr);Notify(i18n::Tr(L"普通窗口模式 · 可在菜单中试验桌面嵌入"));}Place();if(desktop!=was){RECT r{};GetWindowRect(hwnd,&r);int width=r.right-r.left,height=r.bottom-r.top;SetWindowPos(hwnd,nullptr,0,0,width,height+1,SWP_NOMOVE|SWP_NOZORDER|SWP_NOACTIVATE);SetWindowPos(hwnd,nullptr,0,0,width,height,SWP_NOMOVE|SWP_NOZORDER|SWP_NOACTIVATE);}}
void DeskWindow::Pick(bool folder){if(!View().mappedFolder.empty()){Notify(i18n::Tr(L"映射分区为只读视图：请在资源管理器中修改文件夹后右键刷新。"));return;}for(auto const& path:shell::Pick(hwnd,folder))AddEntry(View(),path);Refresh();owner.Save();}
void DeskWindow::Menu(FrameworkElement const& target){auto& z=Model();auto& v=View();bool mapped=!v.mappedFolder.empty();MenuFlyout menu;
 menu.Items().Append(MenuItem(i18n::Tr(L"添加文件 / 应用"),[this,mapped]{if(mapped){Notify(i18n::Tr(L"映射分区为只读视图：请在资源管理器中修改文件夹后右键刷新。"));return;}Pick();}));
 menu.Items().Append(MenuItem(i18n::Tr(L"添加文件夹"),[this,mapped]{if(mapped){Notify(i18n::Tr(L"映射分区为只读视图：请在资源管理器中修改文件夹后右键刷新。"));return;}Pick(true);}));
 menu.Items().Append(MenuItem(mapped?i18n::Tr(L"取消文件夹映射"):i18n::Tr(L"映射文件夹…"),[this,mapped]{if(mapped){View().mappedFolder.clear();Refresh();owner.Save();Notify(i18n::Tr(L"已取消映射，恢复普通分区。"));return;}auto picked=shell::Pick(hwnd,true);if(picked.empty())return;View().mappedFolder=picked.front();SyncMapped(View());Refresh();owner.Save();Notify(i18n::Tr(L"已映射文件夹（只读视图）：修改请在资源管理器中完成，右键可刷新。"));}));
 menu.Items().Append(MenuItem(v.viewMode==L"list"?i18n::Tr(L"切换为图标视图"):i18n::Tr(L"切换为列表视图"),[this]{auto& m=View();m.viewMode=m.viewMode==L"list"?L"grid":L"list";Refresh();owner.Save();}));
 if(!mapped){MenuFlyoutSubItem sort;
  auto addKey=[&](wchar_t const* label,wchar_t const* value){sort.Items().Append(MenuItem(i18n::Tr(label),[this,value,label]{auto& m=View();m.sortKey=value;m.sortDescending=false;SortEntries(m,SortKeyFromString(value),false);Refresh();owner.Save();Notify(i18n::TrF(L"已按 {0} 排序",{std::wstring(i18n::Tr(label))}));}));};
  addKey(L"按名称",L"name");addKey(L"按类型",L"type");addKey(L"按修改日期",L"date");addKey(L"按大小",L"size");
  ToggleMenuFlyoutItem desc;desc.Text(i18n::Tr(L"降序"));desc.IsChecked(v.sortDescending);desc.Click([this](auto&&,auto&&){auto& m=View();m.sortDescending=!m.sortDescending;if(!m.sortKey.empty())SortEntries(m,SortKeyFromString(m.sortKey),m.sortDescending);Refresh();owner.Save();});
  sort.Items().Append(desc);sort.Text(i18n::Tr(L"排序"));menu.Items().Append(sort);}
 menu.Items().Append(MenuItem(i18n::TrF(L"图标大小：{0}（点击切换）",{std::wstring(i18n::Tr(v.tileSize==0?L"小":v.tileSize==1?L"中":L"大"))}),[this]{auto& m=View();m.tileSize=(m.tileSize+1)%3;Refresh();owner.Save();}));
 menu.Items().Append(MenuItem(i18n::TrF(L"文件名：{0}（点击切换）",{std::wstring(v.nameLines==0?i18n::Tr(L"隐藏"):v.nameLines==1?i18n::Tr(L"一行"):i18n::Tr(L"两行"))}),[this]{auto& m=View();m.nameLines=m.nameLines==0?2:m.nameLines-1;Refresh();owner.Save();}));
 menu.Items().Append(MenuItem(z.capsule?i18n::Tr(L"关闭胶囊模式"):i18n::Tr(L"胶囊模式（悬停展开）"),[this]{auto key=id;root.DispatcherQueue().TryEnqueue([this,key]{SetCapsule(!Model().capsule);Place();owner.Save();});}));
 if(z.group.empty()){MenuFlyoutSubItem merge;merge.Text(i18n::Tr(L"合并到标签组…"));for(auto const& o:owner.layout.zones){if(o.id==id)continue;merge.Items().Append(MenuItem(o.name,[this,tid=o.id]{auto key=id;root.DispatcherQueue().TryEnqueue([this,key,tid]{owner.MergeInto(key,tid);});}));}if(merge.Items().Size()>0)menu.Items().Append(merge);}
 else{MenuFlyoutSubItem join;join.Text(i18n::Tr(L"把其他分区并入此组…"));for(auto const& o:owner.layout.zones){if(o.group==z.group)continue;join.Items().Append(MenuItem(o.name,[this,tid=o.id]{auto key=id;root.DispatcherQueue().TryEnqueue([this,key,tid]{owner.MergeInto(key,tid);});}));}if(join.Items().Size()>0)menu.Items().Append(join);menu.Items().Append(MenuItem(i18n::TrF(L"把「{0}」移出标签组",{v.name}),[this]{auto key=viewId;root.DispatcherQueue().TryEnqueue([this,key]{owner.Ungroup(key);});}));}
 menu.Items().Append(MenuItem(i18n::Tr(L"新增分区"),[this]{owner.Add();}));
 menu.Items().Append(MenuItem(i18n::Tr(L"立即刷新"),[this]{if(!View().mappedFolder.empty())SyncMapped(View());Refresh();}));
 menu.Items().Append(MenuItem(owner.desktopMode?i18n::Tr(L"切换普通窗口"):i18n::Tr(L"试验桌面嵌入"),[this]{owner.ToggleDesktop();}));menu.Items().Append(MenuItem(i18n::Tr(L"设置"),[this]{owner.ShowSettings();}));menu.Items().Append(MenuItem(i18n::Tr(L"删除分区（保留原文件）"),[this]{auto key=viewId;root.DispatcherQueue().TryEnqueue([this,key]{owner.Remove(key);});}));menu.ShowAt(target);}
void DeskWindow::Refresh(){auto& z=Model();auto& v=View();if(z.group.empty())viewId=z.id;if(capsuleNow){barGrid.Visibility(Visibility::Collapsed);grid.Visibility(Visibility::Collapsed);listHost.Visibility(Visibility::Collapsed);status.Visibility(Visibility::Collapsed);tabsPanel.Visibility(Visibility::Collapsed);pill.Visibility(Visibility::Visible);pillName.Text(z.name);window.Title(L"GuoDesk · "+z.name);bool has=!z.entries.empty();pillIcon.Visibility(has?Visibility::Visible:Visibility::Collapsed);pillGlyph.Visibility(has?Visibility::Collapsed:Visibility::Visible);if(has)shell::LoadIcon(z.entries.front().path,pillIcon);return;}RebuildTabs();barGrid.Visibility(Visibility::Visible);status.Visibility(Visibility::Visible);title.Text(v.name);window.Title(L"GuoDesk · "+v.name);grid.Visibility(z.collapsed||v.viewMode!=L"grid"?Visibility::Collapsed:Visibility::Visible);listHost.Visibility(z.collapsed||v.viewMode!=L"list"?Visibility::Collapsed:Visibility::Visible);FontIcon chevronGlyph;chevronGlyph.FontFamily(FontFamily(L"Segoe Fluent Icons"));chevronGlyph.Glyph(z.collapsed?L"\uE70D":L"\uE70E");chevronGlyph.FontSize(16);chevron.Content(chevronGlyph);grid.Items().Clear();listPanel.Children().Clear();bool compact=owner.layout.settings.compact;bool mapped=!v.mappedFolder.empty();size_t const limit=500,total=v.entries.size();
 auto itemMenu=[this](std::wstring const& path,std::wstring const& key,bool isMapped,std::wstring stackId){MenuFlyout menu;menu.Items().Append(MenuItem(i18n::Tr(L"打开"),[this,path]{shell::Open(hwnd,path);}));menu.Items().Append(MenuItem(i18n::Tr(L"定位原文件"),[this,path]{shell::Reveal(hwnd,path);}));if(!isMapped){menu.Items().Append(MenuItem(i18n::Tr(L"重新定位文件"),[this,key]{auto picked=shell::Pick(hwnd);if(picked.empty())return;auto& entries=View().entries;auto duplicate=std::find_if(entries.begin(),entries.end(),[&](auto const& x){return x.id!=key&&PathKey(x.path)==PathKey(picked.front());});if(duplicate!=entries.end()){Notify(i18n::Tr(L"此目标已在当前分区中。 "));return;}for(auto& x:entries)if(x.id==key)x.path=picked.front();Refresh();owner.Save();}));menu.Items().Append(MenuItem(i18n::Tr(L"移除入口（保留原文件）"),[this,key]{std::erase_if(View().entries,[&](auto const& x){return x.id==key;});Refresh();owner.Save();}));if(stackId.empty()){MenuFlyoutSubItem into;into.Text(i18n::Tr(L"移入叠放"));for(auto const& s:View().stacks)into.Items().Append(MenuItem(s.name,[this,key,sid=s.id]{AssignStack(View(),key,sid);Refresh();owner.Save();}));into.Items().Append(MenuItem(i18n::Tr(L"新建叠放"),[this,key]{AssignStack(View(),key,CreateStack(View()));Refresh();owner.Save();}));menu.Items().Append(into);}else menu.Items().Append(MenuItem(i18n::Tr(L"移出叠放"),[this,key,stackId]{AssignStack(View(),key,L"");Refresh();owner.Save();}));}return menu;};
 std::map<std::wstring,size_t> firstIdx;for(size_t i=0;i<v.entries.size();++i)if(!v.entries[i].stack.empty())firstIdx.emplace(v.entries[i].stack,i);
 std::set<std::wstring> rendered;
 auto renderCollapse=[&](std::wstring const& sid){int tier=v.tileSize-(compact?1:0);tier=std::clamp(tier,0,2);static int const TW[3]={72,88,112},TH[3]={78,94,118};Border tile;tile.Width(TW[tier]);tile.Height(TH[tier]);tile.CornerRadius(CornerRadius{8,8,8,8});tile.Background(ThemeBrush(L"CardBackgroundFillColorSecondary",Windows::UI::Color{255,80,80,80}));tile.AllowDrop(!mapped);StackPanel c;c.VerticalAlignment(VerticalAlignment::Center);c.Spacing(4);FontIcon g;g.FontFamily(FontFamily(L"Segoe Fluent Icons"));g.Glyph(L"\uE70E");g.FontSize(20);TextBlock t;t.Text(i18n::Tr(L"收起叠放"));t.FontSize(12);t.TextAlignment(TextAlignment::Center);t.Foreground(ThemeBrush(L"TextFillColorSecondary",Windows::UI::Color{255,180,180,180}));c.Children().Append(g);c.Children().Append(t);tile.Child(c);tile.DoubleTapped([this,sid](auto&&,auto&&){expandedStack.clear();Refresh();});tile.DragOver([mapped](auto&&,DragEventArgs const& a){a.AcceptedOperation(mapped?DataPackageOperation::None:(a.DataView().Contains(StandardDataFormats::StorageItems())?DataPackageOperation::Link:DataPackageOperation::Move));a.Handled(true);});if(!mapped)tile.Drop([this,sid](auto&&,DragEventArgs const& a){a.Handled(true);Drop(a,0,sid);});grid.Items().Append(tile);};
 auto renderPile=[&](std::wstring const& sid,size_t at){
  auto first=std::find_if(v.entries.begin(),v.entries.end(),[&](auto const& x){return x.stack==sid;});auto path=first->path;int count=StackCount(v,sid);bool exists=GetFileAttributesW(path.c_str())!=INVALID_FILE_ATTRIBUTES;
  int tier=v.tileSize-(compact?1:0);tier=std::clamp(tier,0,2);static int const TW[3]={72,88,112},TH[3]={78,94,118},TI[3]={32,40,56};
  Grid wrap;wrap.Width(TW[tier]+8);wrap.Height(TH[tier]+8);
  Border back;back.Width(TW[tier]);back.Height(TH[tier]);back.CornerRadius(CornerRadius{8,8,8,8});back.Background(ThemeBrush(L"CardBackgroundFillColorSecondary",Windows::UI::Color{255,80,80,80}));back.Opacity(0.6);back.HorizontalAlignment(HorizontalAlignment::Right);back.VerticalAlignment(VerticalAlignment::Bottom);
  Border front;front.Width(TW[tier]);front.Height(TH[tier]);front.Padding(Thickness{4,4,4,4});front.CornerRadius(CornerRadius{8,8,8,8});front.Background(ThemeBrush(L"CardBackgroundFillColorDefault",Windows::UI::Color{255,60,60,60}));front.HorizontalAlignment(HorizontalAlignment::Left);front.VerticalAlignment(VerticalAlignment::Top);front.AllowDrop(!mapped);ToolTipService::SetToolTip(front,box_value(i18n::TrF(L"叠放 · {0} 项（双击展开）",{std::to_wstring(count)})));
  StackPanel content;content.Spacing(5);Image icon;icon.Width(TI[tier]);icon.Height(TI[tier]);content.Children().Append(icon);shell::LoadIcon(path,icon);TextBlock label;label.Text((exists?L"":L"⚠ ")+shell::Name(path));label.FontSize(12);label.TextAlignment(TextAlignment::Center);label.Foreground(ThemeBrush(L"TextFillColorSecondary",Windows::UI::Color{255,180,180,180}));if(v.nameLines==0)label.Visibility(Visibility::Collapsed);else if(v.nameLines==1){label.TextWrapping(TextWrapping::NoWrap);label.TextTrimming(TextTrimming::CharacterEllipsis);label.MaxHeight(18);}else{label.TextWrapping(TextWrapping::Wrap);label.MaxHeight(36);}content.Children().Append(label);front.Child(content);
  Border badge;badge.Width(20);badge.Height(20);badge.CornerRadius(CornerRadius{10,10,10,10});badge.Background(SolidColorBrush(Windows::UI::Color{255,0,120,212}));badge.HorizontalAlignment(HorizontalAlignment::Right);badge.VerticalAlignment(VerticalAlignment::Top);badge.Margin(Thickness{0,0,3,0});TextBlock cnt;cnt.Text(std::to_wstring(count));cnt.FontSize(11);cnt.Foreground(SolidColorBrush(Windows::UI::Colors::White()));cnt.HorizontalAlignment(HorizontalAlignment::Center);cnt.VerticalAlignment(VerticalAlignment::Center);badge.Child(cnt);
  wrap.Children().Append(back);wrap.Children().Append(front);wrap.Children().Append(badge);
  MenuFlyout pmenu;pmenu.Items().Append(MenuItem(i18n::Tr(L"展开叠放"),[this,sid]{expandedStack=sid;Refresh();}));
  pmenu.Items().Append(MenuItem(i18n::Tr(L"重命名叠放…"),[this,sid]{TextBox box;for(auto const& s:View().stacks)if(s.id==sid)box.Text(s.name);ContentDialog dlg;dlg.Title(box_value(i18n::Tr(L"重命名叠放")));dlg.PrimaryButtonText(i18n::Tr(L"保存"));dlg.CloseButtonText(i18n::Tr(L"取消"));dlg.DefaultButton(ContentDialogButton::Primary);StackPanel p;p.Spacing(8);p.MaxWidth(300);p.Children().Append(box);dlg.Content(p);try{dlg.XamlRoot(root.XamlRoot());}catch(...){return;}auto op=dlg.ShowAsync();op.Completed([this,sid,box](auto&&async,auto&&){if(async.GetResults()!=ContentDialogResult::Primary)return;auto t=std::wstring(box.Text());size_t a=t.find_first_not_of(L" \t");if(a==std::wstring::npos)return;t=t.substr(a,t.find_last_not_of(L" \t")-a+1);for(auto& s:View().stacks)if(s.id==sid)s.name=t;Refresh();owner.Save();});}));
  pmenu.Items().Append(MenuItem(i18n::Tr(L"解散叠放"),[this,sid]{DissolveStack(View(),sid);Refresh();owner.Save();}));
  front.ContextFlyout(pmenu);
  front.DoubleTapped([this,sid](auto&&,auto&&){expandedStack=sid;Refresh();});
  if(!mapped)front.DragStarting([this,sid,vkey=v.id](auto&&,DragStartingEventArgs const& a){a.Data().SetText(L"guodesk-stack:"+vkey+L"|"+sid);a.Data().RequestedOperation(DataPackageOperation::Move);});
  front.DragOver([mapped](auto&&,DragEventArgs const& a){a.AcceptedOperation(mapped?DataPackageOperation::None:(a.DataView().Contains(StandardDataFormats::StorageItems())?DataPackageOperation::Link:DataPackageOperation::Move));a.Handled(true);});
  if(!mapped)front.Drop([this,at,sid](auto&&,DragEventArgs const& a){a.Handled(true);Drop(a,at,sid);});
  grid.Items().Append(wrap);};
 for(size_t i=0;i<std::min(total,limit);++i){auto const& e=v.entries[i];auto path=e.path,key=e.id;auto index=i;bool exists=GetFileAttributesW(path.c_str())!=INVALID_FILE_ATTRIBUTES;auto menu=itemMenu(path,key,mapped,e.stack);
  if(v.viewMode!=L"list"&&!e.stack.empty()&&expandedStack!=e.stack){if(!rendered.count(e.stack)){renderPile(e.stack,i);rendered.insert(e.stack);}continue;}
  if(v.viewMode!=L"list"&&!e.stack.empty()&&expandedStack==e.stack&&firstIdx[e.stack]==i)renderCollapse(e.stack);
  if(v.viewMode==L"list"){
   Border row;row.Height(30);row.CornerRadius(CornerRadius{4,4,4,4});row.Padding(Thickness{8,3,8,3});row.Background(ThemeBrush(L"CardBackgroundFillColorDefault",Windows::UI::Color{255,60,60,60}));ToolTipService::SetToolTip(row,box_value(path));row.PointerEntered([weak=make_weak(row),this](auto&&,auto&&){if(auto r=weak.get())r.Background(ThemeBrush(L"CardBackgroundFillColorSecondary",Windows::UI::Color{255,80,80,80}));});row.PointerExited([weak=make_weak(row),this](auto&&,auto&&){if(auto r=weak.get())r.Background(ThemeBrush(L"CardBackgroundFillColorDefault",Windows::UI::Color{255,60,60,60}));});
   Grid line;ColumnDefinition ci,cn,cp;ci.Width(GridLength{0,GridUnitType::Auto});cn.Width(GridLength{2,GridUnitType::Star});cp.Width(GridLength{3,GridUnitType::Star});line.ColumnDefinitions().Append(ci);line.ColumnDefinitions().Append(cn);line.ColumnDefinitions().Append(cp);
   Image icon;icon.Width(18);icon.Height(18);line.Children().Append(icon);shell::LoadIcon(path,icon);
   TextBlock name;name.Text((exists?L"":L"⚠ ")+shell::Name(path));name.FontSize(12);name.VerticalAlignment(VerticalAlignment::Center);name.Margin(Thickness{8,0,8,0});name.TextTrimming(TextTrimming::CharacterEllipsis);name.Foreground(ThemeBrush(L"TextFillColorSecondary",Windows::UI::Color{255,180,180,180}));Grid::SetColumn(name,1);line.Children().Append(name);
   TextBlock where;where.Text(path);where.FontSize(11);where.VerticalAlignment(VerticalAlignment::Center);where.TextTrimming(TextTrimming::CharacterEllipsis);where.Foreground(ThemeBrush(L"TextFillColorSecondary",Windows::UI::Color{255,160,160,160}));Grid::SetColumn(where,2);line.Children().Append(where);
   row.Child(line);row.DoubleTapped([this,path](auto&&,auto&&){try{shell::Open(hwnd,path);}catch(...){Notify(i18n::Tr(L"无法打开目标，请右键重新定位。 "));}});row.ContextFlyout(menu);listPanel.Children().Append(row);
  }else{
   int tier=v.tileSize-(compact?1:0);tier=std::clamp(tier,0,2);static int const TW[3]={72,88,112},TH[3]={78,94,118},TI[3]={32,40,56};
   Border tile;tile.Width(TW[tier]);tile.Height(TH[tier]);tile.Padding(Thickness{4,4,4,4});tile.CornerRadius(CornerRadius{8,8,8,8});tile.Background(ThemeBrush(L"CardBackgroundFillColorDefault",Windows::UI::Color{255,60,60,60}));tile.CanDrag(!mapped);tile.AllowDrop(true);ToolTipService::SetToolTip(tile,box_value(path));tile.PointerEntered([weak=make_weak(tile),this](auto&&,auto&&){if(auto t=weak.get())t.Background(ThemeBrush(L"CardBackgroundFillColorSecondary",Windows::UI::Color{255,80,80,80}));});tile.PointerExited([weak=make_weak(tile),this](auto&&,auto&&){if(auto t=weak.get())t.Background(ThemeBrush(L"CardBackgroundFillColorDefault",Windows::UI::Color{255,60,60,60}));});StackPanel content;content.Spacing(5);Image icon;icon.Width(TI[tier]);icon.Height(TI[tier]);content.Children().Append(icon);shell::LoadIcon(path,icon);TextBlock label;label.Text((exists?L"":L"⚠ ")+shell::Name(path));label.FontSize(12);label.TextAlignment(TextAlignment::Center);label.Foreground(ThemeBrush(L"TextFillColorSecondary",Windows::UI::Color{255,180,180,180}));if(v.nameLines==0)label.Visibility(Visibility::Collapsed);else if(v.nameLines==1){label.TextWrapping(TextWrapping::NoWrap);label.TextTrimming(TextTrimming::CharacterEllipsis);label.MaxHeight(18);}else{label.TextWrapping(TextWrapping::Wrap);label.MaxHeight(36);}content.Children().Append(label);tile.Child(content);
   tile.DoubleTapped([this,path](auto&&,auto&&){try{shell::Open(hwnd,path);}catch(...){Notify(i18n::Tr(L"无法打开目标，请右键重新定位。 "));}});
   if(!mapped)tile.DragStarting([key](auto&&,DragStartingEventArgs const& a){a.Data().SetText(L"guodesk-entry:"+key);a.Data().RequestedOperation(DataPackageOperation::Move);});
   tile.DragOver([mapped](auto&&,DragEventArgs const& a){a.AcceptedOperation(mapped?DataPackageOperation::None:(a.DataView().Contains(StandardDataFormats::StorageItems())?DataPackageOperation::Link:DataPackageOperation::Move));a.Handled(true);});
   if(!mapped)tile.Drop([this,index,sid=e.stack](auto&&,DragEventArgs const& a){a.Handled(true);Drop(a,index,sid);});
   tile.ContextFlyout(menu);grid.Items().Append(tile);}
 }
 if(mapped){std::wstring head=v.entries.empty()?i18n::Tr(L"映射文件夹为空或不可访问"):i18n::TrF(L"映射视图（只读）· {0} · 共 {1} 项",{shell::Name(v.mappedFolder),std::to_wstring(total)});if(total>limit)head+=i18n::TrF(L" · 已显示前 {0} 项",{std::to_wstring(limit)});Notify(head+i18n::Tr(L" · 双击打开 · 右键更多"));}
 else Notify(v.entries.empty()?i18n::Tr(L"拖入文件、文件夹或应用快捷方式 · 原文件保持原位"):i18n::Tr(L"双击打开 · 右键管理 · 拖拽排序"));}
fire_and_forget DeskWindow::Drop(DragEventArgs a,size_t position,std::wstring stackId){auto deferral=a.GetDeferral();auto weak=winrt::make_weak(root);auto key=viewId;auto* controller=&owner;try{auto data=a.DataView();auto zoneOf=[&](std::wstring const& kid)->Zone*{auto it=std::find_if(controller->layout.zones.begin(),controller->layout.zones.end(),[&](auto const& z){return z.id==kid;});return it==controller->layout.zones.end()?nullptr:&*it;};if(data.Contains(StandardDataFormats::StorageItems())){auto items=co_await data.GetStorageItemsAsync();if(auto zt=zoneOf(key))for(auto const& item:items)if(!item.Path().empty()){auto pk=PathKey(std::wstring(item.Path()));if(AddEntry(*zt,std::wstring(item.Path()))&&!stackId.empty())for(auto& e:zt->entries)if(PathKey(e.path)==pk)e.stack=stackId;}}else if(data.Contains(StandardDataFormats::Text())){std::wstring text(co_await data.GetTextAsync());if(text.starts_with(L"guodesk-entry:")){auto eid=text.substr(14);controller->MoveEntry(eid,key,position);if(!stackId.empty())if(auto zt=zoneOf(key))AssignStack(*zt,eid,stackId);}else if(text.starts_with(L"guodesk-stack:")){auto rest=text.substr(14);auto bar=rest.find(L'|');if(bar!=std::wstring::npos)MoveStack(controller->layout,rest.substr(bar+1),rest.substr(0,bar),key);}}if(auto live=weak.get())live.DispatcherQueue().TryEnqueue([controller]{controller->Refresh();controller->Save();});}catch(...){if(auto live=weak.get())MessageBoxW(nullptr,i18n::Tr(L"无法添加拖入项目。").c_str(),L"GuoDesk",MB_OK);}deferral.Complete();}
LRESULT CALLBACK DeskWindow::Subclass(HWND h,UINT msg,WPARAM w,LPARAM l,UINT_PTR,DWORD_PTR data){auto* self=reinterpret_cast<DeskWindow*>(data);if(msg==WM_NCCALCSIZE&&w&&self->desktop)return 0;if(msg==WM_SIZING&&l){self->SnapResize(*reinterpret_cast<RECT*>(l),static_cast<int>(w));return TRUE;}if(msg==WM_EXITSIZEMOVE){self->Capture();self->owner.Save();}if(msg==WM_DISPLAYCHANGE)self->Place();if(msg==WM_DPICHANGED){auto* rect=reinterpret_cast<RECT*>(l);SetWindowPos(h,nullptr,rect->left,rect->top,rect->right-rect->left,rect->bottom-rect->top,SWP_NOZORDER|SWP_NOACTIVATE);}return DefSubclassProc(h,msg,w,l);}
}

namespace guodesk {
static std::wstring StampOf(std::wstring const& folder){WIN32_FILE_ATTRIBUTE_DATA fa{};if(!GetFileAttributesExW(folder.c_str(),GetFileExInfoStandard,&fa))return{};return std::to_wstring(fa.ftLastWriteTime.dwHighDateTime)+L"-"+std::to_wstring(fa.ftLastWriteTime.dwLowDateTime);}
Controller::Controller(std::filesystem::path root):store(std::move(root)){mutex=CreateMutexW(nullptr,FALSE,L"Local\\GuoDesk.Prototype");if(GetLastError()==ERROR_ALREADY_EXISTS){CloseHandle(mutex);mutex=nullptr;HWND prev=FindWindowW(L"GuoDesk.Controller",nullptr);if(prev)PostMessageW(prev,WM_APP+2,0,0);throw already_running{};}}
Controller::~Controller(){if(messageWindow){UnregisterHotKey(messageWindow,1);KillTimer(messageWindow,1);Shell_NotifyIconW(NIM_DELETE,&tray);DestroyWindow(messageWindow);}note.reset();todo.reset();clockW.reset();guide.reset();tidy.reset();settings.reset();windows.clear();if(mutex)CloseHandle(mutex);}
void Controller::AddTray(){tray={sizeof(tray)};tray.hWnd=messageWindow;tray.uID=1;tray.uFlags=NIF_ICON|NIF_MESSAGE|NIF_TIP;tray.uCallbackMessage=WM_APP+1;tray.hIcon=LoadIconW(GetModuleHandleW(nullptr),MAKEINTRESOURCEW(101));if(!tray.hIcon)tray.hIcon=LoadIconW(nullptr,IDI_APPLICATION);wcscpy_s(tray.szTip,i18n::Tr(L"GuoDesk · 桌面分区").c_str());Shell_NotifyIconW(NIM_ADD,&tray);}
void Controller::Start(){std::wstring warning;layout=store.Load(warning);i18n::SetLanguage(layout.settings.language);for(auto& z:layout.zones)if(!z.mappedFolder.empty())SyncMapped(z);for(auto& z:layout.zones){RECT r{z.x,z.y,z.x+z.width,z.y+z.height};Reanchor(r,z.mon,z.mx,z.my);z.x=r.left;z.y=r.top;}{auto& wg=layout.widgets;RECT rn{wg.noteX,wg.noteY,wg.noteX+wg.noteW,wg.noteY+wg.noteH};Reanchor(rn,wg.noteMon,wg.noteMX,wg.noteMY);wg.noteX=rn.left;wg.noteY=rn.top;RECT rt{wg.todoX,wg.todoY,wg.todoX+wg.todoW,wg.todoY+wg.todoH};Reanchor(rt,wg.todoMon,wg.todoMX,wg.todoMY);wg.todoX=rt.left;wg.todoY=rt.top;RECT rc{wg.clockX,wg.clockY,wg.clockX+wg.clockW,wg.clockY+wg.clockH};Reanchor(rc,wg.clockMon,wg.clockMX,wg.clockMY);wg.clockX=rc.left;wg.clockY=rc.top;RECT rm{wg.musicX,wg.musicY,wg.musicX+wg.musicW,wg.musicY+wg.musicH};Reanchor(rm,wg.musicMon,wg.musicMX,wg.musicMY);wg.musicX=rm.left;wg.musicY=rm.top;RECT rw{wg.weatherX,wg.weatherY,wg.weatherX+wg.weatherW,wg.weatherY+wg.weatherH};Reanchor(rw,wg.weatherMon,wg.weatherMX,wg.weatherMY);wg.weatherX=rw.left;wg.weatherY=rw.top;RECT rs{wg.searchX,wg.searchY,wg.searchX+560,wg.searchY+440};Reanchor(rs,wg.searchMon,wg.searchMX,wg.searchMY);wg.searchX=rs.left;wg.searchY=rs.top;}WNDCLASSW cls{};cls.lpfnWndProc=MessageProc;cls.hInstance=GetModuleHandleW(nullptr);cls.lpszClassName=L"GuoDesk.Controller";RegisterClassW(&cls);messageWindow=CreateWindowExW(WS_EX_TOOLWINDOW,cls.lpszClassName,L"GuoDesk Controller",WS_POPUP,0,0,0,0,nullptr,nullptr,cls.hInstance,this);taskbarCreated=RegisterWindowMessageW(L"TaskbarCreated");AddTray();for(auto const& z:layout.zones){if(!z.group.empty()&&GroupMemberIds(layout,z.group).front()!=z.id)continue;windows.push_back(std::make_unique<DeskWindow>(*this,z.id));if(!z.mappedFolder.empty()){auto stamp=StampOf(z.mappedFolder);if(!stamp.empty())mappedStamp[PathKey(z.mappedFolder)]=stamp;}}if(!ApplyHotkey()&&!windows.empty())windows.front()->Notify(i18n::Tr(L"全局热键注册失败，可能已被其他程序占用。"));SetTimer(messageWindow,1,2000,nullptr);if(layout.widgets.noteVisible)note=std::make_unique<NoteWindow>(*this);if(layout.widgets.todoVisible)todo=std::make_unique<TodoWindow>(*this);if(layout.widgets.clockVisible)clockW=std::make_unique<ClockWindow>(*this);if(layout.widgets.musicVisible)music=std::make_unique<MusicWindow>(*this);if(layout.widgets.weatherVisible)weather=std::make_unique<WeatherWindow>(*this);Save();if(!layout.settings.guideDone)ShowGuide();if(!layout.settings.guideDone)ShowGuide();if(!warning.empty())MessageBoxW(nullptr,warning.c_str(),i18n::Tr(L"GuoDesk 配置恢复").c_str(),MB_OK|MB_ICONINFORMATION);}
void Controller::Save(){try{store.Save(layout);}catch(...){for(auto& w:windows)w->Notify(i18n::Tr(L"保存失败：请检查本地数据目录权限和剩余空间。 "));}}
void Controller::ImportLayout(Layout&& next){tidy.reset();note.reset();todo.reset();clockW.reset();music.reset();weather.reset();try{store.Save(next);}catch(...){for(auto& w:windows)w->Notify(i18n::Tr(L"保存失败：请检查本地数据目录权限和剩余空间。 "));return;}layout=std::move(next);i18n::SetLanguage(layout.settings.language);windows.clear();mappedStamp.clear();for(auto& z:layout.zones)if(!z.mappedFolder.empty())SyncMapped(z);for(auto& z:layout.zones){RECT r{z.x,z.y,z.x+z.width,z.y+z.height};Reanchor(r,z.mon,z.mx,z.my);z.x=r.left;z.y=r.top;}{auto& wg=layout.widgets;RECT rn{wg.noteX,wg.noteY,wg.noteX+wg.noteW,wg.noteY+wg.noteH};Reanchor(rn,wg.noteMon,wg.noteMX,wg.noteMY);wg.noteX=rn.left;wg.noteY=rn.top;RECT rt{wg.todoX,wg.todoY,wg.todoX+wg.todoW,wg.todoY+wg.todoH};Reanchor(rt,wg.todoMon,wg.todoMX,wg.todoMY);wg.todoX=rt.left;wg.todoY=rt.top;RECT rc{wg.clockX,wg.clockY,wg.clockX+wg.clockW,wg.clockY+wg.clockH};Reanchor(rc,wg.clockMon,wg.clockMX,wg.clockMY);wg.clockX=rc.left;wg.clockY=rc.top;RECT rm{wg.musicX,wg.musicY,wg.musicX+wg.musicW,wg.musicY+wg.musicH};Reanchor(rm,wg.musicMon,wg.musicMX,wg.musicMY);wg.musicX=rm.left;wg.musicY=rm.top;RECT rw{wg.weatherX,wg.weatherY,wg.weatherX+wg.weatherW,wg.weatherY+wg.weatherH};Reanchor(rw,wg.weatherMon,wg.weatherMX,wg.weatherMY);wg.weatherX=rw.left;wg.weatherY=rw.top;RECT rs{wg.searchX,wg.searchY,wg.searchX+560,wg.searchY+440};Reanchor(rs,wg.searchMon,wg.searchMX,wg.searchMY);wg.searchX=rs.left;wg.searchY=rs.top;}for(auto const& z:layout.zones){if(!z.group.empty()&&GroupMemberIds(layout,z.group).front()!=z.id)continue;windows.push_back(std::make_unique<DeskWindow>(*this,z.id));if(!z.mappedFolder.empty()){auto stamp=StampOf(z.mappedFolder);if(!stamp.empty())mappedStamp[PathKey(z.mappedFolder)]=stamp;}}if(desktopMode)for(auto& w:windows)w->SetDesktop(true);if(layout.widgets.noteVisible)note=std::make_unique<NoteWindow>(*this);if(layout.widgets.todoVisible)todo=std::make_unique<TodoWindow>(*this);if(layout.widgets.clockVisible)clockW=std::make_unique<ClockWindow>(*this);if(layout.widgets.musicVisible)music=std::make_unique<MusicWindow>(*this);if(layout.widgets.weatherVisible)weather=std::make_unique<WeatherWindow>(*this);ApplySettings();if(!windows.empty())windows.front()->Notify(i18n::Tr(L"导入完成，界面已按新配置重建。"));}
void Controller::Add(){Zone zone;zone.id=NewId();zone.name=i18n::Tr(L"新分区");zone.x+=static_cast<int>(layout.zones.size())*30;zone.y+=static_cast<int>(layout.zones.size())*30;auto key=zone.id;layout.zones.push_back(std::move(zone));windows.push_back(std::make_unique<DeskWindow>(*this,key));if(desktopMode)windows.back()->SetDesktop(true);Save();}
void Controller::SyncWindows(){std::vector<std::wstring> keep;for(auto const& z:layout.zones){if(!z.group.empty()&&GroupMemberIds(layout,z.group).front()!=z.id)continue;keep.push_back(z.id);}for(auto it=windows.begin();it!=windows.end();){if(std::find(keep.begin(),keep.end(),(*it)->id)==keep.end()){it=windows.erase(it);}else ++it;}for(auto const& kid:keep){bool has=false;for(auto const& w:windows)if(w->id==kid)has=true;if(!has){windows.push_back(std::make_unique<DeskWindow>(*this,kid));if(desktopMode)windows.back()->SetDesktop(true);}}}
void Controller::MergeInto(std::wstring const& selfId,std::wstring const& otherId){auto a=std::find_if(layout.zones.begin(),layout.zones.end(),[&](auto const& z){return z.id==selfId;});auto t=std::find_if(layout.zones.begin(),layout.zones.end(),[&](auto const& z){return z.id==otherId;});if(a==layout.zones.end()||t==layout.zones.end()||a==t)return;std::wstring gid;if(!t->group.empty()&&t->group!=a->group){gid=t->group;a->group=gid;}else{gid=a->group.empty()?NewId():a->group;a->group=gid;t->group=gid;}auto members=GroupMemberIds(layout,gid);auto tabIndex=std::find(members.begin(),members.end(),a->id);if(tabIndex!=members.end())a->groupTab=static_cast<int>(tabIndex-members.begin());for(auto& z:layout.zones)if(z.group==gid)z.groupTab=std::clamp(z.groupTab,0,static_cast<int>(members.size())-1);SyncWindows();Save();}
void Controller::Ungroup(std::wstring const& zoneId){auto it=std::find_if(layout.zones.begin(),layout.zones.end(),[&](auto const& z){return z.id==zoneId;});if(it==layout.zones.end()||it->group.empty())return;auto gid=it->group;it->group.clear();it->groupTab=0;if(GroupMemberIds(layout,gid).size()<=1)for(auto& z:layout.zones)if(z.group==gid){z.group.clear();z.groupTab=0;}SyncWindows();Save();}
void Controller::AddToGroup(std::wstring const& anchorId){auto a=std::find_if(layout.zones.begin(),layout.zones.end(),[&](auto const& z){return z.id==anchorId;});if(a==layout.zones.end())return;Zone nz;nz.id=NewId();nz.name=i18n::Tr(L"新分区");if(a->group.empty()){a->group=NewId();}nz.group=a->group;nz.x=a->x;nz.y=a->y;nz.width=a->width;nz.height=a->height;nz.mon=a->mon;nz.mx=a->mx;nz.my=a->my;nz.collapsed=a->collapsed;layout.zones.push_back(std::move(nz));auto members=GroupMemberIds(layout,a->group);for(auto& z:layout.zones)if(z.group==a->group)z.groupTab=std::clamp(z.groupTab,0,static_cast<int>(members.size())-1);Save();}
void Controller::Remove(std::wstring const& key){auto it=std::find_if(layout.zones.begin(),layout.zones.end(),[&](auto const& z){return z.id==key;});if(it==layout.zones.end())return;auto gid=it->group;layout.zones.erase(it);if(!gid.empty()&&GroupMemberIds(layout,gid).size()==1)for(auto& z:layout.zones)if(z.group==gid){z.group.clear();z.groupTab=0;}SyncWindows();Save();}
void Controller::Refresh(){for(auto& w:windows)w->Refresh();}
void Controller::Show(){for(auto& w:windows)w->Show();if(windows.empty())Add();}
void Controller::HideAll(){for(auto& w:windows)if(IsWindowVisible(w->hwnd))ShowWindow(w->hwnd,SW_HIDE);}
void Controller::ToggleAll(){bool any=false;for(auto& w:windows)if(IsWindowVisible(w->hwnd)){any=true;break;}if(any)HideAll();else Show();}
bool Controller::ApplyHotkey(){if(messageWindow){UnregisterHotKey(messageWindow,1);UnregisterHotKey(messageWindow,2);}Hotkey hk;auto const& text=layout.settings.hotkey;if(!text.empty()&&ParseHotkey(text,hk))RegisterHotKey(messageWindow,1,hk.mods|MOD_NOREPEAT,hk.vk);Hotkey hs;auto const& stext=layout.settings.hotkeySearch;if(!stext.empty()&&ParseHotkey(stext,hs))return RegisterHotKey(messageWindow,2,hs.mods|MOD_NOREPEAT,hs.vk)!=0;return true;}
void Controller::Quit(){if(quitting)return;quitting=true;for(auto& w:windows)w->Capture();Save();Shell_NotifyIconW(NIM_DELETE,&tray);Application::Current().Exit();}
void Controller::ToggleDesktop(){desktopMode=!desktopMode;host=shell::DesktopHost();for(auto& w:windows)w->SetDesktop(desktopMode);}
void Controller::ShowSettings(){if(!settings)settings=std::make_unique<SettingsWindow>(*this);settings->Apply();settings->Show();}
void Controller::CloseSettings(){settings.reset();}
void Controller::ShowTidy(){if(!tidy)tidy=std::make_unique<TidyWindow>(*this);tidy->Show();}
void Controller::CloseTidy(){tidy.reset();}
void Controller::ShowNote(){layout.widgets.noteVisible=true;if(!note)note=std::make_unique<NoteWindow>(*this);note->Show();Save();}
void Controller::CloseNote(){if(layout.widgets.noteVisible){layout.widgets.noteVisible=false;Save();}note.reset();}
void Controller::ShowTodo(){layout.widgets.todoVisible=true;if(!todo)todo=std::make_unique<TodoWindow>(*this);todo->Show();Save();}
void Controller::CloseTodo(){if(layout.widgets.todoVisible){layout.widgets.todoVisible=false;Save();}todo.reset();}
void Controller::ShowClock(){layout.widgets.clockVisible=true;if(!clockW)clockW=std::make_unique<ClockWindow>(*this);clockW->Show();Save();}
void Controller::CloseClock(){if(layout.widgets.clockVisible){layout.widgets.clockVisible=false;Save();}clockW.reset();}
void Controller::ShowGuide(){if(!guide)guide=std::make_unique<GuideWindow>(*this);guide->Show();}
void Controller::CloseGuide(){guide.reset();}
void Controller::ShowMusic(){layout.widgets.musicVisible=true;if(!music)music=std::make_unique<MusicWindow>(*this);music->Show();Save();}
void Controller::CloseMusic(){if(layout.widgets.musicVisible){layout.widgets.musicVisible=false;Save();}music.reset();}
void Controller::ShowSearch(){if(!search)search=std::make_unique<SearchWindow>(*this);search->Show();}
void Controller::CloseSearch(){search.reset();}
void Controller::ShowWeather(){layout.widgets.weatherVisible=true;if(!weather)weather=std::make_unique<WeatherWindow>(*this);weather->Show();Save();}
void Controller::CloseWeather(){if(layout.widgets.weatherVisible){layout.widgets.weatherVisible=false;Save();}weather.reset();}
void Controller::CheckReminders(){bool save=false;for(auto& t:layout.widgets.todos){if(t.done||t.reminded||!DueReached(t.due))continue;t.reminded=true;save=true;std::wstring text=t.text;if(text.size()>100)text=text.substr(0,100)+L"…";NOTIFYICONDATAW nif{sizeof(nif)};nif.hWnd=messageWindow;nif.uID=1;nif.uFlags=NIF_INFO;nif.dwInfoFlags=NIIF_INFO;wcscpy_s(nif.szInfoTitle,i18n::Tr(L"待办到期提醒").c_str());wcscpy_s(nif.szInfo,i18n::TrF(L"「{0}」已到截止日期",{text}).c_str());Shell_NotifyIconW(NIM_MODIFY,&nif);}if(save)Save();}
void Controller::ApplySettings(){for(auto& w:windows)w->ApplySettings();}
void Controller::MoveEntry(std::wstring const& key,std::wstring const& target,size_t index){auto to=std::find_if(layout.zones.begin(),layout.zones.end(),[&](auto const& z){return z.id==target;});if(to==layout.zones.end())return;for(auto& from:layout.zones){auto entry=std::find_if(from.entries.begin(),from.entries.end(),[&](auto const& e){return e.id==key;});if(entry==from.entries.end())continue;if(&from!=&*to)for(auto const& existing:to->entries)if(PathKey(existing.path)==PathKey(entry->path))return;auto value=*entry;if(&from!=&*to)value.stack.clear();auto old=static_cast<size_t>(entry-from.entries.begin());from.entries.erase(entry);if(&from==&*to && index>old)--index;index=std::min(index,to->entries.size());to->entries.insert(to->entries.begin()+index,std::move(value));return;}}
LRESULT CALLBACK Controller::MessageProc(HWND h,UINT msg,WPARAM w,LPARAM l){auto* self=reinterpret_cast<Controller*>(GetWindowLongPtrW(h,GWLP_USERDATA));if(msg==WM_NCCREATE){self=static_cast<Controller*>(reinterpret_cast<CREATESTRUCTW*>(l)->lpCreateParams);SetWindowLongPtrW(h,GWLP_USERDATA,reinterpret_cast<LONG_PTR>(self));}if(!self)return DefWindowProcW(h,msg,w,l);try{if(msg==self->taskbarCreated&&self->taskbarCreated){self->AddTray();if(self->desktopMode){self->host=shell::DesktopHost();for(auto& item:self->windows)if(IsWindow(item->hwnd))item->SetDesktop(true);}}if(msg==WM_TIMER){if(self->desktopMode){auto host=shell::DesktopHost();if(host&&host!=self->host){self->host=host;for(auto& item:self->windows)if(IsWindow(item->hwnd))item->SetDesktop(true);}}
 for(auto& z:self->layout.zones){if(z.mappedFolder.empty())continue;auto stamp=StampOf(z.mappedFolder);if(stamp.empty())continue;auto key=PathKey(z.mappedFolder);auto it=self->mappedStamp.find(key);if(it==self->mappedStamp.end()){self->mappedStamp[key]=stamp;continue;}if(it->second!=stamp){it->second=stamp;SyncMapped(z);for(auto& w:self->windows)if(w->id==z.id||w->viewId==z.id)w->Refresh();}}self->CheckReminders();}if(msg==WM_APP+2){self->Show();if(!self->windows.empty())SetForegroundWindow(self->windows.front()->hwnd);return 0;}if(msg==WM_HOTKEY&&w==1){self->ToggleAll();return 0;}if(msg==WM_HOTKEY&&w==2){self->ShowSearch();return 0;}if(msg==WM_APP+1){if(l==WM_LBUTTONUP)self->Show();if(l==WM_RBUTTONUP){HMENU menu=CreatePopupMenu();AppendMenuW(menu,MF_STRING,1,i18n::Tr(L"新增分区").c_str());AppendMenuW(menu,MF_STRING,2,i18n::Tr(L"显示全部").c_str());AppendMenuW(menu,MF_STRING,9,i18n::Tr(L"全部隐藏").c_str());AppendMenuW(menu,MF_STRING,3,self->desktopMode?i18n::Tr(L"切换普通窗口").c_str():i18n::Tr(L"试验桌面嵌入").c_str());AppendMenuW(menu,MF_STRING,6,i18n::Tr(L"整理桌面…").c_str());AppendMenuW(menu,MF_STRING|(self->layout.widgets.noteVisible?MF_CHECKED:0),7,i18n::Tr(L"便签").c_str());AppendMenuW(menu,MF_STRING|(self->layout.widgets.todoVisible?MF_CHECKED:0),8,i18n::Tr(L"待办").c_str());AppendMenuW(menu,MF_STRING|(self->layout.widgets.clockVisible?MF_CHECKED:0),10,i18n::Tr(L"时钟").c_str());AppendMenuW(menu,MF_STRING|(self->layout.widgets.musicVisible?MF_CHECKED:0),11,i18n::Tr(L"音乐").c_str());AppendMenuW(menu,MF_STRING,12,i18n::Tr(L"搜索").c_str());AppendMenuW(menu,MF_STRING|(self->layout.widgets.weatherVisible?MF_CHECKED:0),13,i18n::Tr(L"天气").c_str());AppendMenuW(menu,MF_STRING,5,i18n::Tr(L"设置").c_str());AppendMenuW(menu,MF_SEPARATOR,0,nullptr);AppendMenuW(menu,MF_STRING,4,i18n::Tr(L"退出").c_str());POINT p{};GetCursorPos(&p);SetForegroundWindow(h);int cmd=TrackPopupMenu(menu,TPM_RETURNCMD|TPM_NONOTIFY,p.x,p.y,0,h,nullptr);DestroyMenu(menu);if(cmd==1)self->Add();if(cmd==2)self->Show();if(cmd==9)self->HideAll();if(cmd==3)self->ToggleDesktop();if(cmd==6)self->ShowTidy();if(cmd==7){self->layout.widgets.noteVisible?self->CloseNote():self->ShowNote();}if(cmd==8){self->layout.widgets.todoVisible?self->CloseTodo():self->ShowTodo();}if(cmd==10){self->layout.widgets.clockVisible?self->CloseClock():self->ShowClock();}if(cmd==11){self->layout.widgets.musicVisible?self->CloseMusic():self->ShowMusic();}if(cmd==12)self->ShowSearch();if(cmd==13){self->layout.widgets.weatherVisible?self->CloseWeather():self->ShowWeather();}if(cmd==5)self->ShowSettings();if(cmd==4)self->Quit();}return 0;}}catch(...){MessageBoxW(h,i18n::Tr(L"操作未完成。").c_str(),L"GuoDesk",MB_OK|MB_ICONERROR);}return DefWindowProcW(h,msg,w,l);}
}


