#include "pch.h"
#include "DeskWindow.h"
#include "Shell.h"
using namespace winrt;
using namespace Microsoft::UI::Xaml;
using namespace Microsoft::UI::Xaml::Controls;
using namespace Microsoft::UI::Xaml::Media;
using namespace Microsoft::UI::Xaml::Media::Animation;
using namespace Windows::ApplicationModel::DataTransfer;
namespace guodesk {
static Brush ResolveBrush(wchar_t const* key,Windows::UI::Color fallback,bool dark){
 try{
  auto res=Application::Current().Resources();
  return res.Lookup(box_value(key)).as<Brush>();
 }catch(...){}
 struct Entry{wchar_t const* key;Windows::UI::Color light;Windows::UI::Color dark;};
 static const Entry palette[]{
  {L"CardBackgroundFillColorDefault",{255,248,248,248},{255,43,43,43}},
  {L"CardBackgroundFillColorSecondary",{255,244,244,244},{255,54,54,54}},
  {L"SubtleFillColorSecondaryBrush",{255,236,236,236},{255,56,56,56}},
  {L"TextFillColorSecondary",{255,97,97,97},{255,199,199,199}},
  {L"ApplicationPageBackgroundThemeBrush",{255,243,243,243},{255,32,32,32}},
 };
 for(auto const& e:palette)if(!wcscmp(e.key,key))return SolidColorBrush(dark?e.dark:e.light);
 return SolidColorBrush(fallback);
}
Brush DeskWindow::ThemeBrush(wchar_t const* key,Windows::UI::Color fallback){return ResolveBrush(key,fallback,root.ActualTheme()==ElementTheme::Dark);}
static Button Action(wchar_t const* glyph,std::function<void()> run){FontIcon f;f.FontFamily(FontFamily(L"Segoe Fluent Icons"));f.Glyph(glyph);f.FontSize(16);Button b;b.Content(f);b.Background(nullptr);b.BorderThickness(Thickness{0});b.Click([run](auto&&,auto&&){try{run();}catch(hresult_error const& e){MessageBoxW(nullptr,e.message().c_str(),L"GuoDesk",MB_OK|MB_ICONERROR);}catch(std::exception const&){MessageBoxW(nullptr,L"操作未完成，请检查路径或访问权限。",L"GuoDesk",MB_OK|MB_ICONERROR);}});return b;}
static MenuFlyoutItem MenuItem(wchar_t const* text,std::function<void()> run){MenuFlyoutItem b;b.Text(text);b.Click([run](auto&&,auto&&){try{run();}catch(...){MessageBoxW(nullptr,L"操作未完成，请检查文件是否存在及访问权限。",L"GuoDesk",MB_OK|MB_ICONERROR);}});return b;}
static int Snap(int value,std::vector<int> const& targets,int threshold){int delta=0,best=threshold+1;for(int t:targets){int d=t-value,ad=d<0?-d:d;if(ad<best){best=ad;delta=d;}}return best<=threshold?delta:0;}
Zone& DeskWindow::Model(){return *std::find_if(owner.layout.zones.begin(),owner.layout.zones.end(),[this](auto const& z){return z.id==id;});}
DeskWindow::DeskWindow(Controller& c,std::wstring key):owner(c),id(std::move(key)){
 window=Window();window.Title(L"GuoDesk");hwnd=shell::Handle(window);
 root=Grid();window.SystemBackdrop(MicaBackdrop());root.Padding(Thickness{12,12,12,12});root.RowSpacing(8);
 RowDefinition header;header.Height(GridLength{44,GridUnitType::Pixel});root.RowDefinitions().Append(header);RowDefinition body;body.Height(GridLength{1,GridUnitType::Star});root.RowDefinitions().Append(body);RowDefinition footer;footer.Height(GridLength{0,GridUnitType::Auto});root.RowDefinitions().Append(footer);
 Grid bar;ColumnDefinition col;col.Width(GridLength{1,GridUnitType::Star});bar.ColumnDefinitions().Append(col);ColumnDefinition buttons;buttons.Width(GridLength{0,GridUnitType::Auto});bar.ColumnDefinitions().Append(buttons);
 title=TextBox();title.Text(Model().name);title.PlaceholderText(L"分区名称");title.Background(SolidColorBrush(Windows::UI::Colors::Transparent()));title.BorderThickness(Thickness{0});title.FontSize(16);title.FontWeight(Windows::UI::Text::FontWeights::SemiBold());title.VerticalContentAlignment(VerticalAlignment::Center);title.Padding(Thickness{4,11,4,11});ToolTipService::SetToolTip(title,box_value(L"点击重命名分区"));auto TitleFill=[this](bool hover){Brush fill=SolidColorBrush(Windows::UI::Colors::Transparent());if(hover)fill=ThemeBrush(L"SubtleFillColorSecondaryBrush",Windows::UI::Color{13,0,0,0});title.Background(fill);};title.PointerEntered([TitleFill](auto&&,auto&&){TitleFill(true);});title.PointerExited([TitleFill](auto&&,auto&&){TitleFill(false);});title.LostFocus([this](auto&&,auto&&){auto name=std::wstring(title.Text());if(name.empty())name=L"未命名分区";Model().name=name;title.Text(name);window.Title(L"GuoDesk · "+name);owner.Save();});bar.Children().Append(title);
 StackPanel actions;actions.Orientation(Orientation::Horizontal);actions.Spacing(4);actions.VerticalAlignment(VerticalAlignment::Center);Grid::SetColumn(actions,1);
 Border dragHandle;FontIcon dragIcon;dragIcon.FontFamily(FontFamily(L"Segoe Fluent Icons"));dragIcon.Glyph(L"\uE7C2");dragIcon.FontSize(16);dragHandle.Child(dragIcon);dragHandle.Padding(Thickness{6,4,6,4});dragHandle.CornerRadius(CornerRadius{4,4,4,4});dragHandle.Background(SolidColorBrush(Windows::UI::Colors::Transparent()));ToolTipService::SetToolTip(dragHandle,box_value(L"按住移动分区"));auto HandleHover=[dragHandle,this](bool hover){Brush fill=SolidColorBrush(Windows::UI::Colors::Transparent());if(hover)fill=ThemeBrush(L"SubtleFillColorSecondaryBrush",Windows::UI::Color{13,0,0,0});dragHandle.Background(fill);};dragHandle.PointerEntered([dragHandle,HandleHover](auto&&,auto&&){HandleHover(true);});dragHandle.PointerExited([dragHandle,HandleHover](auto&&,auto&&){HandleHover(false);});embedTimer=root.DispatcherQueue().CreateTimer();embedTimer.Interval(std::chrono::milliseconds(16));embedTimer.Tick([this](auto&&,auto&&){if(!dragging){embedTimer.Stop();return;}if(!(GetAsyncKeyState(VK_LBUTTON)&0x8000)){embedTimer.Stop();dragging=false;Capture();owner.Save();return;}DragUpdate();});dragHandle.PointerPressed([this,dragHandle](auto&&,Input::PointerRoutedEventArgs const& a)mutable{dragging=true;GetCursorPos(&dragStart);GetWindowRect(hwnd,&dragOrigin);if(!desktop)dragHandle.CapturePointer(a.Pointer());else embedTimer.Start();a.Handled(true);});auto DragMove=[this](auto&&,auto&&){DragUpdate();};dragHandle.PointerMoved(DragMove);root.PointerMoved(DragMove);title.PointerMoved(DragMove);auto EndDrag=[this](auto&&,auto&&){if(!dragging)return;dragging=false;Capture();owner.Save();};dragHandle.PointerReleased(EndDrag);dragHandle.PointerCaptureLost(EndDrag);root.PointerReleased(EndDrag);actions.Children().Append(dragHandle);
auto add=Action(L"\uE710",[this]{Pick();});ToolTipService::SetToolTip(add,box_value(L"添加入口"));add.PointerMoved(DragMove);actions.Children().Append(add);
 chevron=Action(L"\uE70E",[this]{Capture();Model().collapsed=!Model().collapsed;Refresh();Place();owner.Save();});ToolTipService::SetToolTip(chevron,box_value(L"折叠 / 展开"));chevron.PointerMoved(DragMove);actions.Children().Append(chevron);
 auto more=Action(L"\uE712",[]{});ToolTipService::SetToolTip(more,box_value(L"更多操作"));more.Click([this,more](auto&&,auto&&){Menu(more);});more.PointerMoved(DragMove);actions.Children().Append(more);bar.Children().Append(actions);root.Children().Append(bar);
 grid=GridView();grid.SelectionMode(ListViewSelectionMode::None);grid.IsItemClickEnabled(false);grid.AllowDrop(true);grid.HorizontalAlignment(HorizontalAlignment::Stretch);Grid::SetRow(grid,1);root.Children().Append(grid);
 grid.DragOver([this](auto&&,DragEventArgs const& a){a.AcceptedOperation(!Model().mappedFolder.empty()?DataPackageOperation::None:(a.DataView().Contains(StandardDataFormats::StorageItems())?DataPackageOperation::Link:DataPackageOperation::Move));a.Handled(true);});grid.Drop([this](auto&&,DragEventArgs const& a){if(!Model().mappedFolder.empty()){Notify(L"映射分区为只读视图，无法拖入。");return;}Drop(a,Model().entries.size());});
 listHost=ScrollViewer();listPanel=StackPanel();listPanel.Orientation(Orientation::Vertical);listPanel.Spacing(2);listPanel.Padding(Thickness{2,2,2,2});listHost.Content(listPanel);listHost.AllowDrop(true);listHost.Visibility(Visibility::Collapsed);Grid::SetRow(listHost,1);root.Children().Append(listHost);
 listHost.DragOver([this](auto&&,DragEventArgs const& a){a.AcceptedOperation(Model().mappedFolder.empty()?(a.DataView().Contains(StandardDataFormats::StorageItems())?DataPackageOperation::Link:DataPackageOperation::Move):DataPackageOperation::None);a.Handled(true);});listHost.Drop([this](auto&&,DragEventArgs const& a){a.Handled(true);if(!Model().mappedFolder.empty()){Notify(L"映射分区为只读视图，无法拖入。");return;}Drop(a,Model().entries.size());});
 status=TextBlock();status.FontSize(11);status.TextWrapping(TextWrapping::Wrap);status.Foreground(ThemeBrush(L"TextFillColorSecondary",Windows::UI::Color{255,160,160,160}));Grid::SetRow(status,2);root.Children().Append(status);
 window.Content(root);window.Closed([this](auto&&,WindowEventArgs const& args){if(!closing){args.Handled(true);ShowWindow(hwnd,SW_HIDE);}});
 SetWindowSubclass(hwnd,Subclass,1,reinterpret_cast<DWORD_PTR>(this));window.Activate();auto presenter=window.AppWindow().Presenter().as<Microsoft::UI::Windowing::OverlappedPresenter>();presenter.SetBorderAndTitleBar(true,false);window.AppWindow().IsShownInSwitchers(false);ApplySettings();Place();
 Storyboard fade;DoubleAnimation alpha;alpha.From(0.0);alpha.To(1.0);alpha.Duration(Duration{std::chrono::milliseconds(220),DurationType::TimeSpan});Storyboard::SetTarget(alpha,root);Storyboard::SetTargetProperty(alpha,L"Opacity");fade.Children().Append(alpha);fade.Begin();
}
DeskWindow::~DeskWindow(){closing=true;if(IsWindow(hwnd)){RemoveWindowSubclass(hwnd,Subclass,1);window.Close();}}
void DeskWindow::ApplySettings(){auto const& theme=owner.layout.settings.theme;root.RequestedTheme(theme==L"Dark"?ElementTheme::Dark:theme==L"Light"?ElementTheme::Light:ElementTheme::Default);status.Foreground(ThemeBrush(L"TextFillColorSecondary",Windows::UI::Color{255,160,160,160}));Refresh();}
void DeskWindow::Notify(std::wstring const& text){status.Text(text);}
void DeskWindow::Capture(){if(!IsWindow(hwnd))return;RECT r{};GetWindowRect(hwnd,&r);auto& z=Model();z.x=r.left;z.y=r.top;z.width=r.right-r.left;if(!z.collapsed)z.height=r.bottom-r.top;}
void DeskWindow::Place(){auto& z=Model();shell::Fit(z);POINT p{z.x,z.y};if(desktop)ScreenToClient(GetParent(hwnd),&p);SetWindowPos(hwnd,nullptr,p.x,p.y,z.width,z.collapsed?88:z.height,SWP_NOZORDER|SWP_NOACTIVATE);}
std::vector<RECT> DeskWindow::Peers(){std::vector<RECT> list;for(auto& w:owner.windows)if(w.get()!=this&&IsWindow(w->hwnd)&&IsWindowVisible(w->hwnd)){RECT r{};GetWindowRect(w->hwnd,&r);list.push_back(r);}return list;}
void DeskWindow::DragUpdate(){if(!dragging)return;POINT p{};GetCursorPos(&p);int x=dragOrigin.left+p.x-dragStart.x,y=dragOrigin.top+p.y-dragStart.y,w=dragOrigin.right-dragOrigin.left,h=dragOrigin.bottom-dragOrigin.top;int threshold=MulDiv(8,GetDpiForWindow(hwnd),96);std::vector<int> xs,ys;auto peers=Peers();for(auto const& r:peers){int cx=r.left+(r.right-r.left)/2,cy=r.top+(r.bottom-r.top)/2;xs.push_back(r.left);xs.push_back(r.right-w);xs.push_back(r.left-w);xs.push_back(r.right);xs.push_back(cx-w/2);ys.push_back(r.top);ys.push_back(r.bottom-h);ys.push_back(r.top-h);ys.push_back(r.bottom);ys.push_back(cy-h/2);}MONITORINFO mi{sizeof(mi)};GetMonitorInfoW(MonitorFromWindow(hwnd,MONITOR_DEFAULTTONEAREST),&mi);xs.push_back(mi.rcWork.left);xs.push_back(mi.rcWork.right-w);ys.push_back(mi.rcWork.top);ys.push_back(mi.rcWork.bottom-h);x+=Snap(x,xs,threshold);y+=Snap(y,ys,threshold);SetWindowPos(hwnd,nullptr,x,y,0,0,SWP_NOSIZE|SWP_NOZORDER|SWP_NOACTIVATE);}
void DeskWindow::SnapResize(RECT& r,int edge){auto peers=Peers();if(peers.empty())return;int threshold=MulDiv(10,GetDpiForWindow(hwnd),96);bool left=edge==WMSZ_LEFT||edge==WMSZ_TOPLEFT||edge==WMSZ_BOTTOMLEFT,top=edge==WMSZ_TOP||edge==WMSZ_TOPLEFT||edge==WMSZ_TOPRIGHT;int w=r.right-r.left,best=threshold+1,target=w;for(auto const& p:peers){int pw=p.right-p.left,d=pw-w,ad=d<0?-d:d;if(ad<best){best=ad;target=pw;}}if(best<=threshold){if(left)r.left=r.right-target;else r.right=r.left+target;}int h=r.bottom-r.top;best=threshold+1;target=h;for(auto const& p:peers){int ph=p.bottom-p.top,d=ph-h,ad=d<0?-d:d;if(ad<best){best=ad;target=ph;}}if(best<=threshold){if(top)r.top=r.bottom-target;else r.bottom=r.top+target;}}
void DeskWindow::Show(){ShowWindow(hwnd,SW_SHOWNOACTIVATE);}
void DeskWindow::SetDesktop(bool enabled){Capture();bool was=desktop;if(enabled){desktop=shell::Attach(hwnd,owner.host);root.Background(ThemeBrush(L"ApplicationPageBackgroundThemeBrush",Windows::UI::Color{255,32,32,32}));Notify(desktop?L"实验性桌面宿主 · 添加入口不会移动原文件":L"嵌入失败，已保留普通窗口模式");}else{if(desktop)shell::Detach(hwnd);desktop=false;root.Background(nullptr);Notify(L"普通窗口模式 · 可在菜单中试验桌面嵌入");}Place();if(desktop!=was){RECT r{};GetWindowRect(hwnd,&r);int width=r.right-r.left,height=r.bottom-r.top;SetWindowPos(hwnd,nullptr,0,0,width,height+1,SWP_NOMOVE|SWP_NOZORDER|SWP_NOACTIVATE);SetWindowPos(hwnd,nullptr,0,0,width,height,SWP_NOMOVE|SWP_NOZORDER|SWP_NOACTIVATE);}}
void DeskWindow::Pick(bool folder){if(!Model().mappedFolder.empty()){Notify(L"映射分区为只读视图：请在资源管理器中修改文件夹后右键刷新。");return;}for(auto const& path:shell::Pick(hwnd,folder))AddEntry(Model(),path);Refresh();owner.Save();}
void DeskWindow::Menu(FrameworkElement const& target){auto& z=Model();bool mapped=!z.mappedFolder.empty();MenuFlyout menu;
 menu.Items().Append(MenuItem(L"添加文件 / 应用",[this,mapped]{if(mapped){Notify(L"映射分区为只读视图：请在资源管理器中修改文件夹后右键刷新。");return;}Pick();}));
 menu.Items().Append(MenuItem(L"添加文件夹",[this,mapped]{if(mapped){Notify(L"映射分区为只读视图：请在资源管理器中修改文件夹后右键刷新。");return;}Pick(true);}));
 menu.Items().Append(MenuItem(mapped?L"取消文件夹映射":L"映射文件夹…",[this,mapped]{if(mapped){Model().mappedFolder.clear();Refresh();owner.Save();Notify(L"已取消映射，恢复普通分区。");return;}auto picked=shell::Pick(hwnd,true);if(picked.empty())return;Model().mappedFolder=picked.front();SyncMapped(Model());Refresh();owner.Save();Notify(L"已映射文件夹（只读视图）：修改请在资源管理器中完成，右键可刷新。");}));
 menu.Items().Append(MenuItem(z.viewMode==L"list"?L"切换为图标视图":L"切换为列表视图",[this]{auto& m=Model();m.viewMode=m.viewMode==L"list"?L"grid":L"list";Refresh();owner.Save();}));
 menu.Items().Append(MenuItem((std::wstring(L"文件名：")+std::wstring(z.nameLines==0?L"隐藏":z.nameLines==1?L"一行":L"两行")+L"（点击切换）").c_str(),[this]{auto& m=Model();m.nameLines=m.nameLines==0?2:m.nameLines-1;Refresh();owner.Save();}));
 menu.Items().Append(MenuItem(L"新增分区",[this]{owner.Add();}));
 menu.Items().Append(MenuItem(L"立即刷新",[this]{if(!Model().mappedFolder.empty())SyncMapped(Model());Refresh();}));
 menu.Items().Append(MenuItem(owner.desktopMode?L"切换普通窗口":L"试验桌面嵌入",[this]{owner.ToggleDesktop();}));menu.Items().Append(MenuItem(L"设置",[this]{owner.ShowSettings();}));menu.Items().Append(MenuItem(L"删除分区（保留原文件）",[this]{auto key=id;root.DispatcherQueue().TryEnqueue([this,key]{owner.Remove(key);});}));menu.ShowAt(target);}
void DeskWindow::Refresh(){auto& z=Model();title.Text(z.name);window.Title(L"GuoDesk · "+z.name);grid.Visibility(z.collapsed||z.viewMode!=L"grid"?Visibility::Collapsed:Visibility::Visible);listHost.Visibility(z.collapsed||z.viewMode!=L"list"?Visibility::Collapsed:Visibility::Visible);FontIcon chevronGlyph;chevronGlyph.FontFamily(FontFamily(L"Segoe Fluent Icons"));chevronGlyph.Glyph(z.collapsed?L"\uE70D":L"\uE70E");chevronGlyph.FontSize(16);chevron.Content(chevronGlyph);grid.Items().Clear();listPanel.Children().Clear();bool compact=owner.layout.settings.compact;bool mapped=!z.mappedFolder.empty();size_t const limit=500,total=z.entries.size();
 auto itemMenu=[this](std::wstring const& path,std::wstring const& key,bool isMapped){MenuFlyout menu;menu.Items().Append(MenuItem(L"打开",[this,path]{shell::Open(hwnd,path);}));menu.Items().Append(MenuItem(L"定位原文件",[this,path]{shell::Reveal(hwnd,path);}));if(!isMapped){menu.Items().Append(MenuItem(L"重新定位文件",[this,key]{auto picked=shell::Pick(hwnd);if(picked.empty())return;auto& entries=Model().entries;auto duplicate=std::find_if(entries.begin(),entries.end(),[&](auto const& x){return x.id!=key&&PathKey(x.path)==PathKey(picked.front());});if(duplicate!=entries.end()){Notify(L"此目标已在当前分区中。 ");return;}for(auto& x:entries)if(x.id==key)x.path=picked.front();Refresh();owner.Save();}));menu.Items().Append(MenuItem(L"移除入口（保留原文件）",[this,key]{std::erase_if(Model().entries,[&](auto const& x){return x.id==key;});Refresh();owner.Save();}));}return menu;};
 for(size_t i=0;i<std::min(total,limit);++i){auto const& e=z.entries[i];auto path=e.path,key=e.id;auto index=i;bool exists=GetFileAttributesW(path.c_str())!=INVALID_FILE_ATTRIBUTES;auto menu=itemMenu(path,key,mapped);
  if(z.viewMode==L"list"){
   Border row;row.Height(30);row.CornerRadius(CornerRadius{4,4,4,4});row.Padding(Thickness{8,3,8,3});row.Background(ThemeBrush(L"CardBackgroundFillColorDefault",Windows::UI::Color{255,60,60,60}));ToolTipService::SetToolTip(row,box_value(path));row.PointerEntered([weak=make_weak(row),this](auto&&,auto&&){if(auto r=weak.get())r.Background(ThemeBrush(L"CardBackgroundFillColorSecondary",Windows::UI::Color{255,80,80,80}));});row.PointerExited([weak=make_weak(row),this](auto&&,auto&&){if(auto r=weak.get())r.Background(ThemeBrush(L"CardBackgroundFillColorDefault",Windows::UI::Color{255,60,60,60}));});
   Grid line;ColumnDefinition ci,cn,cp;ci.Width(GridLength{0,GridUnitType::Auto});cn.Width(GridLength{2,GridUnitType::Star});cp.Width(GridLength{3,GridUnitType::Star});line.ColumnDefinitions().Append(ci);line.ColumnDefinitions().Append(cn);line.ColumnDefinitions().Append(cp);
   Image icon;icon.Width(18);icon.Height(18);line.Children().Append(icon);shell::LoadIcon(path,icon);
   TextBlock name;name.Text((exists?L"":L"⚠ ")+shell::Name(path));name.FontSize(12);name.VerticalAlignment(VerticalAlignment::Center);name.Margin(Thickness{8,0,8,0});name.TextTrimming(TextTrimming::CharacterEllipsis);name.Foreground(ThemeBrush(L"TextFillColorSecondary",Windows::UI::Color{255,180,180,180}));Grid::SetColumn(name,1);line.Children().Append(name);
   TextBlock where;where.Text(path);where.FontSize(11);where.VerticalAlignment(VerticalAlignment::Center);where.TextTrimming(TextTrimming::CharacterEllipsis);where.Foreground(ThemeBrush(L"TextFillColorSecondary",Windows::UI::Color{255,160,160,160}));Grid::SetColumn(where,2);line.Children().Append(where);
   row.Child(line);row.DoubleTapped([this,path](auto&&,auto&&){try{shell::Open(hwnd,path);}catch(...){Notify(L"无法打开目标，请右键重新定位。 ");}});row.ContextFlyout(menu);listPanel.Children().Append(row);
  }else{
   Border tile;tile.Width(compact?72:88);tile.Height(compact?78:94);tile.Padding(Thickness{4,4,4,4});tile.CornerRadius(CornerRadius{8,8,8,8});tile.Background(ThemeBrush(L"CardBackgroundFillColorDefault",Windows::UI::Color{255,60,60,60}));tile.CanDrag(!mapped);tile.AllowDrop(true);ToolTipService::SetToolTip(tile,box_value(path));tile.PointerEntered([weak=make_weak(tile),this](auto&&,auto&&){if(auto t=weak.get())t.Background(ThemeBrush(L"CardBackgroundFillColorSecondary",Windows::UI::Color{255,80,80,80}));});tile.PointerExited([weak=make_weak(tile),this](auto&&,auto&&){if(auto t=weak.get())t.Background(ThemeBrush(L"CardBackgroundFillColorDefault",Windows::UI::Color{255,60,60,60}));});StackPanel content;content.Spacing(5);Image icon;icon.Width(compact?32:40);icon.Height(compact?32:40);content.Children().Append(icon);shell::LoadIcon(path,icon);TextBlock label;label.Text((exists?L"":L"⚠ ")+shell::Name(path));label.FontSize(12);label.TextAlignment(TextAlignment::Center);label.Foreground(ThemeBrush(L"TextFillColorSecondary",Windows::UI::Color{255,180,180,180}));if(z.nameLines==0)label.Visibility(Visibility::Collapsed);else if(z.nameLines==1){label.TextWrapping(TextWrapping::NoWrap);label.TextTrimming(TextTrimming::CharacterEllipsis);label.MaxHeight(18);}else{label.TextWrapping(TextWrapping::Wrap);label.MaxHeight(36);}content.Children().Append(label);tile.Child(content);
   tile.DoubleTapped([this,path](auto&&,auto&&){try{shell::Open(hwnd,path);}catch(...){Notify(L"无法打开目标，请右键重新定位。 ");}});
   if(!mapped)tile.DragStarting([key](auto&&,DragStartingEventArgs const& a){a.Data().SetText(L"guodesk-entry:"+key);a.Data().RequestedOperation(DataPackageOperation::Move);});
   tile.DragOver([mapped](auto&&,DragEventArgs const& a){a.AcceptedOperation(mapped?DataPackageOperation::None:(a.DataView().Contains(StandardDataFormats::StorageItems())?DataPackageOperation::Link:DataPackageOperation::Move));a.Handled(true);});
   if(!mapped)tile.Drop([this,index](auto&&,DragEventArgs const& a){a.Handled(true);Drop(a,index);});
   tile.ContextFlyout(menu);grid.Items().Append(tile);}
 }
 if(mapped){std::wstring head=z.entries.empty()?L"映射文件夹为空或不可访问":L"映射视图（只读）· "+shell::Name(z.mappedFolder)+L" · 共 "+std::to_wstring(total)+L" 项";if(total>limit)head+=L" · 已显示前 "+std::to_wstring(limit)+L" 项";Notify(head+L" · 双击打开 · 右键更多");}
 else Notify(z.entries.empty()?L"拖入文件、文件夹或应用快捷方式 · 原文件保持原位":L"双击打开 · 右键管理 · 拖拽排序");}
fire_and_forget DeskWindow::Drop(DragEventArgs a,size_t position){auto deferral=a.GetDeferral();auto weak=winrt::make_weak(root);auto key=id;auto* controller=&owner;try{auto data=a.DataView();if(data.Contains(StandardDataFormats::StorageItems())){auto items=co_await data.GetStorageItemsAsync();auto it=std::find_if(controller->layout.zones.begin(),controller->layout.zones.end(),[&](auto const& z){return z.id==key;});if(it!=controller->layout.zones.end())for(auto const& item:items)if(!item.Path().empty())AddEntry(*it,std::wstring(item.Path()));}else if(data.Contains(StandardDataFormats::Text())){std::wstring text(co_await data.GetTextAsync());if(text.starts_with(L"guodesk-entry:"))controller->MoveEntry(text.substr(14),key,position);}if(auto live=weak.get())live.DispatcherQueue().TryEnqueue([controller]{controller->Refresh();controller->Save();});}catch(...){if(auto live=weak.get())MessageBoxW(nullptr,L"无法添加拖入项目。",L"GuoDesk",MB_OK);}deferral.Complete();}
LRESULT CALLBACK DeskWindow::Subclass(HWND h,UINT msg,WPARAM w,LPARAM l,UINT_PTR,DWORD_PTR data){auto* self=reinterpret_cast<DeskWindow*>(data);if(msg==WM_NCCALCSIZE&&w&&self->desktop)return 0;if(msg==WM_SIZING&&l){self->SnapResize(*reinterpret_cast<RECT*>(l),static_cast<int>(w));return TRUE;}if(msg==WM_EXITSIZEMOVE){self->Capture();self->owner.Save();}if(msg==WM_DISPLAYCHANGE)self->Place();if(msg==WM_DPICHANGED){auto* rect=reinterpret_cast<RECT*>(l);SetWindowPos(h,nullptr,rect->left,rect->top,rect->right-rect->left,rect->bottom-rect->top,SWP_NOZORDER|SWP_NOACTIVATE);}return DefSubclassProc(h,msg,w,l);}
}

namespace guodesk {
static std::wstring StampOf(std::wstring const& folder){WIN32_FILE_ATTRIBUTE_DATA fa{};if(!GetFileAttributesExW(folder.c_str(),GetFileExInfoStandard,&fa))return{};return std::to_wstring(fa.ftLastWriteTime.dwHighDateTime)+L"-"+std::to_wstring(fa.ftLastWriteTime.dwLowDateTime);}
Controller::Controller(std::filesystem::path root):store(std::move(root)){mutex=CreateMutexW(nullptr,FALSE,L"Local\\GuoDesk.Prototype");if(GetLastError()==ERROR_ALREADY_EXISTS){CloseHandle(mutex);mutex=nullptr;HWND prev=FindWindowW(L"GuoDesk.Controller",nullptr);if(prev)PostMessageW(prev,WM_APP+2,0,0);throw already_running{};}}
Controller::~Controller(){if(messageWindow){KillTimer(messageWindow,1);Shell_NotifyIconW(NIM_DELETE,&tray);DestroyWindow(messageWindow);}windows.clear();if(mutex)CloseHandle(mutex);}
void Controller::AddTray(){tray={sizeof(tray)};tray.hWnd=messageWindow;tray.uID=1;tray.uFlags=NIF_ICON|NIF_MESSAGE|NIF_TIP;tray.uCallbackMessage=WM_APP+1;tray.hIcon=LoadIconW(GetModuleHandleW(nullptr),MAKEINTRESOURCEW(101));if(!tray.hIcon)tray.hIcon=LoadIconW(nullptr,IDI_APPLICATION);wcscpy_s(tray.szTip,L"GuoDesk · 桌面分区");Shell_NotifyIconW(NIM_ADD,&tray);}
void Controller::Start(){std::wstring warning;layout=store.Load(warning);for(auto& z:layout.zones)if(!z.mappedFolder.empty())SyncMapped(z);WNDCLASSW cls{};cls.lpfnWndProc=MessageProc;cls.hInstance=GetModuleHandleW(nullptr);cls.lpszClassName=L"GuoDesk.Controller";RegisterClassW(&cls);messageWindow=CreateWindowExW(WS_EX_TOOLWINDOW,cls.lpszClassName,L"GuoDesk Controller",WS_POPUP,0,0,0,0,nullptr,nullptr,cls.hInstance,this);taskbarCreated=RegisterWindowMessageW(L"TaskbarCreated");AddTray();for(auto const& z:layout.zones){windows.push_back(std::make_unique<DeskWindow>(*this,z.id));if(!z.mappedFolder.empty()){auto stamp=StampOf(z.mappedFolder);if(!stamp.empty())mappedStamp[PathKey(z.mappedFolder)]=stamp;}}SetTimer(messageWindow,1,2000,nullptr);Save();if(!warning.empty())MessageBoxW(nullptr,warning.c_str(),L"GuoDesk 配置恢复",MB_OK|MB_ICONINFORMATION);}
void Controller::Save(){try{store.Save(layout);}catch(...){for(auto& w:windows)w->Notify(L"保存失败：请检查本地数据目录权限和剩余空间。 ");}}
void Controller::Add(){Zone zone;zone.id=NewId();zone.name=L"新分区";zone.x+=static_cast<int>(layout.zones.size())*30;zone.y+=static_cast<int>(layout.zones.size())*30;auto key=zone.id;layout.zones.push_back(std::move(zone));windows.push_back(std::make_unique<DeskWindow>(*this,key));if(desktopMode)windows.back()->SetDesktop(true);Save();}
void Controller::Remove(std::wstring const& key){auto it=std::find_if(layout.zones.begin(),layout.zones.end(),[&](auto const& z){return z.id==key;});if(it==layout.zones.end())return;auto index=static_cast<size_t>(it-layout.zones.begin());windows.erase(windows.begin()+index);layout.zones.erase(it);Save();}
void Controller::Refresh(){for(auto& w:windows)w->Refresh();}
void Controller::Show(){for(auto& w:windows)w->Show();if(windows.empty())Add();}
void Controller::Quit(){if(quitting)return;quitting=true;for(auto& w:windows)w->Capture();Save();Shell_NotifyIconW(NIM_DELETE,&tray);Application::Current().Exit();}
void Controller::ToggleDesktop(){desktopMode=!desktopMode;host=shell::DesktopHost();for(auto& w:windows)w->SetDesktop(desktopMode);}
void Controller::ShowSettings(){if(!settings)settings=std::make_unique<SettingsWindow>(*this);settings->Apply();settings->Show();}
void Controller::CloseSettings(){settings.reset();}
void Controller::ApplySettings(){for(auto& w:windows)w->ApplySettings();}
void Controller::MoveEntry(std::wstring const& key,std::wstring const& target,size_t index){auto to=std::find_if(layout.zones.begin(),layout.zones.end(),[&](auto const& z){return z.id==target;});if(to==layout.zones.end())return;for(auto& from:layout.zones){auto entry=std::find_if(from.entries.begin(),from.entries.end(),[&](auto const& e){return e.id==key;});if(entry==from.entries.end())continue;if(&from!=&*to)for(auto const& existing:to->entries)if(PathKey(existing.path)==PathKey(entry->path))return;auto value=*entry;auto old=static_cast<size_t>(entry-from.entries.begin());from.entries.erase(entry);if(&from==&*to && index>old)--index;index=std::min(index,to->entries.size());to->entries.insert(to->entries.begin()+index,std::move(value));return;}}
LRESULT CALLBACK Controller::MessageProc(HWND h,UINT msg,WPARAM w,LPARAM l){auto* self=reinterpret_cast<Controller*>(GetWindowLongPtrW(h,GWLP_USERDATA));if(msg==WM_NCCREATE){self=static_cast<Controller*>(reinterpret_cast<CREATESTRUCTW*>(l)->lpCreateParams);SetWindowLongPtrW(h,GWLP_USERDATA,reinterpret_cast<LONG_PTR>(self));}if(!self)return DefWindowProcW(h,msg,w,l);try{if(msg==self->taskbarCreated&&self->taskbarCreated){self->AddTray();if(self->desktopMode){self->host=shell::DesktopHost();for(auto& item:self->windows)if(IsWindow(item->hwnd))item->SetDesktop(true);}}if(msg==WM_TIMER){if(self->desktopMode){auto host=shell::DesktopHost();if(host&&host!=self->host){self->host=host;for(auto& item:self->windows)if(IsWindow(item->hwnd))item->SetDesktop(true);}}
 for(size_t i=0;i<self->layout.zones.size()&&i<self->windows.size();++i){auto& z=self->layout.zones[i];if(z.mappedFolder.empty())continue;auto stamp=StampOf(z.mappedFolder);if(stamp.empty())continue;auto key=PathKey(z.mappedFolder);auto it=self->mappedStamp.find(key);if(it==self->mappedStamp.end()){self->mappedStamp[key]=stamp;continue;}if(it->second!=stamp){it->second=stamp;SyncMapped(z);self->windows[i]->Refresh();}}}if(msg==WM_APP+2){self->Show();if(!self->windows.empty())SetForegroundWindow(self->windows.front()->hwnd);return 0;}if(msg==WM_APP+1){if(l==WM_LBUTTONUP)self->Show();if(l==WM_RBUTTONUP){HMENU menu=CreatePopupMenu();AppendMenuW(menu,MF_STRING,1,L"新增分区");AppendMenuW(menu,MF_STRING,2,L"显示全部");AppendMenuW(menu,MF_STRING,3,self->desktopMode?L"切换普通窗口":L"试验桌面嵌入");AppendMenuW(menu,MF_STRING,5,L"设置");AppendMenuW(menu,MF_SEPARATOR,0,nullptr);AppendMenuW(menu,MF_STRING,4,L"退出");POINT p{};GetCursorPos(&p);SetForegroundWindow(h);int cmd=TrackPopupMenu(menu,TPM_RETURNCMD|TPM_NONOTIFY,p.x,p.y,0,h,nullptr);DestroyMenu(menu);if(cmd==1)self->Add();if(cmd==2)self->Show();if(cmd==3)self->ToggleDesktop();if(cmd==5)self->ShowSettings();if(cmd==4)self->Quit();}return 0;}}catch(...){MessageBoxW(h,L"操作未完成。",L"GuoDesk",MB_OK|MB_ICONERROR);}return DefWindowProcW(h,msg,w,l);}
}


