#include "pch.h"
#include "Core.h"
#include "Shell.h"
#include "EvSearch.h"
#include "I18n.h"
#include "WebDav.h"
#include <iostream>
#include <cmath>
namespace guodesk {
void RunTests(std::filesystem::path const& output){std::ofstream report(output);int passed=0;auto expect=[&](bool ok,char const* name){report<<(ok?"PASS ":"FAIL ")<<name<<'\n';report.flush();if(!ok)throw std::runtime_error(name);++passed;};
 Zone z;z.id=NewId();z.name=L"中文 分区";expect(AddEntry(z,L"C:\\测试 文件\\Demo.lnk"),"add unicode path");expect(!AddEntry(z,L"c:\\测试 文件\\DEMO.lnk"),"case insensitive duplicate");expect(!AddEntry(z,L"C:\\测试 文件\\sub\\..\\Demo.lnk"),"normalized duplicate");
 Layout l{{z}};l.settings.theme=L"Dark";l.settings.compact=true;auto round=Deserialize(Serialize(l));expect(round.zones[0].name==z.name && round.zones[0].entries[0].path==z.entries[0].path,"JSON unicode roundtrip");expect(round.settings.theme==L"Dark"&&round.settings.compact,"settings persisted");auto legacy=Deserialize("{\"version\":1,\"zones\":[]}");expect(legacy.settings.theme.empty()&&!legacy.settings.compact,"missing settings tolerated");expect(Deserialize(Serialize(Layout{})).zones.empty(),"empty layout stays empty");
 l.zones[0].mappedFolder=L"C:\\测 试 目录";l.zones[0].viewMode=L"list";l.zones[0].nameLines=1;auto rt=Deserialize(Serialize(l));expect(rt.zones[0].mappedFolder==L"C:\\测 试 目录"&&rt.zones[0].viewMode==L"list"&&rt.zones[0].nameLines==1,"mapped zone fields roundtrip");
 auto fallback=Deserialize("{\"version\":1,\"zones\":[{\"id\":\"a\",\"name\":\"n\",\"x\":0,\"y\":0,\"width\":280,\"height\":160,\"collapsed\":false,\"entries\":[],\"viewMode\":\"weird\",\"nameLines\":9}]}");expect(fallback.zones[0].viewMode==L"grid"&&fallback.zones[0].nameLines==2&&fallback.zones[0].mappedFolder.empty(),"invalid view fields fall back");
 auto dir=std::filesystem::temp_directory_path()/NewId();std::filesystem::create_directories(dir/L"子目录");std::ofstream(dir/L"b.txt");std::ofstream(dir/L"a.txt");
 Zone mz;mz.id=NewId();mz.mappedFolder=dir.wstring();SyncMapped(mz);expect(mz.entries.size()==3,"mapped sync lists children");expect(PathKey(mz.entries[0].path)==PathKey((dir/L"子目录").wstring()),"mapped sync folders first");
 std::filesystem::remove(dir/L"a.txt");SyncMapped(mz);expect(mz.entries.size()==2,"mapped sync reflects deletion");
 mz.mappedFolder=dir/L"missing";SyncMapped(mz);expect(mz.entries.size()==2,"missing folder keeps entries");
 std::filesystem::remove_all(dir);
 auto hdir=std::filesystem::temp_directory_path()/NewId();std::filesystem::create_directories(hdir);std::ofstream(hdir/L"keep.txt");std::ofstream(hdir/L"desktop.ini");
 Zone hz;hz.id=NewId();hz.mappedFolder=hdir.wstring();SyncMapped(hz);expect(hz.entries.size()==1&&PathKey(hz.entries[0].path)==PathKey((hdir/L"keep.txt").wstring()),"mapped sync skips desktop.ini");
 std::filesystem::remove_all(hdir);
 expect(Deserialize("{\"version\":1,\"zones\":[]}").rules.size()==3,"default rules injected");
 Rule dr;dr.id=NewId();dr.name=L"测试规则";dr.exts={L".PDF",L"doc"};dr.targetZone=z.id;Layout rl{{z}};rl.rules={dr};auto rr=Deserialize(Serialize(rl));expect(rr.rules.size()==1&&rr.rules[0].name==L"测试规则"&&rr.rules[0].targetZone==z.id,"rules roundtrip");
 auto rdir=std::filesystem::temp_directory_path()/NewId();std::filesystem::create_directories(rdir);std::ofstream(rdir/L"报告.pdf");std::ofstream(rdir/L"简历-v2.docx");std::ofstream(rdir/L"photo.png");std::ofstream(rdir/L"misc.xyz");std::ofstream(rdir/L"desktop.ini");std::filesystem::create_directories(rdir/L"文件夹");
 auto files=ListLooseFiles(rdir.wstring());expect(files.size()==4,"loose files exclude folders and ini");
 Rule docRule;docRule.id=NewId();docRule.name=L"文档";docRule.exts={L"pdf"};docRule.targetZone=z.id;
 Rule kwRule;kwRule.id=NewId();kwRule.name=L"简历";kwRule.keywords={L"简历"};kwRule.targetZone=z.id;
 std::vector<std::wstring> un;auto plan=BuildPlan({docRule,kwRule},l.zones,files,&un);expect(plan.size()==2&&un.size()==2,"plan matches ext and keyword");
 expect(plan[0].rule==L"文档"&&PathKey(plan[0].path)==PathKey((rdir/L"报告.pdf").wstring()),"extension rule hit");
 expect(plan[1].rule==L"简历","keyword rule hit");
 Rule nb=docRule;nb.id=NewId();nb.targetZone=L"";std::vector<std::wstring> un2;auto plan2=BuildPlan({nb},l.zones,files,&un2);expect(plan2.empty()&&un2.size()==files.size(),"unbound rule skipped");
 Zone az;az.id=z.id;Layout al{{az}};expect(ApplyPlan(al,plan)==2,"apply adds references");expect(al.zones[0].entries.size()==2,"applied entries correct");
 expect(std::filesystem::exists(rdir/L"报告.pdf"),"apply never moves files");
 expect(ApplyPlan(al,plan)==0,"reapply dedupes");
 std::filesystem::remove_all(rdir);
 auto adir=std::filesystem::temp_directory_path()/NewId();std::filesystem::create_directories(adir/L"sub/deep");std::ofstream(adir/L"a.pdf");std::ofstream(adir/L"b.png");std::ofstream(adir/L"junk.xyz");std::ofstream(adir/L"desktop.ini");std::ofstream(adir/L"sub/c.pdf");std::ofstream(adir/L"sub/deep/d.png");std::filesystem::create_directories(adir/L"folder");
 expect(ListLooseFiles(adir.wstring()).size()==3,"loose files stay single-level unless asked");
 auto deep=ListLooseFiles(adir.wstring(),true);auto hasFile=[&](std::wstring const& p){return std::any_of(deep.begin(),deep.end(),[&](auto const& q){return PathKey(q)==PathKey(p);});};
 expect(deep.size()==5&&hasFile((adir/L"sub"/L"c.pdf").wstring())&&hasFile((adir/L"sub"/L"deep"/L"d.png").wstring()),"recursive listing descends into subfolders");
 expect(deep.size()==5&&PathKey(deep.front())==PathKey((adir/L"a.pdf").wstring()),"recursive listing keeps the logical sort");
 expect(ListLooseFiles(adir.wstring(),true,2).size()==2,"recursive listing honours the limit");
 std::vector<std::wstring> un3;auto groups=ArchivePlan({docRule,kwRule},deep,&un3);
 expect(groups.size()==1&&groups[0].category==L"文档"&&groups[0].paths.size()==2,"archive groups hits under the rule name");
 expect(un3.size()==3,"archive leaves unmatched files where they are");
 Rule sizeGate;sizeGate.id=NewId();sizeGate.name=L"大件";sizeGate.exts={L"zip"};sizeGate.minSizeKb=1024;
 expect(RuleMatches(sizeGate,L"zip",L"a.zip",2048,0)&&!RuleMatches(sizeGate,L"zip",L"a.zip",512,0),"a size floor rejects files below it");
 expect(!RuleMatches(sizeGate,L"zip",L"a.zip",-1,0),"a size floor never trusts an unmeasurable file");
 Rule stale;stale.id=NewId();stale.name=L"陈旧";stale.keywords={L"报告"};stale.olderThanDays=30;
 expect(RuleMatches(stale,L"pdf",L"报告.pdf",0,31)&&!RuleMatches(stale,L"pdf",L"报告.pdf",0,29),"an age gate needs the file to be old enough");
 expect(!RuleMatches(stale,L"pdf",L"报告.pdf",0,-1),"an age gate never trusts an unmeasurable date");
 expect(RuleMatches(stale,L"pdf",L"报告.pdf",0,0)==false,"a keyword alone does not beat the age gate");
 expect(!RuleMatches(Rule{},L"pdf",L"a.pdf",0,0),"a rule without conditions matches nothing");
 expect(!RuleMatches(sizeGate,L"rar",L"a.rar",4096,99),"the extension still decides before any gate");
 expect(ClampSizeKb(-5)==0&&ClampSizeKb(200000000)==100000000&&ClampAgeDays(-1)==0&&ClampAgeDays(999999)==36500,"rule gates clamp into range");
 expect(CategoryFolder(L"照片 2024.",L"X")==L"照片 2024","a category name trims its trailing dot");
 expect(CategoryFolder(L"A/B:C*D?E\"F<G>|H\\I",L"X")==L"ABCDEFGHI","a category name drops characters Windows forbids in paths");
 expect(CategoryFolder(L"   ",L"X")==L"X","a blank category name falls back");
 expect(CategoryFolder(L"CON",L"X")==L"CON_","a reserved category name gets a suffix");
 Rule dims;dims.id=NewId();dims.name=L"影音";dims.exts={L"mp4"};dims.targetZone=z.id;dims.minSizeKb=1024;dims.maxSizeKb=4096;dims.olderThanDays=7;
 Layout dl{{z}};dl.rules={dims};auto drt=Deserialize(Serialize(dl));
 expect(drt.rules.size()==1&&drt.rules[0].minSizeKb==1024&&drt.rules[0].maxSizeKb==4096&&drt.rules[0].olderThanDays==7,"rule gates roundtrip");
 auto legacyRules=Deserialize("{\"version\":1,\"zones\":[],\"rules\":[{\"id\":\"r1\",\"name\":\"n\",\"exts\":[\"pdf\"],\"keywords\":[]}]}");
 expect(legacyRules.rules.size()==1&&legacyRules.rules[0].minSizeKb==0&&legacyRules.rules[0].olderThanDays==0,"legacy rules keep the default gates");
 auto bogusRules=Deserialize("{\"version\":1,\"zones\":[],\"rules\":[{\"id\":\"r1\",\"name\":\"n\",\"exts\":[\"pdf\"],\"keywords\":[],\"minSize\":-4,\"maxSize\":1e99,\"olderThan\":999999}]}");
 expect(bogusRules.rules[0].minSizeKb==0&&bogusRules.rules[0].maxSizeKb==100000000&&bogusRules.rules[0].olderThanDays==36500,"absurd gates are clamped on load");
 auto flipped=Deserialize("{\"version\":1,\"zones\":[],\"rules\":[{\"id\":\"r1\",\"name\":\"n\",\"exts\":[\"pdf\"],\"keywords\":[],\"minSize\":5000,\"maxSize\":100}]}");
 expect(flipped.rules.size()==1&&flipped.rules[0].minSizeKb==100&&flipped.rules[0].maxSizeKb==5000,"inverted size bounds are swapped on load");
 std::wstring emoji=std::wstring(59,L'a')+std::wstring(1,0xD83C)+std::wstring(1,0xDF00)+L"tail";auto cut=CategoryFolder(emoji,L"X");
 expect(cut.size()==59&&cut.back()!=0xD83C,"a category name is never cut in the middle of a surrogate pair");
 expect(ArchiveIntervalSeconds(0)==0&&ArchiveIntervalSeconds(1)==3600&&ArchiveIntervalSeconds(2)==86400&&ArchiveIntervalSeconds(9)==0,"archive intervals map to the three modes");
 expect(!ArchiveDue(0,0,1000)&&ArchiveDue(1,0,1000)&&!ArchiveDue(1,900,1000)&&ArchiveDue(1,0,3600)&&!ArchiveDue(2,100,86499)&&ArchiveDue(2,100,86500),"an archive run is due once its interval has passed");
 expect(ClampArchiveMode(-3)==0&&ClampArchiveMode(2)==2&&ClampArchiveMode(7)==0,"archive modes stay in range");
 expect(NowEpoch()>1700000000LL&&NowEpoch()<4102444800LL,"the archive clock is real epoch seconds, not a date stamp");
 expect(ArchiveDue(1,5000,4000)&&!ArchiveDue(1,0,0)&&!ArchiveDue(2,0,-5),"a rolled-back clock still runs and a broken clock never spins");
 std::vector<std::wstring> filedUn;auto filed=ArchivePlan({docRule},{(adir/L"a.pdf").wstring(),(adir/L"sub/x.pdf").wstring(),(adir/L"文档/old.pdf").wstring()},&filedUn,adir.wstring());
 expect(filed.size()==1&&filed[0].category==L"文档"&&filed[0].paths.size()==2&&filedUn.empty(),"files already in their category are not filed again");
 Zone autoZone;autoZone.id=NewId();autoZone.mappedFolder=adir.wstring();autoZone.autoArchive=2;autoZone.archiveAt=1234567890;Layout autoLayout{{autoZone}};auto autoBack=Deserialize(Serialize(autoLayout));
 expect(autoBack.zones.size()==1&&autoBack.zones[0].autoArchive==2&&autoBack.zones[0].archiveAt==1234567890,"auto archive settings roundtrip");
 auto autoLegacy=Deserialize("{\"version\":1,\"zones\":[{\"id\":\"a\",\"name\":\"n\",\"x\":0,\"y\":0,\"width\":280,\"height\":160,\"collapsed\":false,\"entries\":[]}]}");
 expect(autoLegacy.zones[0].autoArchive==0&&autoLegacy.zones[0].archiveAt==0,"legacy zones default to manual archiving");
 auto autoBogus=Deserialize("{\"version\":1,\"zones\":[{\"id\":\"a\",\"name\":\"n\",\"x\":0,\"y\":0,\"width\":280,\"height\":160,\"collapsed\":false,\"entries\":[],\"autoArchive\":41,\"archiveAt\":-9}]}");
 expect(autoBogus.zones[0].autoArchive==0&&autoBogus.zones[0].archiveAt==0,"absurd archive settings fall back to manual");
 auto relMap=Deserialize("{\"version\":1,\"zones\":[{\"id\":\"a\",\"name\":\"n\",\"x\":0,\"y\":0,\"width\":280,\"height\":160,\"collapsed\":false,\"mappedFolder\":\"Downloads\",\"autoArchive\":1,\"entries\":[]}]}");
 expect(relMap.zones[0].mappedFolder.empty(),"a relative mapped folder is refused before it can be resolved against the working directory");
 expect(DownloadName(L"https://ex.com/a/b/report%20final.pdf?v=2")==L"report final.pdf","a download name is decoded from the link tail");
 expect(DownloadName(L"https://ex.com/x/")==L"download"&&DownloadName(L"https://ex.com/")==L"download","a link without a file name falls back");
 expect(DownloadName(L"https://ex.com/../../windows/system32/evil.txt")==L"evil.txt","a download name cannot climb out of the target folder");
 expect(DownloadName(L"https://ex.com/con.txt")==L"con_.txt"&&DownloadName(L"https://ex.com/nul")==L"nul_","a reserved download name gets a prefix-free escape");
 expect(DownloadName(L"https://ex.com/blob/9f2c",L"application/zip")==L"9f2c.zip","a missing extension is taken from the content type");
 expect(ExtFromContentType(L"Image/PNG; charset=x")==L"png"&&ExtFromContentType(L"application/x-unknown").empty(),"content types map only to known extensions");
 expect(IsHttpUrl(L"https://ex.com/a")&&IsHttpUrl(L"http://ex.com/a")&&!IsHttpUrl(L"file://C:/x")&&!IsHttpUrl(L"javascript:alert(1)")&&!IsHttpUrl(L"ftp://ex.com/a"),"only http and https links are downloadable");
 auto ddir=std::filesystem::temp_directory_path()/NewId();std::filesystem::create_directories(ddir);
 auto dcancel=std::make_shared<std::atomic<bool>>(false);
 auto noop=[](long long,long long,std::wstring const&){};
 auto dres=shell::DownloadFile(L"http://127.0.0.1:1/nothing.bin",ddir.wstring(),dcancel,noop,1024*1024);
 bool parts=false;for(auto const& e:std::filesystem::directory_iterator(ddir))if(e.path().wstring().ends_with(L".guodesk-part"))parts=true;
 expect(dres.path.empty()&&!parts,"a failed download leaves no partial file behind");
 dres=shell::DownloadFile(L"file:///C:/windows/win.ini",ddir.wstring(),dcancel,noop,1024*1024);
 expect(dres.path.empty()&&dres.status==0,"a non-http link is refused before any socket is opened");
 expect(ClampStackGrid(-1)==0&&ClampStackGrid(3)==3&&ClampStackGrid(9)==0&&StackCells(0)==1&&StackCells(1)==9&&StackCells(2)==16&&StackCells(3)==25&&StackCells(7)==1,"pile grid modes map to 1/9/16/25 cells");
 Zone pgZone;pgZone.id=NewId();pgZone.stackGrid=2;Layout pgLayout{{pgZone}};auto pgBack=Deserialize(Serialize(pgLayout));
 expect(pgBack.zones[0].stackGrid==2,"pile grid roundtrips");
 auto pgLegacy=Deserialize("{\"version\":1,\"zones\":[{\"id\":\"a\",\"name\":\"n\",\"x\":0,\"y\":0,\"width\":280,\"height\":160,\"collapsed\":false,\"entries\":[]}]}");
 auto pgBogus=Deserialize("{\"version\":1,\"zones\":[{\"id\":\"a\",\"name\":\"n\",\"x\":0,\"y\":0,\"width\":280,\"height\":160,\"collapsed\":false,\"entries\":[],\"stackGrid\":77}]}");
 expect(pgLegacy.zones[0].stackGrid==0&&pgBogus.zones[0].stackGrid==0,"pile grid defaults and clamps on load");
 std::filesystem::remove_all(ddir);
 std::filesystem::remove_all(adir);
 bool invalid=false;try{Deserialize("{\"version\":99,\"zones\":[]}");}catch(...){invalid=true;}expect(invalid,"unsupported version rejected");
 z.x=-5000;z.y=9000;z.width=440;z.height=360;Clamp(z,RECT{0,0,1920,1080});expect(z.x==0 && z.y==720,"offscreen position corrected");z.width=800;z.height=600;Clamp(z,RECT{0,0,200,120});expect(z.width==200&&z.height==120,"small work area bounded");Clamp(z,RECT{-1920,0,0,1080});expect(z.x<0,"negative monitor coordinates");
 auto temp=std::filesystem::temp_directory_path()/NewId();Store store(temp);std::wstring warning;auto initial=store.Load(warning);expect(initial.zones.size()==1,"first run default zone");store.Save(l);auto newer=l;newer.zones[0].name=L"new";store.Save(newer);expect(store.Load(warning).zones[0].name==L"new","atomic save latest");{std::ofstream corrupt(temp/L"layout.json");corrupt<<"broken";}auto recovered=store.Load(warning);expect(recovered.zones[0].name==z.name,"backup recovery");bool preserved=false;for(auto const& f:std::filesystem::directory_iterator(temp))if(f.path().filename().wstring().starts_with(L"layout.corrupt."))preserved=true;expect(preserved,"corrupt original preserved");std::filesystem::remove_all(temp);
 Widgets w;AddTodo(w,L"  买牛奶  ");AddTodo(w,L"写周报");expect(w.todos.size()==2&&w.todos[0].text==L"买牛奶"&&w.todos[1].text==L"写周报","todo add trims");expect(!AddTodo(w,L"   "),"empty todo rejected");ToggleTodo(w,w.todos[1].id);expect(w.todos[1].done,"todo toggle");ToggleTodo(w,w.todos[1].id);expect(!w.todos[1].done,"todo untoggle");
 w.noteText=L"便签：中文 内容\n第二行";w.noteVisible=true;w.todoVisible=true;w.noteX=15;w.noteY=25;w.noteW=333;w.noteH=222;w.todoX=44;w.todoY=55;w.todoW=266;w.todoH=333;RemoveTodo(w,w.todos[0].id);expect(w.todos.size()==1,"todo remove");
 auto wr=Deserialize(Serialize(l));expect(wr.widgets.todos.empty()&&!wr.widgets.noteVisible,"default widgets empty");l.widgets=w;auto wr2=Deserialize(Serialize(l));expect(wr2.widgets.noteText==w.noteText&&wr2.widgets.noteVisible&&wr2.widgets.todoVisible&&wr2.widgets.todos.size()==1&&wr2.widgets.todos[0].text==L"写周报"&&wr2.widgets.noteW==333&&wr2.widgets.todoH==333,"widgets roundtrip");
 auto legacyW=Deserialize("{\"version\":1,\"zones\":[]}");expect(legacyW.widgets.todos.empty()&&!legacyW.widgets.noteVisible&&legacyW.widgets.noteW==300&&legacyW.widgets.todoW==300,"legacy missing widgets defaults");
 i18n::SetLanguage(L"zh-CN");expect(i18n::Tr(L"设置")==L"设置","tr zh passthrough");
 i18n::SetLanguage(L"en-US");expect(i18n::Tr(L"设置")==L"Settings"&&i18n::Tr(L"不存在的键")==L"不存在的键","tr en lookup with fallback");
 expect(i18n::TrF(L"应用整理（添加 {0} 个引用）",{L"3"})==L"Apply tidy (adds 3 references)","trf formats placeholder");
 expect(i18n::Fmt(L"{1}+{0}",{L"A",L"B"})==L"B+A"&&i18n::Fmt(L"a {0} b {9} c",{L"X"})==L"a X b {9} c","fmt reorder and unknown index");
 Layout langL;langL.settings.language=L"en-US";auto langR=Deserialize(Serialize(langL));expect(langR.settings.language==L"en-US","language roundtrip");
 expect(Deserialize("{\"version\":1,\"zones\":[]}").settings.language.empty(),"legacy missing language tolerated");
 Hotkey hk;expect(ParseHotkey(L"Ctrl+Alt+G",hk)&&hk.mods==(MOD_CONTROL|MOD_ALT)&&hk.vk==L'G',"parse hotkey basic");
 expect(ParseHotkey(L"Win+Z",hk)&&hk.mods==MOD_WIN&&hk.vk==L'Z',"parse hotkey win");
 expect(ParseHotkey(L"ctrl + f5",hk)&&hk.vk==VK_F5&&HotkeyToString(hk)==L"Ctrl+F5","parse hotkey case space");
 Hotkey bad;expect(!ParseHotkey(L"Ctrl+G+X",bad)&&!ParseHotkey(L"Alt+",bad)&&!ParseHotkey(L"G",bad)&&!ParseHotkey(L"G+X",bad),"parse hotkey rejects");
 expect(ParseHotkey(L"  ",bad)&&bad.mods==0&&bad.vk==0&&HotkeyToString(bad).empty(),"empty hotkey disabled");
 expect(ParseHotkey(L"Ctrl+Alt+G",hk)&&HotkeyToString(hk)==L"Ctrl+Alt+G"&&ParseHotkey(L"Win+Z",hk)&&HotkeyToString(hk)==L"Win+Z","hotkey string roundtrip");
 auto sdir=std::filesystem::temp_directory_path()/NewId();std::filesystem::create_directories(sdir/L"子目录");
 {std::ofstream f(sdir/L"a2.txt");f<<std::string(100,'x');}{std::ofstream f(sdir/L"a10.txt");f<<"xxxxx";}{std::ofstream f(sdir/L"z.doc");f<<"x";}
 auto touch=[](std::filesystem::path const& p,unsigned long long daysAgo){FILETIME now{};GetSystemTimeAsFileTime(&now);unsigned long long t=(static_cast<unsigned long long>(now.dwHighDateTime)<<32)|now.dwLowDateTime;t-=daysAgo*864000000000ULL;FILETIME ft{static_cast<DWORD>(t&0xffffffffULL),static_cast<DWORD>(t>>32)};HANDLE f=CreateFileW(p.c_str(),FILE_WRITE_ATTRIBUTES,FILE_SHARE_READ|FILE_SHARE_WRITE|FILE_SHARE_DELETE,nullptr,OPEN_EXISTING,FILE_ATTRIBUTE_NORMAL,nullptr);if(f!=INVALID_HANDLE_VALUE){SetFileTime(f,nullptr,nullptr,&ft);CloseHandle(f);}};
 touch(sdir/L"z.doc",10);touch(sdir/L"a2.txt",1);touch(sdir/L"a10.txt",2);
 Zone sz;sz.id=NewId();
 AddEntry(sz,(sdir/L"bad\\none.xyz").wstring());AddEntry(sz,(sdir/L"a10.txt").wstring());AddEntry(sz,(sdir/L"z.doc").wstring());AddEntry(sz,(sdir/L"子目录").wstring());AddEntry(sz,(sdir/L"a2.txt").wstring());
 auto nm=[&](int i){return std::filesystem::path(sz.entries[i].path).filename().wstring();};
 SortEntries(sz,SortKey::Name,false);expect(nm(0)==L"子目录"&&nm(1)==L"a2.txt"&&nm(2)==L"a10.txt"&&nm(3)==L"z.doc"&&nm(4)==L"none.xyz","sort name natural dirs first bad last");
 SortEntries(sz,SortKey::Name,true);expect(nm(0)==L"子目录"&&nm(1)==L"z.doc"&&nm(2)==L"a10.txt"&&nm(3)==L"a2.txt"&&nm(4)==L"none.xyz","sort name desc keeps dirs first bad last");
 SortEntries(sz,SortKey::Size,false);expect(nm(0)==L"子目录"&&nm(1)==L"z.doc"&&nm(2)==L"a10.txt"&&nm(3)==L"a2.txt"&&nm(4)==L"none.xyz","sort size asc");
 SortEntries(sz,SortKey::Size,true);expect(nm(0)==L"子目录"&&nm(1)==L"a2.txt"&&nm(2)==L"a10.txt"&&nm(3)==L"z.doc"&&nm(4)==L"none.xyz","sort size desc bad last");
 SortEntries(sz,SortKey::Date,false);expect(nm(0)==L"子目录"&&nm(1)==L"z.doc"&&nm(2)==L"a10.txt"&&nm(3)==L"a2.txt","sort date asc");
 SortEntries(sz,SortKey::Date,true);expect(nm(1)==L"a2.txt"&&nm(2)==L"a10.txt"&&nm(3)==L"z.doc"&&nm(4)==L"none.xyz","sort date desc");
 SortEntries(sz,SortKey::Type,false);expect(nm(0)==L"子目录"&&nm(1)==L"z.doc"&&nm(2)==L"a2.txt"&&nm(3)==L"a10.txt"&&nm(4)==L"none.xyz","sort type asc");
 std::filesystem::remove_all(sdir);
 auto tdir=std::filesystem::temp_directory_path()/NewId();Store st(tdir);
 Zone qz;qz.id=NewId();qz.name=L"快照";Layout ql{{qz}};
 for(int i=0;i<25;++i){qz.name=L"快照"+std::to_wstring(i);ql.zones[0]=qz;st.Save(ql);}
 int snapCount=0;std::error_code sec;for(auto const& e:std::filesystem::directory_iterator(tdir/L"snapshots",sec))if(e.is_regular_file(sec))++snapCount;
 expect(snapCount>=1&&snapCount<=5,"snapshots throttled and capped");
 auto tdir2=std::filesystem::temp_directory_path()/NewId();Store st2(tdir2);st2.SetSnapshots(false);
 for(int i=0;i<25;++i)st2.Save(ql);
 expect(!std::filesystem::exists(tdir2/L"snapshots"),"snapshots disabled writes none");
 auto tdir3=std::filesystem::temp_directory_path()/NewId();Store st3(tdir3);
 Zone rz;rz.id=NewId();rz.name=L"快照恢复";Layout rl2{{rz}};st3.Save(rl2);
 {std::ofstream f(tdir3/L"layout.json",std::ios::binary);f<<"broken";}{std::ofstream f(tdir3/L"layout.backup.json",std::ios::binary);f<<"broken";}
 std::wstring warn3;auto rec=st3.Load(warn3);
 expect(rec.zones.size()==1&&rec.zones[0].name==L"快照恢复"&&!warn3.empty(),"load recovers from snapshot");
 std::filesystem::remove_all(tdir);std::filesystem::remove_all(tdir2);std::filesystem::remove_all(tdir3);
 l.zones[0].sortKey=L"date";l.zones[0].sortDescending=true;l.zones[0].tileSize=2;l.settings.hotkey=L"Win+Z";l.settings.snapshots=false;
 auto nr=Deserialize(Serialize(l));
 expect(nr.zones[0].sortKey==L"date"&&nr.zones[0].sortDescending&&nr.zones[0].tileSize==2&&nr.settings.hotkey==L"Win+Z"&&!nr.settings.snapshots,"v07 fields roundtrip");
 auto legacy7=Deserialize("{\"version\":1,\"zones\":[]}");
 expect(legacy7.settings.hotkey==L"Ctrl+Alt+G"&&legacy7.settings.snapshots,"legacy defaults for v07 settings");
 auto bad7=Deserialize("{\"version\":1,\"zones\":[{\"id\":\"a\",\"name\":\"n\",\"x\":0,\"y\":0,\"width\":280,\"height\":160,\"collapsed\":false,\"entries\":[],\"tileSize\":7,\"sortKey\":\"weird\"}],\"settings\":{\"hotkey\":\"Bad+\"}}");
 expect(bad7.zones[0].tileSize==1&&bad7.zones[0].sortKey.empty()&&bad7.settings.hotkey.empty(),"invalid v07 values fall back");
 long long dueToday=DueFromOffset(0),dueTomorrow=DueFromOffset(1),dueWeek=DueFromOffset(7);
 expect(dueToday>0&&dueTomorrow>dueToday&&dueWeek>dueTomorrow,"due offsets monotonic");
 expect(DueText(dueToday)==i18n::Tr(L"今天")&&DueText(dueTomorrow)==i18n::Tr(L"明天")&&!DueText(dueWeek).empty(),"due text formats");
 expect(DueReached(dueToday)&&!DueReached(dueTomorrow)&&!DueReached(dueWeek)&&!DueReached(0),"due reached semantics");
 auto tid=w.todos[0].id;SetTodoDue(w,tid,dueToday);expect(w.todos[0].due==dueToday,"set todo due");
 w.todos[0].reminded=true;SetTodoDue(w,tid,dueTomorrow);expect(w.todos[0].due==dueTomorrow&&!w.todos[0].reminded,"due change resets reminded");
 SetTodoDue(w,tid,dueWeek);w.todos[0].reminded=true;SetTodoDue(w,tid,dueWeek);expect(w.todos[0].reminded,"same due keeps reminded");
 l.widgets=w;auto dr2=Deserialize(Serialize(l));expect(dr2.widgets.todos[0].due==dueWeek&&dr2.widgets.todos[0].reminded,"todo due roundtrip");
 Widgets np;ActiveNote(np)->text=L"第一页";AddNotePage(np);ActiveNote(np)->text=L"第二页";AddNotePage(np);ActiveNote(np)->text=L"第三页";
 expect(np.pages.size()==3&&np.notePage==2&&np.pages[0].text==L"第一页"&&np.pages[2].text==L"第三页","note pages add");
 RemoveNotePage(np);expect(np.pages.size()==2&&np.notePage==1&&np.pages[1].text==L"第二页","note page remove");
 RemoveNotePage(np);RemoveNotePage(np);expect(np.pages.size()==1&&np.pages[0].text.empty()&&np.notePage==0,"note last page resets blank");
 Widgets np2;ActiveNote(np2)->text=L"甲";AddNotePage(np2);ActiveNote(np2)->text=L"乙";ActiveNote(np2)->color=4;np2.notePage=1;np2.noteTop=true;np2.clockVisible=true;np2.clockX=11;np2.clockY=22;np2.clockW=260;np2.clockH=140;
 Layout nl;nl.widgets=np2;auto nr8=Deserialize(Serialize(nl));
 expect(nr8.widgets.pages.size()==2&&nr8.widgets.pages[0].text==L"甲"&&nr8.widgets.pages[1].text==L"乙"&&nr8.widgets.pages[1].color==4&&nr8.widgets.noteTop&&nr8.widgets.notePage==1&&nr8.widgets.clockVisible&&nr8.widgets.clockW==260,"note pages and clock fields roundtrip");
 auto legacyNote=Deserialize("{\"version\":1,\"zones\":[],\"widgets\":{\"noteText\":\"\\u65E7\\u5185\\u5BB9\"}}");
 expect(legacyNote.widgets.pages.size()==1&&legacyNote.widgets.pages[0].text==std::wstring(L"\u65E7\u5185\u5BB9"),"legacy noteText migrates");
 l.zones[0].mon=L"\\\\.\\DISPLAY1";l.zones[0].mx=5;l.zones[0].my=7;l.settings.guideDone=true;
 auto mr8=Deserialize(Serialize(l));expect(mr8.zones[0].mon==L"\\\\.\\DISPLAY1"&&mr8.zones[0].mx==5&&mr8.zones[0].my==7&&mr8.settings.guideDone,"monitor anchor and guideDone roundtrip");
 auto areas=EnumMonitorAreas();expect(!areas.empty(),"monitor areas enumerated");
 std::wstring mon8{};int mx8=0,my8=0;RECT on8{100,100,500,400};Reanchor(on8,mon8,mx8,my8);
 expect(on8.left==100&&on8.top==100&&mon8.size()>0,"reanchor on-screen keeps position");
 bool named=false;for(auto const& a:areas)if(a.device==mon8){named=true;expect(mx8==on8.left-a.work.left&&my8==on8.top-a.work.top,"reanchor records work-area-relative origin");break;}
 expect(named,"reanchor names a monitor");
 std::wstring mon9{};int mx9=0,my9=0;RECT off9{-9000,-9000,-8700,-8800};Reanchor(off9,mon9,mx9,my9);
 bool inSome=false;for(auto const& a:areas)if(off9.left>=a.work.left&&off9.top>=a.work.top&&off9.right<=a.work.right&&off9.bottom<=a.work.bottom)inSome=true;
 expect(inSome&&mon9.size()>0,"reanchor off-screen clamps into work area");
 expect(IsMusicFile(L"C:\\m\\a.MP3")&&IsMusicFile(L"C:\\m\\b.flac")&&IsMusicFile(L"C:\\m\\c.m4a")&&IsMusicFile(L"C:\\m\\d.ogg")&&!IsMusicFile(L"C:\\m\\e.txt")&&!IsMusicFile(L"C:\\m\\f"),"music file extensions");
 auto mdir=std::filesystem::temp_directory_path()/NewId();std::filesystem::create_directories(mdir/L"专辑");
 {std::ofstream f(mdir/L"b.mp3");f<<"x";}{std::ofstream f(mdir/L"a.mp3");f<<"x";}{std::ofstream f(mdir/L"封面.txt");f<<"x";}
 auto pl=MusicPlaylist(mdir.wstring());expect(pl.size()==2&&std::filesystem::path(pl[0]).filename()==L"a.mp3"&&std::filesystem::path(pl[1]).filename()==L"b.mp3","music playlist scans and natural sorts");
 expect(MusicPlaylist((mdir/L"missing").wstring()).empty(),"music playlist missing folder empty");
 std::filesystem::remove_all(mdir);
 expect(SearchMatch(L"报告 Final.PDF",L"final")&&SearchMatch(L"报告",L"报")&&!SearchMatch(L"报告",L"简历")&&!SearchMatch(L"报告",L""),"search match contains");
 Layout sl;Zone z1;z1.id=NewId();z1.name=L"文档";AddEntry(z1,L"D:\\docs\\报告2026.pdf");Zone z2;z2.id=NewId();z2.name=L"图片";AddEntry(z2,L"D:\\pics\\cat.png");sl.zones={z1,z2};
 std::vector<SearchHit> hits;SearchZones(sl,L"报告",hits);expect(hits.size()==1&&hits[0].zone==L"文档"&&hits[0].name==L"报告2026.pdf","search zones finds by name");
 std::vector<SearchHit> hits2;SearchZones(sl,L"docs",hits2);expect(hits2.size()==1&&PathKey(hits2[0].path)==PathKey(L"D:\\docs\\报告2026.pdf"),"search zones finds by path");
 std::vector<SearchHit> hits3;SearchZones(sl,L"不存在的词",hits3);expect(hits3.empty(),"search zones no match empty");
 expect(WmoText(0)==L"晴"&&WmoText(95)==L"雷暴"&&WmoText(999)==L"—","wmo text mapping");
 bool emojiOk=true;for(int c=0;c<=99;++c)if(WmoEmoji(c).empty())emojiOk=false;expect(emojiOk,"wmo emoji covers all codes");
 auto wn=ParseWeatherJson(LR"({"current":{"temperature_2m":21.4,"relative_humidity_2m":63,"weather_code":2},"daily":{"time":["2026-10-01","2026-10-02","2026-10-03","2026-10-04"],"weather_code":[2,61,3,0],"temperature_2m_max":[25.1,22.0,20.5,26.2],"temperature_2m_min":[15.2,14.0,12.1,16.0]}})");
 expect(wn.valid&&wn.temp==21.4&&wn.humidity==63&&wn.code==2&&wn.hi==25.1&&wn.lo==15.2,"parse weather json");
 expect(wn.days.size()==3&&wn.days[0].code==61&&wn.days[0].date==20261002&&wn.days[2].hi==26.2,"parse weather daily");
 auto wnb=ParseWeatherJson(L"not json");expect(!wnb.valid,"parse weather garbage invalid");
 auto gp=ParseGeoJson(LR"({"results":[{"name":"上海","country":"中国","latitude":31.22,"longitude":121.45},{"name":"Shanghai","country":"","latitude":1.0,"longitude":2.0}]})");
 expect(gp.size()==2&&gp[0].name==L"上海"&&gp[0].lat==31.22&&gp[0].lon==121.45&&gp[1].country.empty(),"parse geocode json");
 expect(ParseGeoJson(L"broken").empty(),"parse geocode garbage");
 auto ip=ParseIpLocJson(LR"({"status":"success","city":"杭州","lat":30.27,"lon":120.15})");
 expect(ip.name==L"杭州"&&ip.lat==30.27&&ip.lon==120.15,"parse ip locate json");
 auto ipBad=ParseIpLocJson(LR"({"status":"fail"})");expect(ipBad.name.empty()&&ipBad.lat==0&&ipBad.lon==0,"parse ip locate rejected");
 l.widgets.musicVisible=true;l.widgets.weatherVisible=true;l.widgets.musicX=5;l.widgets.musicY=6;l.widgets.musicW=280;l.widgets.musicH=380;l.widgets.weatherX=7;l.widgets.weatherY=8;l.widgets.weatherW=250;l.widgets.weatherH=340;l.widgets.searchX=9;l.widgets.searchY=10;l.widgets.musicFolder=L"D:\\音乐";l.widgets.musicIndex=2;l.widgets.musicVol=80;l.widgets.weatherCity=L"上海";l.widgets.weatherLat=31.22;l.widgets.weatherLon=121.45;l.widgets.musicMon=L"\\\\.\\DISPLAY1";l.widgets.musicMX=3;l.widgets.musicMY=4;l.widgets.weatherMon=L"\\\\.\\DISPLAY2";l.widgets.weatherMX=1;l.widgets.weatherMY=2;l.widgets.searchMon=L"\\\\.\\DISPLAY1";l.widgets.searchMX=6;l.widgets.searchMY=8;l.settings.hotkeySearch=L"Ctrl+Alt+F";
 auto r9=Deserialize(Serialize(l));
 expect(r9.widgets.musicVisible&&r9.widgets.weatherVisible&&r9.widgets.musicX==5&&r9.widgets.musicW==280&&r9.widgets.weatherX==7&&r9.widgets.weatherW==250&&r9.widgets.searchX==9&&r9.widgets.searchY==10&&r9.widgets.musicFolder==L"D:\\音乐"&&r9.widgets.musicIndex==2&&r9.widgets.musicVol==80&&r9.widgets.weatherCity==L"上海"&&r9.widgets.weatherLat==31.22&&r9.widgets.weatherLon==121.45&&r9.widgets.musicMon==L"\\\\.\\DISPLAY1"&&r9.widgets.musicMX==3&&r9.widgets.weatherMX==1&&r9.widgets.searchMX==6&&r9.settings.hotkeySearch==L"Ctrl+Alt+F","v09 fields roundtrip");
 auto legacy9=Deserialize("{\"version\":1,\"zones\":[]}");
 expect(!legacy9.widgets.musicVisible&&!legacy9.widgets.weatherVisible&&legacy9.widgets.weatherLat==999&&legacy9.widgets.weatherLon==999&&legacy9.widgets.musicVol==65&&legacy9.settings.hotkeySearch.empty(),"legacy defaults for v09 fields");
 auto clamped9=Deserialize("{\"version\":1,\"zones\":[],\"widgets\":{\"musicW\":100,\"musicH\":50,\"weatherW\":10,\"weatherH\":10,\"musicVol\":250,\"musicIndex\":-5,\"weatherLat\":5000,\"weatherLon\":-5000}}");
 expect(clamped9.widgets.musicW==240&&clamped9.widgets.musicH==300&&clamped9.widgets.weatherW==220&&clamped9.widgets.weatherH==280&&clamped9.widgets.musicVol==100&&clamped9.widgets.musicIndex==0&&clamped9.widgets.weatherLat==999&&clamped9.widgets.weatherLon==999,"v09 out-of-range values clamped");
 Hotkey hs;expect(ParseHotkey(L"Ctrl+Alt+F",hs)&&HotkeyToString(hs)==L"Ctrl+Alt+F","parse search hotkey");
 Zone kz;kz.id=NewId();AddEntry(kz,L"D:\\s\\a.txt");AddEntry(kz,L"D:\\s\\b.txt");AddEntry(kz,L"D:\\s\\c.txt");
 auto s1=CreateStack(kz);expect(!s1.empty()&&kz.stacks.size()==1,"stack create");
 expect(!NewStackName(kz).empty(),"stack default name non-empty");
 auto s2=CreateStack(kz);expect(kz.stacks.size()==2&&kz.stacks[0].name!=kz.stacks[1].name,"stack names unique");
 AssignStack(kz,kz.entries[0].id,s1);AssignStack(kz,kz.entries[1].id,s1);
 expect(StackCount(kz,s1)==2&&StackCount(kz,s2)==0&&StackCount(kz,L"nope")==0,"stack count");
 DissolveStack(kz,s1);expect(kz.stacks.size()==1&&kz.entries[0].stack.empty()&&kz.entries[1].stack.empty(),"stack dissolve clears entries");
 Zone fz;fz.id=NewId();AddEntry(fz,L"D:\\m\\x.txt");AddEntry(fz,L"D:\\m\\y.txt");
 Zone tz2;tz2.id=NewId();AddEntry(tz2,L"D:\\m\\x.txt");
 Layout ml;ml.zones={fz,tz2};auto msid=CreateStack(ml.zones[0]);AssignStack(ml.zones[0],ml.zones[0].entries[0].id,msid);AssignStack(ml.zones[0],ml.zones[0].entries[1].id,msid);
 expect(MoveStack(ml,msid,ml.zones[0].id,ml.zones[1].id)==1,"move stack dedupes existing");
 expect(ml.zones[0].entries.empty()&&ml.zones[1].entries.size()==2&&ml.zones[1].entries[1].stack==msid,"moved entry keeps stack");
 expect(MoveStack(ml,msid,ml.zones[1].id,ml.zones[1].id)==0,"move stack same zone no-op");
 Zone gz;gz.id=NewId();gz.name=L"组A";gz.capsule=true;AddEntry(gz,L"D:\\g\\one.txt");
 auto gid=CreateStack(gz);AssignStack(gz,gz.entries[0].id,gid);
 gz.group=L"group-1";Zone gz2;gz2.id=NewId();gz2.name=L"组B";gz2.group=L"group-1";gz2.groupTab=1;
 Layout gl;gl.zones={gz,gz2};
 auto gr=Deserialize(Serialize(gl));
 expect(gr.zones[0].capsule&&gr.zones[0].stacks.size()==1&&gr.zones[0].entries[0].stack==gid,"v10 stack and capsule roundtrip");
 expect(gr.zones[1].group==L"group-1"&&gr.zones[1].groupTab==1,"v10 group roundtrip");
 expect(GroupMemberIds(gl,L"group-1").size()==2&&GroupMemberIds(gl,L"none").empty(),"group member ids");
 auto lg10=Deserialize("{\"version\":1,\"zones\":[{\"id\":\"z\",\"name\":\"n\",\"x\":0,\"y\":0,\"width\":280,\"height\":160,\"collapsed\":false,\"entries\":[]}]}");
 expect(lg10.zones[0].group.empty()&&!lg10.zones[0].capsule&&lg10.zones[0].stacks.empty(),"legacy zone without v10 fields defaults");
 auto dg10=Deserialize("{\"version\":1,\"zones\":[{\"id\":\"z1\",\"name\":\"n\",\"x\":0,\"y\":0,\"width\":280,\"height\":160,\"collapsed\":false,\"entries\":[],\"group\":\"g\",\"groupTab\":9,\"capsule\":true},{\"id\":\"z2\",\"name\":\"n2\",\"x\":0,\"y\":0,\"width\":280,\"height\":160,\"collapsed\":false,\"entries\":[],\"group\":\"g\"},{\"id\":\"z3\",\"name\":\"n3\",\"x\":0,\"y\":0,\"width\":280,\"height\":160,\"collapsed\":false,\"entries\":[],\"group\":\"g\"}]}");
 expect(dg10.zones[0].groupTab==2&&dg10.zones[0].capsule,"groupTab clamped to member range");
 auto sg10=Deserialize("{\"version\":1,\"zones\":[{\"id\":\"z1\",\"name\":\"n\",\"x\":0,\"y\":0,\"width\":280,\"height\":160,\"collapsed\":false,\"entries\":[],\"group\":\"solo\"}]}");
 expect(sg10.zones[0].group.empty(),"solo group dissolved on load");
 auto ds10=Deserialize("{\"version\":1,\"zones\":[{\"id\":\"z\",\"name\":\"n\",\"x\":0,\"y\":0,\"width\":280,\"height\":160,\"collapsed\":false,\"entries\":[{\"id\":\"e1\",\"path\":\"D:\\\\x.txt\",\"stack\":\"ghost\"}],\"stacks\":[{\"id\":\"s1\",\"name\":\"S\"}]}]}");
 expect(ds10.zones[0].entries[0].stack.empty(),"dangling entry stack cleared");
 auto vs10=Deserialize("{\"version\":1,\"zones\":[{\"id\":\"z\",\"name\":\"n\",\"x\":0,\"y\":0,\"width\":280,\"height\":160,\"collapsed\":false,\"entries\":[{\"id\":\"e1\",\"path\":\"D:\\\\x.txt\",\"stack\":\"s1\"}],\"stacks\":[{\"id\":\"s1\",\"name\":\"S\"}]}]}");
 expect(vs10.zones[0].entries[0].stack==L"s1","valid entry stack survives");
 webdav::UrlParts up;
 expect(webdav::ParseUrl(L"https://dav.example.com:5006/home",up)&&up.scheme==L"https"&&up.host==L"dav.example.com"&&up.port==5006&&up.path==L"/home","parse https url with port");
 webdav::UrlParts uh;
 expect(webdav::ParseUrl(L"http://example.com/dav",uh)&&uh.scheme==L"http"&&uh.host==L"example.com"&&uh.port==80&&uh.path==L"/dav","parse http url default port");
 expect(!webdav::ParseUrl(L"example.com/dav",up)&&!webdav::ParseUrl(L"ftp://example.com",up)&&!webdav::ParseUrl(L"",up),"parse url rejects bad input");
 expect(webdav::JoinUrl(L"https://dav.example.com/dav/",L"a.txt")==L"https://dav.example.com/dav/a.txt"&&webdav::JoinUrl(L"https://dav.example.com/dav",L"b.txt")==L"https://dav.example.com/dav/b.txt","join url normalizes slash");
 auto blob=webdav::ProtectSecret(L"密码 abc 123");
 expect(!blob.empty()&&blob!=L"密码 abc 123"&&webdav::UnprotectSecret(blob)==L"密码 abc 123","dpapi secret roundtrip");
 expect(webdav::UnprotectSecret(L"not-a-blob!!").empty(),"unprotect garbage returns empty");
 l.settings.performance=true;l.settings.syncUrl=L"https://dav.example.com:5006/home/";l.settings.syncUser=L"user@example.com";l.settings.syncPass=L"pass";l.settings.syncAuto=true;
 auto r11=Deserialize(Serialize(l));
 expect(r11.settings.performance&&r11.settings.syncUrl==L"https://dav.example.com:5006/home/"&&r11.settings.syncUser==L"user@example.com"&&r11.settings.syncPass==L"pass"&&r11.settings.syncAuto,"v11 sync fields roundtrip");
 auto bad11=Deserialize("{\"version\":1,\"zones\":[],\"settings\":{\"syncUrl\":\"ftp://example.com\",\"syncPass\":\"x\"}}");
 expect(bad11.settings.syncUrl.empty()&&bad11.settings.syncPass==L"x","non-http sync url rejected");
 auto lg11=Deserialize("{\"version\":1,\"zones\":[]}");
 expect(!lg11.settings.performance&&lg11.settings.syncUrl.empty()&&!lg11.settings.syncAuto,"legacy defaults for v11 fields");
 l.settings.syncInsecure=true;auto r381=Deserialize(Serialize(l));expect(r381.settings.syncInsecure,"sync insecure flag roundtrip");
 expect(!Deserialize("{\"version\":1,\"zones\":[],\"settings\":{\"syncAuto\":true}}").settings.syncInsecure,"sync insecure defaults off when absent");
 expect(IsDoubleCtrlHotkey(L"DoubleCtrl")&&!IsDoubleCtrlHotkey(L"Ctrl+Alt+G")&&!IsDoubleCtrlHotkey(L""),"double ctrl marker");
 Layout dcl;dcl.settings.hotkey=L"DoubleCtrl";auto dcr=Deserialize(Serialize(dcl));
 expect(dcr.settings.hotkey==L"DoubleCtrl","double ctrl hotkey roundtrip");
 auto dcl2=Deserialize("{\"version\":1,\"zones\":[],\"settings\":{\"hotkey\":\"DoubleCtrl\"}}");
 expect(dcl2.settings.hotkey==L"DoubleCtrl","double ctrl hotkey from json");
 expect(ParseHotkey(L"Win+F9",hk)&&HotkeyToString(hk)==L"Win+F9","parse hotkey win F9");
 expect(ParseHotkey(L"Ctrl+Shift+7",hk)&&hk.vk==L'7'&&HotkeyToString(hk)==L"Ctrl+Shift+7","parse hotkey digit");
 Widgets sw;AddTodo(sw,L"买牛奶");AddTodo(sw,L"写周报");ToggleTodo(sw,sw.todos[0].id);
 sw.pages.push_back({L"会议记录\n细节",0});sw.pages.push_back({L"   ",0});
 Layout swl;swl.widgets=sw;
 std::vector<SearchHit> wh;SearchWidgets(swl,L"牛奶",wh);
 expect(wh.empty(),"search widgets skips done todo");
 std::vector<SearchHit> wh2;SearchWidgets(swl,L"周报",wh2);
 expect(wh2.size()==1&&wh2[0].kind==L"todo"&&wh2[0].name==L"写周报"&&wh2[0].zone.empty(),"search widgets finds todo");
 std::vector<SearchHit> wh3;SearchWidgets(swl,L"会议",wh3);
 expect(wh3.size()==1&&wh3[0].kind==L"note"&&wh3[0].name==L"会议记录","search widgets finds note first line");
 std::vector<SearchHit> wh4;SearchWidgets(swl,L"",wh4);
 expect(wh4.empty(),"search widgets empty query");
 std::vector<SearchHit> wh5;SearchWidgets(swl,L"不存在的词",wh5);
 expect(wh5.empty(),"search widgets no match");
 expect(!KnownFolder(L"downloads").empty()&&!KnownFolder(L"documents").empty()&&!KnownFolder(L"pictures").empty()&&!KnownFolder(L"music").empty()&&!KnownFolder(L"videos").empty(),"known folders resolve");
 expect(KnownFolder(L"bogus").empty()&&KnownFolder(L"").empty(),"known folder unknown tag empty");
 auto tpls=BuiltInTemplates();
 expect(tpls.size()==3&&tpls[0].id==L"office"&&tpls[1].id==L"media"&&tpls[2].id==L"minimal","three built-in templates");
 bool tplShape=true;for(auto const& t:tpls)for(auto const& tz:t.zones){if(tz.name.empty()||tz.folderTag.empty())tplShape=false;if(tz.rx<0||tz.ry<0||tz.rw<=0||tz.rh<=0||tz.rx+tz.rw>1000||tz.ry+tz.rh>1000)tplShape=false;}
 expect(tplShape,"template zones named and within work area");
 RECT work{0,0,1920,1080};
 int expected=0;for(auto const& tz:tpls[0].zones)if(!KnownFolder(tz.folderTag).empty())++expected;
 Layout tplL;int n1=ApplyTemplate(tplL,tpls[0],work);
 expect(n1==expected&&static_cast<int>(tplL.zones.size())==expected,"apply office template adds zones");
 bool mapped=true,inWork=true;for(auto const& zz:tplL.zones){if(zz.mappedFolder.empty())mapped=false;if(zz.x<0||zz.y<0||zz.width<200||zz.height<140||zz.x+zz.width>1920||zz.y+zz.height>1080)inWork=false;}
 expect(mapped,"template zones carry mapped folder");
 expect(inWork,"template zone rects inside work area");
 expect(ApplyTemplate(tplL,tpls[0],work)==0,"apply template twice is idempotent");
 expect(ApplyTemplate(tplL,tpls[1],work)==2&&static_cast<int>(tplL.zones.size())==expected+2,"partial overlap adds only missing");
 expect(ApplyTemplate(tplL,tpls[2],work)==0,"fully overlapping template adds nothing");
 Layout qkL;
 expect(AddQuickZone(qkL,L"downloads",work)==1&&AddQuickZone(qkL,L"downloads",work)==0,"quick zone adds once");
 expect(!qkL.zones.empty()&&qkL.zones[0].mappedFolder==KnownFolder(L"downloads"),"quick zone maps known folder");
 std::string tjson=Serialize(tplL);Layout tback=Deserialize(tjson);
 expect(tback.zones.size()==tplL.zones.size()&&tback.zones[0].mappedFolder==tplL.zones[0].mappedFolder,"template zones serialize roundtrip");
 auto bdir=std::filesystem::temp_directory_path()/NewId();std::filesystem::create_directories(bdir/L"sub1"/L"inner");std::filesystem::create_directories(bdir/L"other");std::ofstream(bdir/L"a.txt");std::ofstream(bdir/L"desktop.ini");
 auto root=bdir.wstring(),inner=(bdir/L"sub1"/L"inner").wstring(),sub1=(bdir/L"sub1").wstring(),outside=(bdir/L"other").wstring(),elsewhere=(std::filesystem::temp_directory_path()/NewId()).wstring();
 auto listed=ListMapped(root);expect(listed.size()==3,"list mapped includes folders and files");expect(PathKey(listed[0].path)==PathKey(outside)&&PathKey(listed[1].path)==PathKey(sub1),"list mapped dirs first sorted");expect(listed[2].stack.empty(),"list mapped entries bare");
 ListMapped(root+L"\\missing");expect(ListMapped(root+L"\\missing").empty(),"list mapped missing folder empty");expect(ListMapped(L"").empty(),"list mapped empty root empty");
 expect(UnderRoot(root,inner),"under root nested");expect(UnderRoot(root,sub1),"under root direct");expect(!UnderRoot(root,root),"root not under itself");expect(!UnderRoot(root,(bdir.parent_path()/L"unrelated").wstring()),"sibling folder outside root");expect(UnderRoot(root,inner+L"\\.."),"inside via dotdot");expect(!UnderRoot(root,L""),"empty path not under root");expect(!UnderRoot(L"",inner),"empty root has no children");
 auto big=std::wstring(root);for(auto& c:big)if(c>=L'A'&&c<=L'Z')c=c-L'A'+L'a';
 auto lowered=std::wstring(inner);for(auto& c:lowered)if(c>=L'A'&&c<=L'Z')c=c-L'A'+L'a';
 expect(UnderRoot(big,lowered),"case insensitive comparison");expect(UnderRoot(root,lowered),"mixed case child under original root");
 auto chain=Crumbs(root,inner);expect(chain.size()==3,"crumbs chain per level");expect(PathKey(chain.front())==PathKey(root)&&PathKey(chain.back())==PathKey(inner),"crumbs endpoints exact");expect(PathKey(chain[1])==PathKey(sub1),"crumbs middle level");
 expect(Crumbs(root,L"").size()==1&&PathKey(Crumbs(root,L"").front())==PathKey(root),"crumbs empty current is root only");expect(Crumbs(root,elsewhere).size()==1,"crumbs outside is root only");
 expect(PathKey(CrumbParent(root,inner))==PathKey(sub1),"crumb parent of inner");expect(PathKey(CrumbParent(root,sub1))==PathKey(root),"crumb parent of first level");expect(CrumbParent(root,root).empty()&&CrumbParent(root,L"").empty(),"crumb parent at root empty");expect(CrumbParent(root,elsewhere).empty(),"crumb parent outside empty");

 Zone bz;bz.id=NewId();bz.browseInPlace=false;Layout bl{{bz}};auto bback=Deserialize(Serialize(bl));expect(!bback.zones[0].browseInPlace,"browseInPlace false roundtrip");
 Zone bz2;bz2.id=NewId();Layout bl2{{bz2}};expect(Deserialize(Serialize(bl2)).zones[0].browseInPlace,"browseInPlace default true roundtrip");
 Zone bx;bx.id=NewId();bx.mappedFolder=root;bx.browseFolder=sub1;Layout fl{{bx}};auto fback=Deserialize(Serialize(fl));expect(fback.zones[0].browseFolder==sub1,"browseFolder roundtrip");
 Zone bx2=bx;bx2.browseFolder=elsewhere;Layout fl2{{bx2}};expect(Deserialize(Serialize(fl2)).zones[0].browseFolder.empty(),"browseFolder outside root dropped");
 Zone bx3=bx;bx3.mappedFolder.clear();Layout fl3{{bx3}};expect(Deserialize(Serialize(fl3)).zones[0].browseFolder.empty(),"browseFolder without mapping dropped");
 Zone bx4=bx;bx4.browseInPlace=false;Layout fl4{{bx4}};expect(Deserialize(Serialize(fl4)).zones[0].browseFolder.empty(),"browseFolder with browsing off dropped");
 expect(Deserialize("{\"version\":1,\"zones\":[{\"id\":\"a\",\"name\":\"n\",\"x\":0,\"y\":0,\"width\":280,\"height\":160,\"collapsed\":false,\"entries\":[]}]}").zones[0].browseInPlace,"legacy zone defaults browseInPlace true");
 std::filesystem::remove_all(bdir);
 Widgets capW;
 expect(AppendNote(capW,L"  hello\r\nworld \n"),"append note accepts trimmed text");
 expect(capW.pages.size()==1&&capW.pages[0].text==L"hello\nworld","append note normalizes newlines");
 expect(!AppendNote(capW,L"  \t\r\n"),"append blank rejected");
 expect(capW.pages.size()==1&&capW.pages[0].text==L"hello\nworld","append blank changes nothing");
 expect(AppendNote(capW,L"third"),"append second capture");
 expect(capW.pages[0].text==L"hello\nworld\nthird","append note adds newline separated");
 AddNotePage(capW);expect(capW.notePage==1&&AppendNote(capW,L"page two"),"append targets active page");
 expect(capW.pages[0].text==L"hello\nworld\nthird"&&capW.pages[1].text==L"page two","append writes only active page");
 Layout capL;capL.settings.hotkeyCapture=L"Ctrl+Alt+K";auto capR=Deserialize(Serialize(capL));expect(capR.settings.hotkeyCapture==L"Ctrl+Alt+K","capture hotkey roundtrip");
 auto capEmpty=Deserialize(Serialize(Layout{}));expect(capEmpty.settings.hotkeyCapture.empty(),"capture hotkey default empty");
 auto capBad=Deserialize("{\"version\":1,\"zones\":[],\"settings\":{\"hotkeyCapture\":\"Bad+\"}}");expect(capBad.settings.hotkeyCapture.empty(),"invalid capture hotkey dropped");
 Layout fontL;fontL.settings.textSize=2;fontL.settings.clockStyle=L"analog";auto fontR=Deserialize(Serialize(fontL));expect(fontR.settings.textSize==2&&fontR.settings.clockStyle==L"analog","textSize+clockStyle roundtrip");
 auto fontDef=Deserialize(Serialize(Layout{}));expect(fontDef.settings.textSize==1&&fontDef.settings.clockStyle.empty(),"font defaults standard digital");
 auto fontBad=Deserialize("{\"version\":1,\"zones\":[],\"settings\":{\"textSize\":7,\"clockStyle\":\"analogX\"}}");expect(fontBad.settings.textSize==1&&fontBad.settings.clockStyle.empty(),"invalid textSize/clockStyle dropped");
 auto nearF=[](double a,double b){return std::fabs(a-b)<0.001;};
 expect(nearF(ScaledFont(0,20),17)&&nearF(ScaledFont(1,20),20)&&nearF(ScaledFont(2,20),24),"scaled font three steps");
 expect(nearF(ScaledFont(-3,20),17)&&nearF(ScaledFont(9,20),24),"scaled font clamps out-of-range");
 Layout evL;evL.settings.everything=false;auto evR=Deserialize(Serialize(evL));expect(!evR.settings.everything,"everything toggle roundtrip");
 auto evDef=Deserialize(Serialize(Layout{}));expect(evDef.settings.everything,"everything enabled by default");
 auto evOld=Deserialize("{\"version\":1,\"zones\":[],\"settings\":{}}");expect(evOld.settings.everything,"legacy layout keeps everything default");
 expect(ev::ShouldQuery(L"ab",true)&&!ev::ShouldQuery(L"a",true)&&!ev::ShouldQuery(L"abc",false),"everything query gate");
 std::vector<SearchHit> mh={{L"C:\\x\\a.txt",L"a.txt",L"资料",L""}};
 std::vector<SearchHit> mf={{L"C:\\X\\a.txt",L"a.txt",L"",L"file"},{L"D:\\docs\\b.docx",L"b.docx",L"",L"file"},{L"",L"x",L"",L"file"}};
 auto added=ev::MergeHits(mh,mf);
 expect(mh.size()==2&&added.size()==1&&added[0].path==L"D:\\docs\\b.docx"&&added[0].kind==L"file","everything merge dedupes case-insensitively");
 Zone cz;cz.id=L"c1";cz.color=8;Layout cl{{cz}};expect(Deserialize(Serialize(cl)).zones[0].color==8,"zone color roundtrip");
 Zone cz0;cz0.id=L"c0";Layout cl0{{cz0}};expect(Deserialize(Serialize(cl0)).zones[0].color==0,"uncolored zone stays uncolored");
 auto cOld=Deserialize("{\"version\":1,\"zones\":[{\"id\":\"a\",\"name\":\"n\",\"x\":0,\"y\":0,\"width\":280,\"height\":160,\"collapsed\":false,\"entries\":[]}],\"settings\":{}}");expect(cOld.zones[0].color==0,"legacy zone has no color");
 auto cBad=Deserialize("{\"version\":1,\"zones\":[{\"id\":\"a\",\"name\":\"n\",\"x\":0,\"y\":0,\"width\":280,\"height\":160,\"collapsed\":false,\"entries\":[],\"color\":99},{\"id\":\"b\",\"name\":\"m\",\"x\":0,\"y\":0,\"width\":280,\"height\":160,\"collapsed\":false,\"entries\":[],\"color\":-3},{\"id\":\"c\",\"name\":\"o\",\"x\":0,\"y\":0,\"width\":280,\"height\":160,\"collapsed\":false,\"entries\":[],\"color\":2.5}],\"settings\":{}}");expect(cBad.zones.size()==3&&cBad.zones[0].color==0&&cBad.zones[1].color==0&&cBad.zones[2].color==0,"invalid zone colors fall back");
 expect(ZoneColorCount()==8&&ZoneColorRGB(1)==0xE81123u&&ZoneColorRGB(8)==0xE3008Cu,"zone palette bounds");
 expect(ZoneColorRGB(0)==0u&&ZoneColorRGB(9)==0u&&ZoneColorRGB(-1)==0u,"zone palette out-of-range is none");
 Zone bgz1;bgz1.id=L"b1";bgz1.background=L"C:\\pics\\a.png";bgz1.dim=2;Layout bgl1{{bgz1}};auto bgback=Deserialize(Serialize(bgl1));expect(bgback.zones[0].background==L"C:\\pics\\a.png"&&bgback.zones[0].dim==2,"background and dim roundtrip");
 Zone bgz2;bgz2.id=L"b2";Layout bgl2{{bgz2}};expect(Deserialize(Serialize(bgl2)).zones[0].dim==1,"dim defaults to medium");
 auto bgBad=Deserialize("{\"version\":1,\"zones\":[{\"id\":\"a\",\"name\":\"n\",\"x\":0,\"y\":0,\"width\":280,\"height\":160,\"collapsed\":false,\"entries\":[],\"background\":\"C:\\\\a.txt\",\"dim\":7},{\"id\":\"b\",\"name\":\"m\",\"x\":0,\"y\":0,\"width\":280,\"height\":160,\"collapsed\":false,\"entries\":[],\"background\":\"C:\\\\p\\\\b.JPG\",\"dim\":-1},{\"id\":\"c\",\"name\":\"o\",\"x\":0,\"y\":0,\"width\":280,\"height\":160,\"collapsed\":false,\"entries\":[],\"background\":\"C:\\\\p\\\\c.webp\",\"dim\":0}],\"settings\":{}}");
 expect(bgBad.zones[0].background.empty()&&bgBad.zones[0].dim==1&&bgBad.zones[1].background==L"C:\\p\\b.JPG"&&bgBad.zones[1].dim==1&&bgBad.zones[2].background==L"C:\\p\\c.webp"&&bgBad.zones[2].dim==0,"invalid background/dim self-heal");
 expect(IsImagePath(L"a.png")&&IsImagePath(L"C:\\x\\b.webp")&&IsImagePath(L"x.TIFF"),"image path accepts pictures");
 expect(!IsImagePath(L"C:\\x\\b.txt")&&!IsImagePath(L"noext")&&!IsImagePath(L"C:\\a.b\\c")&&!IsImagePath(L"")&&!IsImagePath(L"x.jpegx"),"image path rejects others");
 Zone pnz1;pnz1.id=L"p1";pnz1.pins={L"C:\\Windows\\notepad.exe",L"D:\\docs"};Layout pnl1{{pnz1}};auto pnback=Deserialize(Serialize(pnl1));expect(pnback.zones[0].pins==std::vector<std::wstring>({L"C:\\Windows\\notepad.exe",L"D:\\docs"}),"pins roundtrip");
 auto pnLong="{\"version\":1,\"zones\":[{\"id\":\"a\",\"name\":\"n\",\"x\":0,\"y\":0,\"width\":280,\"height\":160,\"collapsed\":false,\"entries\":[],\"pins\":[\"C:\\\\"+std::string(300,'x')+"\",\"C:\\\\keep.exe\"]}]}";
 expect(Deserialize(pnLong).zones[0].pins==std::vector<std::wstring>({L"C:\\keep.exe"}),"oversized pin dropped");
 auto pnLegacy=Deserialize("{\"version\":1,\"zones\":[{\"id\":\"a\",\"name\":\"n\",\"x\":0,\"y\":0,\"width\":280,\"height\":160,\"collapsed\":false,\"entries\":[]}]}");expect(pnLegacy.zones[0].pins.empty(),"legacy zone has no pins");
 auto pnMixed=Deserialize("{\"version\":1,\"zones\":[{\"id\":\"a\",\"name\":\"n\",\"x\":0,\"y\":0,\"width\":280,\"height\":160,\"collapsed\":false,\"entries\":[],\"pins\":[\"ok\",5,\"\",\"ok\",\"C:\\\\dup\",\"C:\\\\DUP\\\\\"]}]}");expect(pnMixed.zones[0].pins==std::vector<std::wstring>({L"ok",L"C:\\dup"}),"pins drop junk and dedupe case-insensitively");
 std::string manyPins="{\"version\":1,\"zones\":[{\"id\":\"a\",\"name\":\"n\",\"x\":0,\"y\":0,\"width\":280,\"height\":160,\"collapsed\":false,\"entries\":[],\"pins\":[";for(int i=0;i<20;++i){manyPins+="\"C:\\\\pin"+std::to_string(i)+".exe\"";if(i<19)manyPins+=",";}manyPins+="]}]}";
 expect(Deserialize(manyPins).zones[0].pins.size()==12,"pins stay bounded to twelve");
 expect(ClampOpacityPercent(0)==20&&ClampOpacityPercent(-5)==20&&ClampOpacityPercent(75)==75&&ClampOpacityPercent(100)==100&&ClampOpacityPercent(150)==100,"opacity percent clamps to range");
 expect(NextOpacityStep(100)==80&&NextOpacityStep(80)==60&&NextOpacityStep(60)==40&&NextOpacityStep(40)==100,"opacity steps cycle down then reset");
 Zone opz;opz.id=L"o1";opz.opacity=60;Layout opl{{opz}};expect(Deserialize(Serialize(opl)).zones[0].opacity==60,"opacity roundtrip");
 expect(Deserialize("{\"version\":1,\"zones\":[{\"id\":\"a\",\"name\":\"n\",\"x\":0,\"y\":0,\"width\":280,\"height\":160,\"collapsed\":false,\"entries\":[],\"opacity\":150}]}").zones[0].opacity==100,"oversized opacity clamped on load");
 expect(pnLegacy.zones[0].opacity==100&&Deserialize("{\"version\":1,\"zones\":[{\"id\":\"a\",\"name\":\"n\",\"x\":0,\"y\":0,\"width\":280,\"height\":160,\"collapsed\":false,\"entries\":[],\"opacity\":\"high\"}]}").zones[0].opacity==100,"nonnumeric opacity falls back to full");
 expect(ClampExpandDir(-1)==0&&ClampExpandDir(2)==2&&ClampExpandDir(3)==3&&ClampExpandDir(9)==0,"expand direction clamps to four modes");
 expect(ClampMaxHeight(0)==0&&ClampMaxHeight(24)==0&&ClampMaxHeight(50)==50&&ClampMaxHeight(100)==100&&ClampMaxHeight(120)==100,"max height percent clamps or disables");
 expect(ZoneExpandedHeight(900,0,1000)==900&&ZoneExpandedHeight(900,50,1000)==500&&ZoneExpandedHeight(300,50,1000)==300&&ZoneExpandedHeight(900,100,1000)==900,"max height caps only oversized zones");
 expect(ZoneExpandedHeight(900,5,1000)==88&&ZoneExpandedHeight(900,50,0)==900,"tiny caps keep the bar and unknown work area disables the cap");
 expect(ZoneCapHeight(0,1032)==(1<<20)&&ZoneCapHeight(25,1032)==258&&ZoneCapHeight(4,2000)==88&&ZoneCapHeight(50,0)==(1<<20),"cap height converts percent with a bar floor");
 Zone cvz;cvz.id=L"c1";cvz.x=100;cvz.y=600;cvz.width=400;cvz.height=900;cvz.maxHeight=25;Clamp(cvz,RECT{0,0,1920,1032});expect(cvz.y==600&&cvz.height==900,"a capped zone is clamped by its rendered height and keeps its intent");
 Zone cbz;cbz.id=L"c2";cbz.x=100;cbz.y=1000;cbz.width=400;cbz.height=900;cbz.maxHeight=25;cbz.collapsed=true;Clamp(cbz,RECT{0,0,1920,1032});expect(cbz.y==944,"a collapsed bar keeps eighty-eight pixels on screen");
 expect(ZoneAnchorTop(100,300,88,1,0,1000)==100&&ZoneAnchorTop(100,300,88,2,0,1000)==312&&ZoneAnchorTop(100,300,88,3,0,1000)==206,"collapsing anchors top bottom or center by direction");
 expect(ZoneAnchorTop(100,88,300,2,0,1000)==0&&ZoneAnchorTop(500,88,300,3,0,1000)==394&&ZoneAnchorTop(100,88,300,1,0,1000)==100,"expanding keeps the anchored edge and stays on screen");
 expect(ZoneAnchorTop(800,150,300,0,0,1000)==650&&ZoneAnchorTop(100,100,300,0,0,1000)==100&&ZoneAnchorTop(100,100,1200,1,0,1000)==0,"auto direction flips upward only when it would overflow");
 Zone gmz;gmz.id=L"g1";gmz.expandDir=2;gmz.maxHeight=50;gmz.locked=true;Layout gml{{gmz}};auto gmr=Deserialize(Serialize(gml));expect(gmr.zones[0].expandDir==2&&gmr.zones[0].maxHeight==50&&gmr.zones[0].locked,"zone geometry settings roundtrip");
 auto gmLegacy=Deserialize("{\"version\":1,\"zones\":[{\"id\":\"a\",\"name\":\"n\",\"x\":0,\"y\":0,\"width\":280,\"height\":160,\"collapsed\":false,\"entries\":[]}]}");expect(gmLegacy.zones[0].expandDir==0&&gmLegacy.zones[0].maxHeight==0&&!gmLegacy.zones[0].locked,"legacy zone defaults to auto direction without lock");
 auto gmBad=Deserialize("{\"version\":1,\"zones\":[{\"id\":\"a\",\"name\":\"n\",\"x\":0,\"y\":0,\"width\":280,\"height\":160,\"collapsed\":false,\"entries\":[],\"expandDir\":9,\"maxHeight\":\"half\",\"locked\":\"yes\"}]}");expect(gmBad.zones[0].expandDir==0&&gmBad.zones[0].maxHeight==0&&!gmBad.zones[0].locked,"junk geometry values fall back to defaults");
 expect(std::wstring(ExpandDirName(2))==L"向上展开"&&std::wstring(ExpandDirName(7))==L"自动展开","direction names cover invalid input");
 expect(MediaTrackLine(L"  曲目 ",L" 歌手 ")==L"曲目 · 歌手"&&MediaTrackLine(L"",L"仅艺人")==L"仅艺人"&&MediaTrackLine(L"曲",L"  ")==L"曲"&&MediaTrackLine(L"  ",L"")==L"","media line trims and joins parts");
 expect(MediaTrackLine(std::wstring(200,L't'),L"a").size()==160,"media line capped at one sixty");
 expect(MediaTimeText(0,0)==L"0:00"&&MediaTimeText(65,0)==L"1:05"&&MediaTimeText(5,125)==L"0:05 / 2:05","media time formats position and span");
 expect(MediaTimeText(-9,-9)==L"0:00","media time clamps negatives");
 expect(MediaStatusKind(0)==0&&MediaStatusKind(4)==3&&MediaStatusKind(5)==2&&MediaStatusKind(3)==1&&MediaStatusKind(1)==1&&MediaStatusKind(9)==1,"media status kinds follow SDK enum (Playing=4 Paused=5 Stopped=3)");
 Widgets tkw,cdw;
 AddTodo(tkw,L"flag red");AddTodo(tkw,L"flag none");tkw.todos[0].flag=1;expect(tkw.todos[0].flag==1&&tkw.todos[1].flag==0,"todo flag defaults to none");
 Layout tkl;tkl.widgets=tkw;auto tkb=Deserialize(Serialize(tkl));expect(tkb.widgets.todos[0].flag==1&&tkb.widgets.todos[1].flag==0,"todo flag roundtrip");
 auto tkLegacy=Deserialize("{\"version\":1,\"zones\":[],\"widgets\":{\"todos\":[{\"id\":\"a\",\"text\":\"t\"}]}}");expect(tkLegacy.widgets.todos.size()==1&&tkLegacy.widgets.todos[0].flag==0,"legacy todo without flag defaults none");
 auto tkBad=Deserialize("{\"version\":1,\"zones\":[],\"widgets\":{\"todos\":[{\"id\":\"a\",\"text\":\"t\",\"flag\":7}]}}");expect(tkBad.widgets.todos[0].flag==0,"out of range flag self heals");
 expect(TodoFlagRGB(1)==0xE81123u&&TodoFlagRGB(2)==0xFFB900u&&TodoFlagRGB(3)==0x13A10Eu&&TodoFlagRGB(0)==0u&&TodoFlagRGB(9)==0u,"flag colors map with safe fallback");
 TodoItem tki1;tki1.done=true;TodoItem tki2;tki2.flag=2;expect(TodoMatchesFilter(tki1,0)&&TodoMatchesFilter(tki2,0)&&!TodoMatchesFilter(tki1,1)&&TodoMatchesFilter(tki2,1)&&TodoMatchesFilter(tki1,2)&&!TodoMatchesFilter(tki2,2),"filter kinds select done and pending");
 AddTodo(cdw,L"a");AddTodo(cdw,L"b");cdw.todos[0].done=true;expect(ClearDoneTodos(cdw)==1&&cdw.todos.size()==1&&cdw.todos[0].text==L"b","clear done removes only finished");expect(ClearDoneTodos(cdw)==0,"clear done on none is a no-op");
 expect(ShouldListApp(L"Notepad",L"C:\\Windows\\notepad.exe"),"normal shortcut is listed");
 expect(!ShouldListApp(L"",L"C:\\x.exe")&&!ShouldListApp(L"App",L""),"nameless or targetless shortcut is hidden");
 expect(!ShouldListApp(L"Uninstall GuoDesk",L"C:\\x\\unins000.exe"),"uninstaller shortcut is hidden");
 expect(!ShouldListApp(L"卸载工具",L"C:\\x.exe"),"chinese uninstaller shortcut is hidden");
 expect(AppMatches(L"Google Chrome",L"chro")&&AppMatches(L"Google Chrome",L"CHROME")&&AppMatches(L"Word",L"")&&!AppMatches(L"Word",L"edge"),"app filter is case insensitive substring");
 std::vector<AppShortcut> agv;agv.push_back({L"b",L"l1",L"t",L""});agv.push_back({L"A",L"l2",L"t",L""});SortAppsByName(agv);expect(agv[0].name==L"A"&&agv[1].name==L"b","app sort ignores case");
 Widgets agw;agw.appGridVisible=true;agw.appGridX=120;agw.appGridY=140;agw.appGridW=300;agw.appGridH=360;agw.appGridMon=L"MON1";agw.appGridMX=7;agw.appGridMY=9;Layout agl;agl.widgets=agw;auto agb=Deserialize(Serialize(agl));expect(agb.widgets.appGridVisible&&agb.widgets.appGridX==120&&agb.widgets.appGridY==140&&agb.widgets.appGridW==300&&agb.widgets.appGridH==360&&agb.widgets.appGridMon==L"MON1"&&agb.widgets.appGridMX==7&&agb.widgets.appGridMY==9,"app grid roundtrip");
 auto agLegacy=Deserialize("{\"version\":1,\"zones\":[],\"widgets\":{}}");expect(!agLegacy.widgets.appGridVisible&&agLegacy.widgets.appGridW==340&&agLegacy.widgets.appGridH==400,"legacy layout hides app grid with defaults");
 auto agSmall=Deserialize("{\"version\":1,\"zones\":[],\"widgets\":{\"appGridVisible\":true,\"appGridW\":10,\"appGridH\":10}}");expect(agSmall.widgets.appGridVisible&&agSmall.widgets.appGridW==260&&agSmall.widgets.appGridH==280,"tiny app grid self heals to minimum");
 UndoStack ua;expect(ua.Empty()&&ua.Count()==0&&ua.Limit()==20,"undo stack starts empty");
 UndoFrame ufr;expect(!ua.Pop(ufr),"undo pop on empty stack reports nothing");
 ua.Push(L"step1",Serialize(Layout{}));ua.Push(L"step2",Serialize(Layout{}));
 expect(ua.Count()==2&&ua.TopLabel()==L"step2"&&ua.Pop(ufr)&&ufr.label==L"step2","undo pops newest first");
 expect(ua.Count()==1&&ua.Pop(ufr)&&ufr.label==L"step1"&&ua.Empty(),"undo pops in reverse order");
 ua.Push(L"ignored",std::string{});expect(ua.Empty(),"undo ignores empty snapshots");
 UndoStack ub(3);for(int i=1;i<=5;++i)ub.Push(std::to_wstring(i),Serialize(Layout{}));
 expect(ub.Count()==3&&ub.TopLabel()==L"5","undo history stays bounded");
 expect(ub.Pop(ufr)&&ufr.label==L"5"&&ub.Pop(ufr)&&ufr.label==L"4"&&ub.Pop(ufr)&&ufr.label==L"3"&&ub.Empty(),"undo evicts oldest frames");
 UndoStack uc(0);uc.Push(L"a",Serialize(Layout{}));uc.Push(L"b",Serialize(Layout{}));expect(uc.Count()==1&&uc.TopLabel()==L"b","undo limit of zero falls back to one");
 uc.Push(L"c",Serialize(Layout{}));uc.Clear();expect(uc.Empty()&&uc.TopLabel().empty(),"undo clear drops history");
 Zone uz;uz.id=L"u1";uz.name=L"撤";Layout ul{{uz}};ul.settings.hotkeyUndo=L"Ctrl+Alt+Z";ul.settings.tabHover=false;
 UndoStack ud;ud.Push(L"delete",Serialize(ul));UndoFrame uf2;expect(ud.Pop(uf2)&&Deserialize(uf2.snapshot).zones.size()==1,"undo snapshot restores layout");
 Layout us;us.settings.hotkeyUndo=L"Ctrl+Alt+U";us.settings.tabHover=true;auto usBack=Deserialize(Serialize(us));expect(usBack.settings.hotkeyUndo==L"Ctrl+Alt+U"&&usBack.settings.tabHover,"undo hotkey and hover tab roundtrip");
 Layout usOff;usOff.settings.hotkeyUndo=L"";usOff.settings.tabHover=false;expect(Deserialize(Serialize(usOff)).settings.hotkeyUndo.empty()&&!Deserialize(Serialize(usOff)).settings.tabHover,"undo hotkey can be disabled");
 auto usLegacy=Deserialize("{\"version\":1,\"zones\":[],\"settings\":{}}");expect(usLegacy.settings.hotkeyUndo==L"Ctrl+Alt+U"&&usLegacy.settings.tabHover,"legacy config keeps undo defaults");
 auto usBad=Deserialize("{\"version\":1,\"zones\":[],\"settings\":{\"hotkeyUndo\":\"NotAKey!!\"}}");expect(usBad.settings.hotkeyUndo.empty(),"invalid undo hotkey dropped");
 Layout um;um.settings.memTrim=false;expect(!Deserialize(Serialize(um)).settings.memTrim,"mem trim can be disabled");
 auto umLegacy=Deserialize("{\"version\":1,\"zones\":[],\"settings\":{}}");expect(umLegacy.settings.memTrim,"legacy config keeps mem trim default on");
 std::wstring dragPath=L"C:\\a b.txt";auto hd=shell::MakeHdrop({dragPath});expect(hd.size()==sizeof(DROPFILES)+(dragPath.size()+1+1)*sizeof(wchar_t),"HDROP payload size and double terminator");auto* dfp=reinterpret_cast<DROPFILES*>(hd.data());expect(dfp->pFiles==static_cast<DWORD>(sizeof(DROPFILES))&&dfp->fWide,"HDROP wide header offset");expect(std::wstring(reinterpret_cast<wchar_t*>(hd.data()+sizeof(DROPFILES)))==dragPath,"HDROP path roundtrip");
 auto hdTwo=shell::MakeHdrop({L"C:\\x",L"D:\\y"});expect(hdTwo.size()==sizeof(DROPFILES)+(4+1+4+1+1)*sizeof(wchar_t),"HDROP multi-path terminator");
 expect(WeatherSkinCount()==7&&WeatherSkinForCode(0,false)==0&&WeatherSkinForCode(0,true)==1,"clear day and night use different skins");
 expect(WeatherSkinForCode(3,false)==2&&WeatherSkinForCode(63,false)==3&&WeatherSkinForCode(75,false)==4&&WeatherSkinForCode(86,false)==4&&WeatherSkinForCode(95,false)==5&&WeatherSkinForCode(45,false)==6,"weather codes map to cloud rain snow thunder fog");
 expect(WeatherSkinForCode(80,false)==3,"showers map to rain not snow");
 expect((WeatherSkinTop(0)&0xFFFFFF)==0x3A7BD3&&(WeatherSkinBottom(4)&0xFFFFFF)==0xE3EEF7&&WeatherSkinTop(99)==WeatherSkinTop(2),"skin palette bounds");
 auto wRain=ParseWeatherJson(L"{\"current\":{\"temperature_2m\":21.5,\"weather_code\":61,\"is_day\":0},\"daily\":{\"time\":[\"2026-10-03\",\"2026-10-04\"],\"weather_code\":[61,3],\"temperature_2m_max\":[24,22],\"temperature_2m_min\":[15,13]},\"hourly\":{\"time\":[\"2026-10-03T13:00\",\"2026-10-03T14:00\",\"2026-10-03T15:00\",\"2026-10-04T14:00\"],\"weather_code\":[61,63,3,0],\"temperature_2m\":[20,19,18,17]}}",2026100314LL);
 expect(wRain.valid&&!wRain.isDay,"is_day parsed as night");
 expect(wRain.hours.size()==3&&wRain.hours[0].key==2026100314LL&&wRain.hours[0].code==63,"hourly picks current hour onward");
 expect(wRain.hours[1].key==2026100315LL&&wRain.hours[1].temp==18&&wRain.hours[2].key==2026100414LL,"next hours parsed in order");
 auto wPlain=ParseWeatherJson(L"{\"current\":{\"temperature_2m\":9,\"weather_code\":3},\"daily\":{\"time\":[\"2026-10-03\"],\"weather_code\":[3],\"temperature_2m_max\":[10],\"temperature_2m_min\":[2]}}");
 expect(wPlain.valid&&wPlain.hours.empty()&&wPlain.isDay,"legacy payload without hourly stays valid");
 Layout wsk;wsk.widgets.weatherSkin=1;expect(Deserialize(Serialize(wsk)).widgets.weatherSkin==1,"weather skin roundtrip");
 auto wskLegacy=Deserialize("{\"version\":1,\"zones\":[],\"widgets\":{\"weatherSkin\":7}}");expect(wskLegacy.widgets.weatherSkin==0,"invalid weather skin self-heals to standard");
 std::vector<std::wstring> shv;PushSearchHistory(shv,L" report ");PushSearchHistory(shv,L"pdf");PushSearchHistory(shv,L" report ");PushSearchHistory(shv,L"   ");
 expect(shv.size()==2&&shv[0]==L"report"&&shv[1]==L"pdf","search history dedupes, trims and moves to front");
 for(int i=0;i<25;++i)PushSearchHistory(shv,std::wstring(L"q")+std::to_wstring(i));
 expect(shv.size()==20&&shv.front()==L"q24","search history stays bounded");
 std::vector<std::wstring> sfv;expect(ToggleSearchFavorite(sfv,L"todo"),"favorite added");expect(!ToggleSearchFavorite(sfv,L" todo "),"favorite toggles off after trim match");expect(sfv.empty()&&!ToggleSearchFavorite(sfv,L""),"empty favorite ignored");
 std::vector<std::wstring> sel;expect(ToggleSelect(sel,L"c:\\a"),"select adds key");expect(ToggleSelect(sel,L"c:\\b")&&sel.size()==2&&sel[0]==L"c:\\a"&&sel[1]==L"c:\\b","selection keeps insertion order");expect(!ToggleSelect(sel,L"c:\\a")&&sel==std::vector<std::wstring>({L"c:\\b"}),"select toggles off");expect(!ToggleSelect(sel,L"")&&sel.size()==1,"empty select key ignored");
 std::vector<std::wstring> selBig;for(int i=0;i<5;++i)ToggleSelect(selBig,std::to_wstring(i),3);expect(selBig.size()==3&&selBig[0]==L"2"&&selBig[2]==L"4","selection stays bounded, oldest evicted");
 std::vector<std::wstring> rp{L"C:\\d\\a.txt",L"C:\\d\\b.txt",L"C:\\d\\c.txt",L"C:\\d\\d.txt"};
 std::vector<std::wstring> rs;expect(SelectRange(rs,rp,1,2)==2&&rs==std::vector<std::wstring>({PathKey(rp[1]),PathKey(rp[2])}),"range select adds both ends");
 expect(SelectRange(rs,rp,3,0)==2&&rs.size()==4&&rs==std::vector<std::wstring>({PathKey(rp[1]),PathKey(rp[2]),PathKey(rp[0]),PathKey(rp[3])}),"reversed range adds only the missing ends");
 expect(SelectRange(rs,rp,-5,99)==0&&rs.size()==4,"out-of-bounds range anchors and targets clamp silently");
 expect(SelectRange(rs,{},0,3)==0,"range select ignores an empty list");
 std::vector<std::wstring> rsCap;expect(SelectRange(rsCap,rp,0,3,2)==4&&rsCap==std::vector<std::wstring>({PathKey(rp[2]),PathKey(rp[3])}),"range select honours the selection cap");
 expect(UniqueName({},L"新建文件夹")==L"新建文件夹"&&UniqueName({L"New Folder"},L"New folder")==L"New folder (2)","unique names dodge case-insensitive clashes");
 expect(UniqueName({L"readme.TXT"},L"readme",L".txt")==L"readme (2).txt"&&UniqueName({L"a",L"a (2)",L"A (3)"},L"a")==L"a (4)","unique numbering skips taken suffixes");
 expect(NavStep(-1,5,1)==0&&NavStep(-1,5,-1)==4,"nav from unfocused enters first or last by direction");
 expect(NavStep(2,5,1)==3&&NavStep(2,5,-1)==1,"nav steps by delta");
 expect(NavStep(0,5,-1)==0&&NavStep(4,5,1)==4,"nav clamps at both ends");
 expect(NavStep(0,0,1)==-1&&NavStep(3,0,-1)==-1,"nav on empty returns none");
 expect(NavStep(1,3,99)==2&&NavStep(1,3,-99)==0,"nav large delta clamps");
 Layout shL;shL.settings.searchHistory={L"a",L"b"};shL.settings.searchFavorites={L"keep"};auto shBack=Deserialize(Serialize(shL));expect(shBack.settings.searchHistory==std::vector<std::wstring>({L"a",L"b"})&&shBack.settings.searchFavorites==std::vector<std::wstring>({L"keep"}),"search history and favorites roundtrip");
 auto shLegacy=Deserialize("{\"version\":1,\"zones\":[],\"settings\":{}}");expect(shLegacy.settings.searchHistory.empty()&&shLegacy.settings.searchFavorites.empty(),"legacy config has no search history");
 auto shMixed=Deserialize("{\"version\":1,\"zones\":[],\"settings\":{\"searchHistory\":[\"ok\",5,\"\",\"x\"]}}");expect(shMixed.settings.searchHistory==std::vector<std::wstring>({L"ok",L"x"}),"non-string history entries dropped");
 MonitorArea tp1{L"\\\\.\\DISPLAY1",RECT{0,0,1920,1040}};MonitorArea tp2{L"\\\\.\\DISPLAY2",RECT{1920,0,4480,1080}};
 auto tpSa=TopologySignature({tp1,tp2});auto tpSb=TopologySignature({tp2,tp1});
 expect(!tpSa.empty()&&tpSa==tpSb,"topology signature is order independent");
 MonitorArea tp1b{L"\\\\.\\DISPLAY1",RECT{0,0,2560,1440}};
 expect(TopologySignature({tp1b,tp2})!=tpSa,"resolution change alters signature");
 expect(TopologySignature({tp1})!=tpSa,"monitor count change alters signature");
 expect(TopologySignature({}).empty(),"empty topology gives empty signature");
 std::map<std::wstring,std::string> tpArc;
 expect(!ArchiveTopology(tpArc,L"","body")&&!ArchiveTopology(tpArc,L"k",""),"empty key or body rejected");
 expect(ArchiveTopology(tpArc,L"k1","b1")&&ArchiveTopology(tpArc,L"k2","b2"),"archives accepted");
 expect(ArchiveTopology(tpArc,L"k1","b1x"),"re-archiving replaces entry");
 std::string tpGot;expect(TakeTopology(tpArc,L"k1",tpGot)&&tpGot=="b1x"&&!TakeTopology(tpArc,L"nope",tpGot),"take returns archived body");
 for(int i=0;i<10;++i)ArchiveTopology(tpArc,std::wstring(L"key")+std::to_wstring(i),"body"+std::to_string(i));
 expect(tpArc.size()==6,"archives stay bounded");
 expect(!ArchiveTopology(tpArc,L"big",std::string(300000,'x')),"oversized body rejected");
 Layout tpSrc;Zone tzp;tzp.id=L"tz1";tzp.name=L"Port";tzp.x=10;tzp.y=20;tzp.width=300;tzp.height=200;tpSrc.zones.push_back(tzp);tpSrc.topologyLast=L"sigA";tpSrc.topologyArchives[L"sigA"]="bodyA";tpSrc.topologyArchives[L"sigB"]="bodyB";
 auto tpBody=Serialize(tpSrc);
 auto tpBack=Deserialize(tpBody);
 expect(tpBack.topologyLast==L"sigA"&&tpBack.topologyArchives.size()==2&&tpBack.topologyArchives[L"sigB"]=="bodyB","topology archives roundtrip");
 expect(tpBack.zones.size()==1&&tpBack.zones[0].name==L"Port","archived body re-parses to same layout");
 auto tpLegacy=Deserialize("{\"version\":1,\"zones\":[]}");
 expect(tpLegacy.topologyLast.empty()&&tpLegacy.topologyArchives.empty(),"legacy config has no topology data");
 auto tpJunk=Deserialize("{\"version\":1,\"zones\":[],\"topology\":{\"last\":\"x\",\"archives\":{\"k\":[1],\"kk\":\"\"}}}");
 expect(tpJunk.topologyLast==L"x"&&tpJunk.topologyArchives.empty(),"invalid archive entries dropped");
 auto tpBad=Deserialize("{\"version\":1,\"zones\":[],\"topology\":5}");
 expect(tpBad.topologyLast.empty(),"junk topology ignored");
 Layout rvL;rvL.settings.revealHotkey=L"Ctrl+Alt+Space";auto rvBack=Deserialize(Serialize(rvL));expect(rvBack.settings.revealHotkey==L"Ctrl+Alt+Space","reveal hotkey roundtrips");
 expect(Deserialize("{\"version\":1,\"zones\":[],\"settings\":{}}").settings.revealHotkey.empty(),"legacy config has no reveal hotkey");
 expect(Deserialize("{\"version\":1,\"zones\":[],\"settings\":{\"revealHotkey\":\"Foo Bar\"}}").settings.revealHotkey.empty(),"invalid reveal hotkey cleared");
 expect(Deserialize("{\"version\":1,\"zones\":[],\"settings\":{\"revealHotkey\":\"\"}}").settings.revealHotkey.empty(),"empty reveal hotkey stays empty");
 Layout rgL;rgL.settings.hotkeyRaise=L"Ctrl+Alt+Q";auto rgBack=Deserialize(Serialize(rgL));expect(rgBack.settings.hotkeyRaise==L"Ctrl+Alt+Q","raise hotkey roundtrips");
 expect(Deserialize("{\"version\":1,\"zones\":[],\"settings\":{}}").settings.hotkeyRaise.empty(),"legacy config has no raise hotkey");
 expect(Deserialize("{\"version\":1,\"zones\":[],\"settings\":{\"hotkeyRaise\":\"Not A Key\"}}").settings.hotkeyRaise.empty(),"invalid raise hotkey cleared");
 expect(BuildDiagnostics(rgL,L"3.10.0",L"x64",L"",20261005).find(L"raise=Ctrl+Alt+Q")!=std::wstring::npos&&BuildDiagnostics(Layout{},L"3.10.0",L"x64",L"",20261005).find(L"raise=none")!=std::wstring::npos,"diagnostics reports raise hotkey");
 auto luA=LunarFromSolar(2026,10,3);expect(luA.valid&&luA.year==2026&&luA.month==8&&luA.day==23&&!luA.leap,"lunar 2026-10-03 is month 8 day 23");
 expect(LunarText(luA)==L"八月廿三","lunar text formats month and day");
 auto luB=LunarFromSolar(2026,2,17);expect(luB.valid&&luB.month==1&&luB.day==1,"2026 spring festival lands on month 1 day 1");
 expect(LunarText(luB)==L"正月初一","lunar text uses zheng yue and chu yi");
 expect(HolidayText(2026,2,17,luB)==L"春节","spring festival holiday");
 auto luC=LunarFromSolar(2026,9,25);expect(luC.valid&&luC.month==8&&luC.day==15&&HolidayText(2026,9,25,luC)==L"中秋节","mid autumn holiday");
 auto luD=LunarFromSolar(2025,7,25);expect(luD.valid&&luD.leap&&luD.month==6&&luD.day==1&&LunarText(luD)==L"闰六月初一","leap month is detected and labelled");
 auto luE=LunarFromSolar(2026,2,16);expect(luE.valid&&luE.month==12&&HolidayText(2026,2,16,luE)==L"除夕","new year eve from lunar last day");
 auto luF=LunarFromSolar(2024,2,9);expect(luF.valid&&luF.month==12&&luF.day==30&&HolidayText(2024,2,9,luF)==L"除夕","new year eve on day 30 works too");
 auto luG=LunarFromSolar(2026,10,1);expect(luG.valid&&luG.month==8&&luG.day==21&&HolidayText(2026,10,1,luG)==L"国庆节","national day beats lunar text");
 expect(HolidayText(2026,4,5,LunarFromSolar(2026,4,5))==L"清明节","qingming formula gives apr 5 in 2026");
 expect(HolidayText(2026,4,4,LunarFromSolar(2026,4,4)).empty(),"day before qingming has no holiday");
 auto luH=LunarFromSolar(2026,10,10);expect(luH.valid&&luH.month==9&&luH.day==1&&LunarText(luH)==L"九月初一","month rolls over to next lunar month");
 auto luBad=LunarFromSolar(2060,1,1);expect(!luBad.valid&&LunarText(luBad).empty(),"out of range dates are invalid");
 expect(!LunarFromSolar(1899,12,31).valid,"dates before the table are invalid");
 expect(NextDue(20261003,1,20261003)==20261004,"next due daily adds one day");
 expect(NextDue(20261003,2,20261003)==20261010,"next due weekly adds seven days");
 expect(NextDue(20261020,3,20261020)==20261103,"next due biweekly crosses into next month");
 expect(NextDue(20261001,1,20261005)==20261005,"next due daily catches up to today from overdue");
 expect(NextDue(20260131,4,20260201)==20260228,"monthly clamps day 31 to feb 28");
 expect(NextDue(20240131,4,20240201)==20240229,"monthly clamps to leap feb 29");
 expect(NextDue(20261215,4,20261215)==20270115,"monthly rolls into next year");
 expect(NextDue(20260131,4,20260601)==20260628,"monthly chain keeps clamped drift");
 expect(NextDue(20261003,0,20261003)==20261003&&NextDue(20261003,9,20261003)==20261003,"invalid repeat kinds leave due untouched");
 Widgets rw340;AddTodo(rw340,L"喝水");AddTodo(rw340,L"交周报");
 rw340.todos[0].repeat=1;rw340.todos[0].due=20261003;rw340.todos[0].reminded=true;rw340.todos[1].repeat=0;
 expect(ToggleTodo(rw340,rw340.todos[0].id)==2&&!rw340.todos[0].done&&rw340.todos[0].due>20261003&&!rw340.todos[0].reminded,"checking a repeating todo rolls its due instead of completing");
 expect(ToggleTodo(rw340,rw340.todos[1].id)==1&&rw340.todos[1].done,"plain todo still toggles done");
 expect(ToggleTodo(rw340,L"nope")==0,"toggling unknown id reports no change");
 rw340.todos[0].done=true;expect(ToggleTodo(rw340,rw340.todos[0].id)==1&&!rw340.todos[0].done,"repeating todo can untoggle from done");
 Layout rl340;rl340.widgets=rw340;auto rt340=Deserialize(Serialize(rl340));
 expect(rt340.widgets.todos[0].repeat==1&&rt340.widgets.todos[0].due==rw340.todos[0].due&&rt340.widgets.todos[1].repeat==0,"todo repeat roundtrip");
 auto rLegacy=Deserialize("{\"version\":1,\"zones\":[],\"widgets\":{\"todos\":[{\"id\":\"a\",\"text\":\"t\"}]}}");expect(rLegacy.widgets.todos.size()==1&&rLegacy.widgets.todos[0].repeat==0,"legacy todo without repeat defaults none");
 auto rBad=Deserialize("{\"version\":1,\"zones\":[],\"widgets\":{\"todos\":[{\"id\":\"a\",\"text\":\"t\",\"repeat\":9}]}}");expect(rBad.widgets.todos[0].repeat==0,"out of range repeat self heals");
 expect(ToggleTodo(rw340,rw340.todos[0].id)==2&&rw340.todos[0].due>DueFromOffset(0),"monthly-free daily todo rolls past today");
 expect(ClampBackdropKind(0)==0&&ClampBackdropKind(1)==1,"backdrop kinds 0 and 1 pass through");
 expect(ClampBackdropKind(2)==0&&ClampBackdropKind(-3)==0&&ClampBackdropKind(7)==0,"illegal backdrop kinds clamp to mica");
 Layout sl350;sl350.settings.backdrop=1;auto srt350=Deserialize(Serialize(sl350));expect(srt350.settings.backdrop==1,"backdrop setting roundtrip");
 auto sbad350=Deserialize("{\"version\":1,\"zones\":[],\"settings\":{\"backdrop\":7}}");expect(sbad350.settings.backdrop==0,"numeric-but-illegal backdrop self heals");
 auto stype350=Deserialize("{\"version\":1,\"zones\":[],\"settings\":{\"backdrop\":\"acrylic\"}}");expect(stype350.settings.backdrop==0,"wrong-typed backdrop self heals");
 auto sleg350=Deserialize("{\"version\":1,\"zones\":[]}");expect(sleg350.settings.backdrop==0,"legacy layout without backdrop defaults mica");
 std::vector<std::wstring> fin360{L"C:\\a\\x.PNG",L"C:\\a\\notes.txt",L"C:\\a\\z.jpg",L"C:\\a\\noext",L"C:\\a\\w.gif"};
 auto fout360=FilterImagePaths(fin360);
 expect(fout360.size()==3&&fout360[0]==fin360[0]&&fout360[1]==fin360[2]&&fout360[2]==fin360[4],"FilterImagePaths keeps only images in order");
 std::vector<std::wstring> fnone360;expect(FilterImagePaths(fnone360).empty(),"FilterImagePaths of no paths is empty");
 Layout wl360;wl360.widgets.clockBg=L"D:\\pics\\sunrise.png";wl360.widgets.clockBgTrans=60;auto wrt360=Deserialize(Serialize(wl360));expect(wrt360.widgets.clockBg==L"D:\\pics\\sunrise.png"&&wrt360.widgets.clockBgTrans==60,"clock background roundtrip");
 auto wlow360=Deserialize("{\"version\":1,\"zones\":[],\"widgets\":{\"clockBg\":\"D:\\\\pics\",\"clockBgTrans\":7}}");expect(wlow360.widgets.clockBg==L"D:\\pics"&&wlow360.widgets.clockBgTrans==20,"tiny clock transparency clamps to floor");
 auto wbad360=Deserialize("{\"version\":1,\"zones\":[],\"widgets\":{\"clockBgTrans\":\"mist\"}}");expect(wbad360.widgets.clockBgTrans==100&&wbad360.widgets.clockBg.empty(),"wrong-typed clock transparency self heals");
 auto wleg360=Deserialize("{\"version\":1,\"zones\":[]}");expect(wleg360.widgets.clockBg.empty()&&wleg360.widgets.clockBgTrans==100,"legacy widgets without clock background default clear");
 Layout d370;Zone zz370;zz370.name=L"ZONESecretName";zz370.entries.push_back({L"e1",L"C:\\ENTRYSECRET.txt",L""});zz370.pins.push_back(L"C:\\PINSECRET.lnk");zz370.mappedFolder=L"D:\\MAPPEDSECRET";d370.zones.push_back(zz370);
 d370.settings.syncUrl=L"https://secret-host.example/dav";d370.settings.syncUser=L"myuser";d370.settings.syncPass=L"s3cretpw";
 d370.widgets.noteText=L"NOTESECRET";d370.widgets.todos.push_back({L"t1",L"TODOSECRET",false,20261001,false,0,0});
 d370.widgets.todos.push_back({L"t2",L"b",true,0,false,2,0});
 d370.widgets.todos.push_back({L"t3",L"c",false,0,false,0,2});
 d370.widgets.clockVisible=true;
 auto diag370=BuildDiagnostics(d370,L"3.7.0",L"x64",L"10.0.26100.1",20261004);
 expect(diag370.find(L"version=3.7.0")!=std::wstring::npos&&diag370.find(L"zones=1")!=std::wstring::npos&&diag370.find(L"os=10.0.26100.1")!=std::wstring::npos,"diagnostics carries version and zone count");
 expect(diag370.find(L"todos=3")!=std::wstring::npos&&diag370.find(L"done=1")!=std::wstring::npos&&diag370.find(L"overdue=1")!=std::wstring::npos&&diag370.find(L"repeating=1")!=std::wstring::npos&&diag370.find(L"flags=1")!=std::wstring::npos,"diagnostics counts todo states against today");
 expect(diag370.find(L"webdav=configured")!=std::wstring::npos&&diag370.find(L"clock=1")!=std::wstring::npos&&diag370.find(L"hotkey=Ctrl+Alt+G")!=std::wstring::npos,"diagnostics reports webdav state widget flags and hotkey");
 expect(diag370.find(L"SECRET")==std::wstring::npos&&diag370.find(L"secret")==std::wstring::npos&&diag370.find(L"myuser")==std::wstring::npos&&diag370.find(L"s3cretpw")==std::wstring::npos,"diagnostics is privacy filtered with no user content");
 auto dEmpty370=BuildDiagnostics(Layout{},L"1.0",L"ARM64",L"",20261004);
 expect(dEmpty370.find(L"zones=0")!=std::wstring::npos&&dEmpty370.find(L"webdav=off")!=std::wstring::npos&&dEmpty370.find(L"os=unknown")!=std::wstring::npos,"default layout diagnostics is all-zero with webdav off");
 expect(dEmpty370.find(L"topologyLast=none")!=std::wstring::npos&&dEmpty370.find(L"clockStyle=digital")!=std::wstring::npos,"diagnostics normalizes empty optional values");
 auto md0=ParseInlineMarkdown(L"plain text");
 expect(md0.size()==1&&md0[0].style==0&&md0[0].text==L"plain text","markdown plain text is one segment");
 auto md1=ParseInlineMarkdown(L"**urgent** call");
 expect(md1.size()==2&&md1[0].style==1&&md1[0].text==L"urgent"&&md1[1].style==0&&md1[1].text==L" call","markdown bold segment split");
 auto md2=ParseInlineMarkdown(L"~~done~~ and `code`");
 expect(md2.size()==3&&md2[0].style==2&&md2[1].style==0&&md2[2].style==3&&md2[2].text==L"code","markdown strike and code styles");
 auto md3=ParseInlineMarkdown(L"#home fix #later");
 expect(md3.size()==3&&md3[0].style==4&&md3[0].text==L"#home"&&md3[1].style==0&&md3[2].style==4,"markdown tags at word starts");
 auto md4=ParseInlineMarkdown(L"a#b unclosed **x");
 expect(md4.size()==1&&md4[0].style==0&&md4[0].text==L"a#b unclosed **x","markdown literal when no boundary or unclosed");
 TodoItem tf1;tf1.due=20200101;TodoItem tf2;tf2.due=20991231;tf2.repeat=1;
 expect(TodoMatchesFilter(tf1,3)&&!TodoMatchesFilter(tf2,3)&&!TodoMatchesFilter(tf1,4)&&TodoMatchesFilter(tf2,4),"overdue and repeating filters select correctly");
 TodoItem tq;tq.text=L"Buy Milk";
 expect(TodoMatchesQuery(tq,L"")&&TodoMatchesQuery(tq,L"milk")&&TodoMatchesQuery(tq,L"buy mi")&&!TodoMatchesQuery(tq,L"juice"),"query is case-insensitive substring");
 Widgets bw380;AddTodo(bw380,L"a");auto idAx=bw380.todos[0].id;AddTodo(bw380,L"b");auto idBy=bw380.todos[1].id;AddTodo(bw380,L"c");auto idCz=bw380.todos[2].id;
 expect(RemoveTodos(bw380,{idAx,idCz})==2&&bw380.todos.size()==1&&bw380.todos[0].text==L"b","bulk remove keeps order and counts");
 expect(RemoveTodos(bw380,{})==0&&RemoveTodos(bw380,{L"ghost"})==0&&bw380.todos.size()==1&&bw380.todos[0].id==idBy,"bulk remove no-op on empty or unknown ids");
 expect(PreviewKind(L"C:\\p\\photo.PNG")==1&&PreviewKind(L"C:\\p\\note.md")==2&&PreviewKind(L"C:\\p\\setup.exe")==0&&PreviewKind(L"C:\\p\\README")==0,"PreviewKind classifies image, text and unknown");
 expect(IsTextPath(L"C:\\p\\run.ps1")&&IsTextPath(L"C:\\p\\icon.svg")&&IsTextPath(L"C:\\p\\a.MD")&&!IsTextPath(L"C:\\p\\book.zip")&&!IsTextPath(L"C:\\p\\noextension"),"IsTextPath covers code and markup while rejecting archives and extension-less names");
 {
  std::vector<char> u8bom{(char)0xEF,(char)0xBB,(char)0xBF,'A',(char)0xE4,(char)0xB8,(char)0xAD};
  std::vector<char> le130{(char)0xFF,(char)0xFE,0x48,0x00,0x69,0x00};
  std::vector<char> be130{(char)0xFE,(char)0xFF,0x00,0x48,0x00,0x69};
  std::vector<char> crlf130{'a','\r','\n','b','\r','c'};
  std::vector<char> gbk130{(char)0xD6,(char)0xD0,(char)0xCE,(char)0xC4};
  expect(DecodeNeutralText(u8bom)==L"A中","utf-8 bom stripped and multibyte decoded");
  expect(DecodeNeutralText(le130)==L"Hi"&&DecodeNeutralText(be130)==L"Hi","utf-16 detected in both endiannesses");
  expect(DecodeNeutralText(crlf130)==L"a\nb\nc","mixed newlines normalised to lf");
  expect(DecodeNeutralText(gbk130).size()==2,"legacy ansi bytes still decode through the fallback");
  expect(DecodeNeutralText(std::vector<char>{}).empty(),"empty input decodes to empty text");
 }
 expect(ClampPreviewText(L"line1\nline2\nline3\n",8)==L"line1"&&ClampPreviewText(L"short",8)==L"short"&&ClampPreviewText(L"abcdefghij",0)==L"abcdefghij","ClampPreviewText cuts on a line boundary and leaves short text untouched");
 expect(PreviewSizeText(0)==L"0 B"&&PreviewSizeText(-5)==L"0 B"&&PreviewSizeText(1023)==L"1023 B","PreviewSizeText renders bytes below one kilobyte");
 expect(PreviewSizeText(1536)==L"1.5 KB"&&PreviewSizeText(2LL*1024*1024)==L"2.0 MB"&&PreviewSizeText(3LL*1024*1024*1024+512LL*1024*1024)==L"3.50 GB","PreviewSizeText scales to KB, MB and GB");
 expect(ProgressPercent(0,10)==0&&ProgressPercent(5,0)==0&&ProgressPercent(-3,10)==0,"ProgressPercent stays zero without a usable total");
 expect(ProgressPercent(10,10)==100&&ProgressPercent(24,10)==100&&ProgressPercent(1,3)==33&&ProgressPercent(2,3)==67,"ProgressPercent rounds and caps at one hundred");
 expect(OpOutcome(3,0,false)==1&&OpOutcome(0,0,false)==0&&OpOutcome(0,0,true)==4,"OpOutcome tells success, nothing done and pure cancel apart");
 expect(OpOutcome(2,1,false)==2&&OpOutcome(0,2,false)==3&&OpOutcome(2,0,true)==1&&OpOutcome(2,1,true)==2,"OpOutcome reports partial success, total failure and cancelled batches");
 expect(DropOperation(false,false)==0&&DropOperation(false,true)==0,"a normal zone keeps the reference drop whatever the modifier says");
 expect(DropOperation(true,false)==1&&DropOperation(true,true)==2,"a mapped zone copies on drop and moves on Shift+drop");
 expect(SelfNesting(root,root)&&SelfNesting(root,root+L"\\"),"a folder dropped onto itself counts as nesting");
 expect(SelfNesting(root,inner),"a folder dropped into its own subfolder counts as nesting");
 expect(!SelfNesting(inner,root)&&!SelfNesting(root,elsewhere),"moving a subfolder up to its parent and unrelated folders are not nesting");
 expect(!SelfNesting(L"",root)&&!SelfNesting(root,L""),"empty source or destination is never nesting");
 expect(IsReservedDeviceName(L"CON")&&IsReservedDeviceName(L"con.txt")&&IsReservedDeviceName(L"NUL")&&IsReservedDeviceName(L"COM1")&&IsReservedDeviceName(L"lpt9.log")&&IsReservedDeviceName(L"CLOCK$"),"reserved device names are recognised");
 expect(!IsReservedDeviceName(L"content.txt")&&!IsReservedDeviceName(L"console")&&!IsReservedDeviceName(L"comm1")&&!IsReservedDeviceName(L"lpt0")&&!IsReservedDeviceName(L"lpt10")&&!IsReservedDeviceName(L""),"ordinary names pass the reserved check");
 {
  std::vector<char> split3140{'A',(char)0xE4,(char)0xB8,(char)0xAD,(char)0xE2};
  expect(DecodeNeutralText(split3140)==L"A中","a trailing utf-8 sequence cut by the head read does not corrupt the text");
 }
report<<"TOTAL "<<passed<<" passed\n";
}
}
